# Test-model

We will load the trained model and test it on the test storms using ACE preliminary parameters.

We will also plot the storms that we will use in the paper and save the predictions to a csv format to get the metrics in the next notebook

In [1]:
# External Libraries
import numpy as np
import torch
import torchinfo
import matplotlib.pyplot as plt
import pandas as pd
import os
from IPython.display import display
import time
import matplotlib.dates as mdates
from IPython.display import display, HTML
import pickle

# Local Libraries
import reldi_modules
import utils
import pre_processing
import storm_dates
import metrics
import constants

# configs
display(HTML("<style>.container { width:100% !important; }</style>"))
pd.set_option("display.max_columns", None)

if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"CUDA is available. Using GPU: {torch.cuda.get_device_name(0)}")
else:
    device = torch.device("cpu")
    print("CUDA is not available. Using CPU.")

/mnt/data/ldi-forecast-1and2-hours/ldi-torch/lib/python3.12/site-packages/tslearn/bases/bases.py:15: UserWarning: h5py not installed, hdf5 features will not be supported.
Install h5py to use hdf5 features: http://docs.h5py.org/
  warn(h5py_msg)

CUDA is available. Using GPU: NVIDIA GeForce RTX 3090

In [2]:
LOOKBACK = 12 * 8
NUM_OUTPUTS_MODEL = 3
QUANTILES = [0.05, 0.95]
BATCH_SIZE = 256
D_MODEL = 128
FORECAST_STEPS = 2

indices_cols = ["SYM_H"]
ldi_cols = []
for station in constants.STATIONS:
    indices_cols.append(f"LDi_{station}")
    ldi_cols.append(f"LDi_{station}")

COLS_TO_USE = [
    constants.B_MAGNITUDE_COL_NAME,
    constants.BZ_COL_NAME,
    constants.PROTON_DENSITY_COL_NAME,
    constants.PROTON_SPEED_COL_NAME,
    constants.PROTON_TEMPERATURE_COL_NAME,
    constants.PRESSURE_COL_NAME,
]

COLS_TO_USE_NO_DERIVED = constants.COLS_TO_USE_NO_DERIVED.copy()

COLS_TO_SCALE_LOG = [
    constants.PROTON_DENSITY_COL_NAME,
    constants.PROTON_TEMPERATURE_COL_NAME,
    constants.PROTON_SPEED_COL_NAME,
    constants.PRESSURE_COL_NAME,
]

COLS_TO_SCALE_STANDARD = [constants.PROTON_SPEED_COL_NAME, constants.BZ_COL_NAME]

COLS_TO_SCALE_ROBUST = [
    constants.PROTON_TEMPERATURE_COL_NAME,
    constants.PROTON_DENSITY_COL_NAME,
    constants.PRESSURE_COL_NAME,
    constants.B_MAGNITUDE_COL_NAME,
]


stations_data_path = "./data/stations_data_magnetic.csv"
stations_data = pd.read_csv(stations_data_path)

min_lat = 0
max_lat = 90

min_lon = -180
max_lon = 180


SHIFT_NAMES = []
SHIFT_VALUES = []
SHIFT_FORWARD = []

for i in range(FORECAST_STEPS):
    SHIFT_VALUES.append(-(i + 1) * 12)
    SHIFT_FORWARD.append((i + 1) * 12)
    SHIFT_NAMES.append(f"-{i + 1}h")

SHIFT_HOUR = 12
THRESHOLD_PLOT = -200

NUM_FEATS_SOLAR_WIND = len(COLS_TO_USE)

rotation_columns = []
NUM_FEATS_LDI = 5
NUM_FEATS_POSITION = 4
LABEL_COLUMNS = []
COLS_PLOT = COLS_TO_USE.copy()
INDEX_COLUMNS = []
station_columns_decoder = {}
ldi_columns_decoder = {}
station_labels = {}
station_columns = {}
station_first_ldi = {}
total_station_columns = {}
station_to_labels = {}

for station in constants.STATIONS:
    station_to_labels[station] = []
    station_first_ldi[station] = f"LDi_{station}"
    station_columns[station] = [
        f"LDi_{station}",
        f"MLT_{station}_sin",
        f"MLT_{station}_cos",
        f"Latitude_{station}",
        f"Longitude_{station}",
    ]
    labels_station = []
    station_columns_decoder[station] = []
    for shift_suffix in SHIFT_NAMES:
        labels_station.append(f"LDi_{station}{shift_suffix}")
        station_columns_decoder[station].append(f"MLT_{station}_sin{shift_suffix}")
        station_columns_decoder[station].append(f"MLT_{station}_cos{shift_suffix}")
        station_columns_decoder[station].append(f"Latitude_{station}{shift_suffix}")
        station_columns_decoder[station].append(f"Longitude_{station}{shift_suffix}")

    station_labels[station] = labels_station
    ldi_columns_decoder[station] = [f"LDi_{station}"]
    for shift_suffix in SHIFT_NAMES[:-1]:
        ldi_columns_decoder[station].append(f"LDi_{station}{shift_suffix}")

    rotation_columns.append(f"MLT_{station}_sin")
    rotation_columns.append(f"MLT_{station}_cos")
    rotation_columns.append(f"Latitude_{station}")
    rotation_columns.append(f"Longitude_{station}")
    for i in range(FORECAST_STEPS):
        LABEL_COLUMNS.append(f"LDi_{station}-{i + 1}h")
        station_to_labels[station].append(f"LDi_{station}-{i + 1}h")
    INDEX_COLUMNS.append(f"LDi_{station}")
    COLS_PLOT.append(f"LDi_{station}")
    total_station_columns[station] = (
        station_columns[station].copy() + COLS_TO_USE.copy()
    )


def inside_quantile(row, label, q_lower, q_upper):
    return row[q_lower] <= row[label] <= row[q_upper]


for station in constants.STATIONS:
    os.makedirs(f"figs/{station}", exist_ok=True)
    os.makedirs(f"figs_colors/{station}", exist_ok=True)
    os.makedirs(f"predictions/{station}", exist_ok=True)
    os.makedirs(f"figs/{station}/bfe/", exist_ok=True)
    os.makedirs(f"figs_colors/{station}/bfe/", exist_ok=True)
    os.makedirs(f"figs/{station}/forecasts/", exist_ok=True)
    os.makedirs(f"figs_colors/{station}/forecasts/", exist_ok=True)


SAVE_FIGS = True

In [3]:
all_timeline_data_path = "./data/all_timeline"

ldi_paths = [
    "./data/LDI_ABG.csv",
    "./data/LDI_MMB.csv",
    "./data/LDI_CLF.csv",
    "./data/LDI_TUC.csv",
    "./data/LDI_HON.csv",
    "./data/LDI_SFS.csv",
]

In [4]:
model = torch.load("reldi_1to2h_full_model.pt", weights_only=False).to(device)
model.eval()

solar_wind_input_example = torch.randn(32, LOOKBACK, len(COLS_TO_USE)).to(device)
ldi_input_example = torch.randn(32, LOOKBACK, NUM_FEATS_LDI).to(device)
decoder_input_example = torch.randn(32, FORECAST_STEPS, NUM_FEATS_LDI).to(device)
decoder_input_inference_position_example = torch.randn(
    32, FORECAST_STEPS, NUM_FEATS_POSITION
).to(device)
decoder_input_inference_ldi_example = torch.randn(32, 1, 1).to(device)

print(f"{solar_wind_input_example.shape = }")
print(f"{ldi_input_example.shape = }")
print(f"{decoder_input_example.shape = }")
print(f"{decoder_input_inference_position_example.shape = }")
print(f"{decoder_input_inference_ldi_example.shape = }")

# Teacher forcing
(
    output_teacher_forcing,
    quantile_lower_teacher_forcing,
    quantile_upper_teacher_forcing,
) = model(solar_wind_input_example, ldi_input_example, decoder_input_example)
print(f"{output_teacher_forcing.shape = }")
print(f"{quantile_lower_teacher_forcing.shape = }")
print(f"{quantile_upper_teacher_forcing.shape = }")

# Inference
output_inference, quantile_lower_inference, quantile_upper_inference = model.inference(
    solar_wind_input_example,
    ldi_input_example,
    decoder_input_inference_ldi_example,
    decoder_input_inference_position_example,
)
print(f"{output_inference.shape = }")
print(f"{quantile_lower_inference.shape = }")
print(f"{quantile_upper_inference.shape = }")


print(
    torchinfo.summary(
        model,
        input_data=(solar_wind_input_example, ldi_input_example, decoder_input_example),
    )
)

solar_wind_input_example.shape = torch.Size([32, 96, 6])
ldi_input_example.shape = torch.Size([32, 96, 5])
decoder_input_example.shape = torch.Size([32, 2, 5])
decoder_input_inference_position_example.shape = torch.Size([32, 2, 4])
decoder_input_inference_ldi_example.shape = torch.Size([32, 1, 1])
output_teacher_forcing.shape = torch.Size([32, 2, 1])
quantile_lower_teacher_forcing.shape = torch.Size([32, 2, 1])
quantile_upper_teacher_forcing.shape = torch.Size([32, 2, 1])
output_inference.shape = torch.Size([32, 2, 1])
quantile_lower_inference.shape = torch.Size([32, 2, 1])
quantile_upper_inference.shape = torch.Size([32, 2, 1])
==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
RELDi                                    [32, 2, 1]                --
├─Encoder: 1-1                           [32, 2, 128]              --
│    └─Sequential: 2-1                   [32, 128, 96]             --
│    │    └─CausalConv1d: 3-1            [32, 128, 96]             5,504
│    │    └─SiLU: 3-2                    [32, 128, 96]             --
│    │    └─CausalConv1d: 3-3            [32, 128, 96]             82,048
│    │    └─SiLU: 3-4                    [32, 128, 96]             --
│    │    └─CausalConv1d: 3-5            [32, 128, 96]             49,280
│    │    └─SiLU: 3-6                    [32, 128, 96]             --
│    └─Conv1d: 2-2                       [32, 128, 96]             896
│    └─Dropout: 2-3                      [32, 128, 96]             --
│    └─MultiheadAttention: 2-4           [32, 96, 128]             67,328
│    └─Dropout: 2-5                      [32, 96, 128]             --
│    └─LSTM: 2-6                         [32, 96, 256]             264,192
│    └─Dropout: 2-7                      [32, 2, 128]              --
├─Decoder: 1-2                           [32, 2, 1]                --
│    └─Sequential: 2-8                   [32, 2, 64]               --
│    │    └─Linear: 3-7                  [32, 2, 64]               128
│    │    └─SiLU: 3-8                    [32, 2, 64]               --
│    └─Sequential: 2-9                   [32, 2, 64]               --
│    │    └─Linear: 3-9                  [32, 2, 64]               320
│    │    └─SiLU: 3-10                   [32, 2, 64]               --
│    └─MultiheadAttention: 2-10          [32, 2, 64]               24,832
│    └─MultiheadAttention: 2-11          [32, 2, 128]              66,048
│    └─Sequential: 2-12                  [32, 2, 128]              --
│    │    └─Linear: 3-11                 [32, 2, 512]              66,048
│    │    └─SiLU: 3-12                   [32, 2, 512]              --
│    │    └─Dropout: 3-13                [32, 2, 512]              --
│    │    └─Linear: 3-14                 [32, 2, 128]              65,664
│    │    └─LayerNorm: 3-15              [32, 2, 128]              256
│    └─Linear: 2-13                      [32, 2, 1]                129
│    └─Sequential: 2-14                  [32, 2, 2]                --
│    │    └─Linear: 3-16                 [32, 2, 64]               8,256
│    │    └─SiLU: 3-17                   [32, 2, 64]               --
│    │    └─Dropout: 3-18                [32, 2, 64]               --
│    │    └─Linear: 3-19                 [32, 2, 2]                130
==========================================================================================
Total params: 701,059
Trainable params: 701,059
Non-trainable params: 0
Total mult-adds (Units.GIGABYTES): 1.24
==========================================================================================
Input size (MB): 0.14
Forward/backward pass size (MB): 19.37
Params size (MB): 2.17
Estimated Total Size (MB): 21.68
==========================================================================================

/mnt/data/ldi-forecast-1and2-hours/ldi-torch/lib/python3.12/site-packages/torchinfo/torchinfo.py:477: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  action_fn=lambda data: sys.getsizeof(data.storage()),

In [5]:
all_df_ace_imf_provisional = utils.read_data(
    all_timeline_data_path, pattern_to_read=["ace_imf_provisonal_5_min"]
)

all_df_ace_imf_provisional = pd.concat(all_df_ace_imf_provisional)

test_dfs_ace_imf = []

offset = pd.DateOffset(hours=24)

for start_date, end_date, storm_index in storm_dates.TEST_STORMS:
    sd = pd.to_datetime(start_date) - offset
    ed = pd.to_datetime(end_date) + offset
    storm = all_df_ace_imf_provisional[sd:ed].copy()
    storm = pre_processing.preprocess_ace_imf_provisional(storm)
    test_dfs_ace_imf.append(storm.copy())

del all_df_ace_imf_provisional

In [6]:
all_df_ace_swepam_provisional = utils.read_data(
    all_timeline_data_path, pattern_to_read=["ace_swepam_provisional_5_min"]
)

all_df_ace_swepam_provisional = pd.concat(all_df_ace_swepam_provisional)

test_dfs_ace_swepam = []

for start_date, end_date, storm_index in storm_dates.TEST_STORMS:
    sd = pd.to_datetime(start_date) - offset
    ed = pd.to_datetime(end_date) + offset
    storm = all_df_ace_swepam_provisional[sd:ed].copy()
    storm = pre_processing.preprocess_ace_swepam_provisional(storm)
    test_dfs_ace_swepam.append(storm.copy())

del all_df_ace_swepam_provisional

In [7]:
all_omni = utils.read_data(all_timeline_data_path, pattern_to_read=["omni"])
all_omni = pd.concat(all_omni)

In [8]:
ldi = [
    pd.read_csv(ldi_path, parse_dates=["datetime"], index_col="datetime")
    for ldi_path in ldi_paths
]
ldi = pd.concat(ldi, axis=1)

for station in constants.STATIONS:
    ldi[f"Longitude_{station}"] = stations_data[stations_data["IAGA_CODE"] == station][
        "LONGITUDE_M"
    ].values[0]
    ldi[f"Latitude_{station}"] = stations_data[stations_data["IAGA_CODE"] == station][
        "LATITUDE_M"
    ].values[0]

In [9]:
test_storms = []

for i in range(len(test_dfs_ace_imf)):
    storm = test_dfs_ace_imf[i].join(test_dfs_ace_swepam[i])
    storm = storm.join(ldi)
    test_storms.append(storm)

In [10]:
medians = {
    "Bmag": 6.447526,
    "Bz": -0.270270,
    "Proton_density": 4.700450,
    "Proton_speed": 456.152500,
    "Proton_temp": 75410.697500,
    "Pressure": 1.984565,
}

In [11]:
for i, _ in enumerate(test_storms):
    test_storms[i].loc[:, COLS_TO_USE_NO_DERIVED] = (
        test_storms[i].loc[:, COLS_TO_USE_NO_DERIVED].interpolate()
    )
    test_storms[i].loc[:, COLS_TO_USE_NO_DERIVED] = (
        test_storms[i].loc[:, COLS_TO_USE_NO_DERIVED].ffill()
    )
    test_storms[i].loc[:, COLS_TO_USE_NO_DERIVED] = (
        test_storms[i].loc[:, COLS_TO_USE_NO_DERIVED].bfill()
    )
    test_storms[i].loc[:, COLS_TO_USE_NO_DERIVED] = (
        test_storms[i].loc[:, COLS_TO_USE_NO_DERIVED].fillna(medians)
    )

for i, storm in enumerate(test_storms):
    test_storms[i] = pre_processing.calculate_derived_params(storm)

for i, storm in enumerate(test_storms):
    test_storms[i] = test_storms[i].astype("float32")

In [12]:
blacklist_storms = {
    "ABG": [93, 103, 109],
    "MMB": [93, 94],
    "CLF": [],
    "TUC": [],
    "HON": [],
    "SFS": [95],
}

blacklist_dates = {
    "ABG": [],
    "MMB": [],
    "CLF": [],
    "TUC": [
        (
            "2023-03-28 00:00:00",
            "2023-04-01 00:00:00",
        ),  # Storm 96 bunch of NAs at the end
    ],
    "HON": [
        ("2024-06-30 00:00:00", "2024-07-05 00:00:00"),
    ],
    "SFS": [],
}

for start_date, end_date, index in storm_dates.TEST_STORMS:
    for station, blacklist in blacklist_storms.items():
        if index in blacklist:
            for storm_ind in range(len(test_storms)):
                if pd.to_datetime(start_date) in test_storms[storm_ind].index:
                    print(f"Blacklisting test storm {index} for station {station}")
                    df_tmp = test_storms[storm_ind].copy()
                    df_tmp[f"LDi_{station}"] = np.nan
                    test_storms[storm_ind] = df_tmp


for station, dates in blacklist_dates.items():
    for invalid_date in dates:
        if type(invalid_date) is tuple:
            start_invalid = pd.to_datetime(invalid_date[0])
            end_invalid = pd.to_datetime(invalid_date[1])

            for storm_ind in range(len(test_storms)):
                if (
                    start_invalid in test_storms[storm_ind].index
                    or end_invalid in test_storms[storm_ind].index
                ):
                    print(
                        f"Invalidating testing tuple for {station}",
                        start_invalid,
                        end_invalid,
                    )
                    df_tmp = test_storms[storm_ind].copy()
                    df_tmp.loc[start_invalid:end_invalid, f"LDi_{station}"] = np.nan
                    df_tmp[f"LDi_{station}"] = df_tmp[f"LDi_{station}"].interpolate()
                    test_storms[storm_ind] = df_tmp

        else:
            invalid_d = pd.to_datetime(invalid_date)
            print(f"Invalidating date for {station}", invalid_d)

            for storm_ind in range(len(test_storms)):
                if invalid_d in test_storms[storm_ind].index:
                    print(f"Invalidating testing date for {station}", invalid_d)
                    df_tmp = test_storms[storm_ind].copy()
                    df_tmp.loc[invalid_d, f"LDi_{station}"] = np.nan
                    df_tmp[f"LDi_{station}"] = df_tmp[f"LDi_{station}"].interpolate()
                    test_storms[storm_ind] = df_tmp

Blacklisting test storm 93 for station ABG
Blacklisting test storm 93 for station MMB
Blacklisting test storm 94 for station MMB
Blacklisting test storm 95 for station SFS
Blacklisting test storm 103 for station ABG
Blacklisting test storm 109 for station ABG
Invalidating testing tuple for TUC 2023-03-28 00:00:00 2023-04-01 00:00:00
Invalidating testing tuple for HON 2024-06-30 00:00:00 2024-07-05 00:00:00

In [13]:
def normalize_latitude(values, min_value=min_lat, max_value=max_lat):
    return [
        2 * (np.abs(value) - min_value) / (max_value - min_value) - 1
        for value in values
    ]


def normalize_longitude(values, min_value=min_lon, max_value=max_lon):
    return [
        2 * (np.abs(value) - min_value) / (max_value - min_value) - 1
        for value in values
    ]


def encode_MLT(mlt):
    mlt_sin = np.sin(2 * np.pi * mlt / 24)
    mlt_cos = np.cos(2 * np.pi * mlt / 24)
    return np.array([mlt_sin, mlt_cos])


# Save the scalers to the experiments folder
with open("scalerStandard.pkl", "rb") as f:
    scalerStandard = pickle.load(f)
with open("scalerRobust.pkl", "rb") as f:
    scalerRobust = pickle.load(f)
with open("labelScaler.pkl", "rb") as f:
    labelScaler = pickle.load(f)

for i, storm in enumerate(test_storms):
    test_storms[i][COLS_TO_SCALE_LOG] = pre_processing.scaleLog(
        test_storms[i][COLS_TO_SCALE_LOG]
    )
    test_storms[i][COLS_TO_SCALE_STANDARD] = scalerStandard.transform(
        test_storms[i][COLS_TO_SCALE_STANDARD]
    )
    test_storms[i][COLS_TO_SCALE_ROBUST] = scalerRobust.transform(
        test_storms[i][COLS_TO_SCALE_ROBUST]
    )

    for station in constants.STATIONS:
        test_storms[i][f"LDi_{station}"] = labelScaler.transform(
            test_storms[i][f"LDi_{station}"].values.reshape(-1, 1)
        )
        test_storms[i][f"Latitude_{station}"] = normalize_latitude(
            test_storms[i][f"Latitude_{station}"]
        )
        test_storms[i][f"Longitude_{station}"] = normalize_longitude(
            test_storms[i][f"Longitude_{station}"]
        )
        mlts = test_storms[i].apply(
            lambda row: encode_MLT(row[f"MLT_{station}"]), axis=1
        )
        test_storms[i][[f"MLT_{station}_sin", f"MLT_{station}_cos"]] = pd.DataFrame(
            mlts.tolist(), index=test_storms[i].index
        )
    test_storms[i] = test_storms[i].astype("float32")

/mnt/data/ldi-forecast-1and2-hours/ldi-torch/lib/python3.12/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.6.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/mnt/data/ldi-forecast-1and2-hours/ldi-torch/lib/python3.12/site-packages/sklearn/base.py:440: InconsistentVersionWarning: Trying to unpickle estimator RobustScaler from version 1.6.1 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [14]:
def plot_storm_local(
    df_p, df_s, station, color, start_date, end_date, col_name, title_text="", ax=None
):
    if ax is None:
        fig, ax = plt.subplots(1, 1, figsize=(16, 8))

    sd = pd.to_datetime(start_date)
    ed = pd.to_datetime(end_date)

    df_pred = df_p[sd:ed].copy()
    df_sym = df_s[sd:ed].copy()

    month = df_pred.index[len(df_pred) // 2].month_name()
    year = df_pred.index[len(df_pred) // 2].year

    (lsym,) = ax.plot(
        df_sym[df_pred.index[0] : df_pred.index[-1]].index,
        df_sym[df_pred.index[0] : df_pred.index[-1]]["SYM_H"],
        color="black",
        alpha=0.4,
        label=f"SYM-H",
    )

    ax.set_xlabel(f"{month} of {year}", fontsize=25)
    ax.set_ylabel("Disturbance (nT)", fontsize=25)

    ax.set_title(title_text, fontsize=25)

    (lpred,) = ax.plot(
        df_pred.index,
        df_pred[f"Predicted_{col_name}"],
        label=f"Predicted LDi {station}",
        color=color,
        alpha=0.6,
        linewidth=2,
    )
    (lobs,) = ax.plot(
        df_pred.index,
        df_pred[f"Observed_{col_name}"],
        label=f"Observed LDi {station}",
        color="blue",
        alpha=0.6,
        linewidth=2,
    )
    (lconf,) = ax.plot(
        df_pred.index[0],
        df_pred[f"Observed_{col_name}"].iloc[0],
        label=f"90% confidence",
        color="lightblue",
        alpha=0.8,
        linewidth=2,
    )

    plt.setp(ax.spines.values(), lw=2, color="black", alpha=1)

    ax.xaxis_date()

    ax.fill_between(
        df_pred.index,
        df_pred[f"Quantile_05_{col_name}"],
        df_pred[f"Quantile_95_{col_name}"],
        alpha=0.8,
        interpolate=True,
        color="lightblue",
    )

    num_days = (df_pred.index[-1] - df_pred.index[0]).days
    if num_days < 14:
        interval = 1
    elif num_days <= 30:
        interval = 2
    else:
        interval = 3

    if num_days < 5:
        ax.xaxis.set_major_locator(mdates.HourLocator(interval=6))
    else:
        ax.xaxis.set_major_locator(mdates.DayLocator(interval=interval))
        ax.xaxis.set_minor_locator(mdates.HourLocator(interval=6))

    if num_days > 5:
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%d"))
    else:
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%d %H:%M"))

    # Adjust the tick parameters for better visibility
    ax.tick_params(axis="both", which="major", labelsize=20, width=2, length=10)

    xticks = ax.get_xticklabels()
    if num_days < 5:
        for i in range(1, len(xticks), 2):
            xticks[i].set_visible(False)

    # Adjust the tick parameters for better visibility

    # Ensure that the grid is enabled and properly configured
    ax.grid(True, which="major", axis="both", linestyle="--", linewidth=0.5)

    # Ensure that the grid is enabled and properly configured
    ax.grid(True, which="major", axis="both", linestyle="--", linewidth=0.5)

    ax.set_xlim(df_pred.index[0], df_pred.index[-1])

    lines = [lobs, lpred, lsym, lconf]
    labels = [l.get_label() for l in lines]

    leg = ax.legend(
        lines,
        labels,
        bbox_to_anchor=(0.5, 1.3),
        loc="upper center",
        ncol=4,
        fancybox=True,
        prop={"size": 20},
    )
    leg.get_frame().set_alpha(None)
    leg.get_frame().set_facecolor((0, 0, 0, 0))
    leg.get_lines()[-1].set_linewidth(12.0)
    leg.get_frame().set_edgecolor("black")
    plt.setp(ax.spines.values(), lw=1, color="black", alpha=1)
    return fig, ax

In [15]:
def plot_storm_local_persistence(
    df_p,
    df_s,
    station,
    color,
    start_date,
    end_date,
    col_name_pred,
    col_name_obs,
    hours,
    title_text="",
    ax=None,
):
    if ax is None:
        fig, ax = plt.subplots(1, 1, figsize=(16, 8))

    sd = pd.to_datetime(start_date)
    ed = pd.to_datetime(end_date)

    df_pred = df_p[sd:ed].copy()
    df_sym = df_s[sd:ed].copy()

    month = df_pred.index[len(df_pred) // 2].month_name()
    year = df_pred.index[len(df_pred) // 2].year

    (lsym,) = ax.plot(
        df_sym[df_pred.index[0] : df_pred.index[-1]].index,
        df_sym[df_pred.index[0] : df_pred.index[-1]]["SYM_H"],
        color="black",
        alpha=0.4,
        label=f"SYM-H",
    )

    ax.set_xlabel(f"{month} of {year}", fontsize=25)
    ax.set_ylabel("Disturbance (nT)", fontsize=25)

    ax.set_title(title_text, fontsize=25)

    (lpred,) = ax.plot(
        df_pred.index,
        df_pred[col_name_pred],
        label=f"Persistence LDi {station} {hours}h",
        color=color,
        alpha=0.6,
        linewidth=2,
    )
    (lobs,) = ax.plot(
        df_pred.index,
        df_pred[col_name_obs],
        label=f"Observed LDi {station}",
        color="blue",
        alpha=0.6,
        linewidth=2,
    )

    plt.setp(ax.spines.values(), lw=2, color="black", alpha=1)

    ax.xaxis_date()

    num_days = (df_pred.index[-1] - df_pred.index[0]).days
    if num_days < 14:
        interval = 1
    elif num_days <= 30:
        interval = 2
    else:
        interval = 3

    if num_days < 5:
        ax.xaxis.set_major_locator(mdates.HourLocator(interval=6))
    else:
        ax.xaxis.set_major_locator(mdates.DayLocator(interval=interval))
        ax.xaxis.set_minor_locator(mdates.HourLocator(interval=6))

    if num_days > 5:
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%d"))
    else:
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%d %H:%M"))

    # Adjust the tick parameters for better visibility
    ax.tick_params(axis="both", which="major", labelsize=20, width=2, length=10)

    xticks = ax.get_xticklabels()
    if num_days < 5:
        for i in range(1, len(xticks), 2):
            xticks[i].set_visible(False)

    # Adjust the tick parameters for better visibility

    # Ensure that the grid is enabled and properly configured
    ax.grid(True, which="major", axis="both", linestyle="--", linewidth=0.5)

    # Ensure that the grid is enabled and properly configured
    ax.grid(True, which="major", axis="both", linestyle="--", linewidth=0.5)

    ax.set_xlim(df_pred.index[0], df_pred.index[-1])

    lines = [lobs, lpred, lsym]
    labels = [l.get_label() for l in lines]

    leg = ax.legend(
        lines,
        labels,
        bbox_to_anchor=(0.5, 1.3),
        loc="upper center",
        ncol=4,
        fancybox=True,
        prop={"size": 20},
    )
    leg.get_frame().set_alpha(None)
    leg.get_frame().set_facecolor((0, 0, 0, 0))
    leg.get_lines()[-1].set_linewidth(12.0)
    leg.get_frame().set_edgecolor("black")
    plt.setp(ax.spines.values(), lw=1, color="black", alpha=1)
    return fig, ax

In [16]:
PLOT_STUFF = True
metrics_test = {}
for station in constants.STATIONS:
    metrics_test[station] = {}

summary_columns = [
    "Station",
    "StormIndex",
    "BFE SYM-H",
    "DTW SYM-H",
    "RMSE SYM-H",
    "R2 SYM-H",
]

for metric_col in [
    "BFE",
    "Better_BFE",
    "DTW",
    "RMSE",
    "Better_RMSE",
    "R2",
    "inside 90%",
]:
    for forecast_step in range(FORECAST_STEPS):
        summary_columns.append(f"{metric_col} {forecast_step + 1}h")

return_columns = [
    "StormIndex",
    "BFE SYM-H",
    "RMSE SYM-H",
]

for metric_col in ["BFE", "RMSE"]:
    for forecast_step in range(FORECAST_STEPS):
        return_columns.append(f"{metric_col} {forecast_step + 1}h")

metrics_return = [
    "Station",
    "Global_BFE_SYM-H",
    "Global_RMSE_SYM-H",
    "Global_R2_SYM-H",
]

for forecast_step in range(FORECAST_STEPS):
    for metric_col in [
        "Global_RMSE_",
        "Global_BFE_",
        "Global_R2_",
        "Global_inside_90%_",
    ]:
        metrics_return.append(f"{metric_col}{forecast_step + 1}h")

for forecast_step in range(FORECAST_STEPS):
    for metric_col in ["RMSE_persistence-", "BFE_persistence-", "R2_persistence-"]:
        metrics_return.append(f"{metric_col}{forecast_step + 1}h")

for metric_col in ["Better BFE", "Better RMSE"]:
    for forecast_step in range(FORECAST_STEPS):
        metrics_return.append(f"{metric_col} {forecast_step + 1}h")


def test_on_station(station, color, model, same_color=True):

    total_columns = COLS_TO_USE.copy()
    solar_wind_columns = COLS_TO_USE.copy()
    ldi_columns = station_columns[station]
    decoder_columns_position = station_columns_decoder[station]
    decoder_columns_ldi_inference = station_first_ldi[station]
    label_names = station_to_labels[station]

    summary_columns = [
        "Station",
        "StormIndex",
        "BFE SYM-H",
        "DTW SYM-H",
        "RMSE SYM-H",
        "R2 SYM_H",
    ]

    print(f"Testing model {model.__class__.__name__}")

    for i in range(FORECAST_STEPS):
        summary_columns.append(f"BFE {i+1}h")
    for i in range(FORECAST_STEPS):
        summary_columns.append(f"DTW {i+1}h")
    for i in range(FORECAST_STEPS):
        summary_columns.append(f"RMSE {i+1}h")
    for i in range(FORECAST_STEPS):
        summary_columns.append(f"R2 {i+1}h")
    for i in range(FORECAST_STEPS):
        summary_columns.append(f"inside 90% {i+1}h")

    for col in label_names:
        metrics_test[station][f"BFE_{col}"] = []
        metrics_test[station][f"DTW_{col}"] = []
        metrics_test[station][f"RMSE_{col}"] = []
        metrics_test[station][f"R2_{col}"] = []
        metrics_test[station][f"inside_90%_{col}"] = []

    original_index = f"LDi_{station}"

    for station_column in station_columns[station]:
        total_columns.append(station_column)
        for shift_suffix, shift_value in zip(SHIFT_NAMES, SHIFT_VALUES):
            total_columns.append(f"{station_column}{shift_suffix}")

    print(f"Evaluating for on station {station}")

    metrics_test[station][f"BFE_SYM-H"] = []
    metrics_test[station][f"DTW_SYM-H"] = []
    metrics_test[station][f"RMSE_SYM-H"] = []
    metrics_test[station][f"R2_SYM-H"] = []

    prediction_dfs_all = []
    prediction_dfs = {}
    global_sym = []

    skipped_indices = []
    global_presistences = []
    valid_indices = []

    for index_strm, ts in enumerate(test_storms):

        start_date = pd.to_datetime(storm_dates.TEST_STORMS[index_strm][0])
        end_date = pd.to_datetime(storm_dates.TEST_STORMS[index_strm][1])
        storm_index = storm_dates.TEST_STORMS[index_strm][2]

        if storm_index in blacklist_storms[station]:
            print(
                f"Skipping blacklisted test storm {storm_index} for {station} from {start_date} - {end_date}"
            )
            continue

        test_storm = ts.copy()

        test_storm[f"LDi_{station}"] = test_storm[f"LDi_{station}"].interpolate(
            limit_area="inside"
        )

        start_date = start_date
        end_date = end_date
        start_index = test_storm[f"LDi_{station}"].first_valid_index()
        end_index = test_storm[f"LDi_{station}"].last_valid_index()
        test_storm = test_storm.loc[start_index:end_index]

        for station_column in station_columns[station]:
            for shift_suffix, shift_value in zip(SHIFT_NAMES, SHIFT_VALUES):
                test_storm[f"{station_column}{shift_suffix}"] = test_storm[
                    f"{station_column}"
                ].shift(shift_value)

        valid = True
        nas = test_storm[f"LDi_{station}"].isna().sum()

        if nas > 0:
            print(
                f'Skipping test storm {storm_index} for station {station} from {start_date} - {end_date} - NAs: {test_storm[f"LDi_{station}"].isna().sum()}'
            )
            skipped_indices.append(storm_index)
            valid = False

        if not valid:
            fig, ax = plt.subplots(figsize=(10, 3))

            ax.plot(
                test_storm[start_date:end_date].index[0],
                test_storm[start_date:end_date][f"LDi_{station}"].iloc[0],
                color="black",
                alpha=0.1,
                label=f"MLT_{station}",
            )
            ax.plot(
                test_storm[start_date:end_date].index,
                test_storm[start_date:end_date][f"LDi_{station}"],
                color=color,
                label=f"LDi_{station}",
                alpha=0.5,
            )
            ax.plot(
                test_storm[start_date:end_date].index,
                test_storm[start_date:end_date][f"SYM_H"],
                color="blue",
                label=f"SYM_H",
                alpha=0.5,
            )
            ax.fill_between(
                test_storm[start_date:end_date].index,
                test_storm[start_date:end_date][f"LDi_{station}"].min(),
                test_storm[start_date:end_date][f"LDi_{station}"].max(),
                where=test_storm[start_date:end_date][f"LDi_{station}"].isna(),
                color="magenta",
                alpha=0.1,
                hatch="X",
            )
            ax.grid(True)
            ax.legend()
            print(
                "Test storm",
                storm_index,
                "from",
                start_date,
                "to",
                end_date,
                "ldi missing values",
                test_storm[start_date:end_date][f"LDi_{station}"].isna().sum(),
            )
            # plt.show();
            plt.close()
            continue

        ln = len(test_storm)
        valid_indices.append(storm_index)
        batch_encoder_solar_wind = torch.zeros(
            (ln - LOOKBACK, LOOKBACK, len(solar_wind_columns)), dtype=torch.float32
        )
        batch_encoder_ldi = torch.zeros(
            (ln - LOOKBACK, LOOKBACK, len(ldi_columns)), dtype=torch.float32
        )
        batch_decoder_first_ldi = torch.zeros((ln - LOOKBACK, 1), dtype=torch.float32)
        batch_decoder_ldi_position = torch.zeros(
            (ln - LOOKBACK, FORECAST_STEPS, NUM_FEATS_POSITION), dtype=torch.float32
        )
        labels = torch.zeros((ln - LOOKBACK, len(label_names)), dtype=torch.float32)
        indices_pred = []
        indices_pred_val = []
        print(
            f"Test storm number {storm_index}, from {start_date} "
            f"until {end_date}, number of batches: {ln}"
        )

        labels = np.zeros((ln - LOOKBACK, FORECAST_STEPS), dtype=np.float32)

        print(
            f"Shapes of the input tensors: {batch_encoder_solar_wind.shape}, {batch_encoder_ldi.shape}, {batch_decoder_first_ldi.shape}, {batch_decoder_ldi_position.shape}, {labels.shape}"
        )

        for i in range(ln - LOOKBACK):
            batch_encoder_solar_wind[i] = torch.tensor(
                test_storm.iloc[i : i + LOOKBACK][solar_wind_columns].values,
                dtype=torch.float32,
            )
            batch_encoder_ldi[i] = torch.tensor(
                test_storm.iloc[i : i + LOOKBACK][ldi_columns].values,
                dtype=torch.float32,
            )
            batch_decoder_first_ldi[i] = torch.tensor(
                test_storm.iloc[i + LOOKBACK - 1][decoder_columns_ldi_inference],
                dtype=torch.float32,
            )
            batch_decoder_ldi_position[i] = torch.tensor(
                test_storm.iloc[i + LOOKBACK - 1][
                    decoder_columns_position
                ].values.reshape(FORECAST_STEPS, NUM_FEATS_POSITION),
                dtype=torch.float32,
            )

            labels[i] = torch.tensor(
                test_storm.iloc[i + LOOKBACK - 1][label_names].values,
                dtype=torch.float32,
            )

            indices_pred.append(test_storm.iloc[i + LOOKBACK - 1].name)
            indices_pred_val.append(test_storm.iloc[i + LOOKBACK - 1][original_index])

        predictions_q05 = []
        predictions_q95 = []
        predictions_mse = []
        batch_decoder_first_ldi = batch_decoder_first_ldi.unsqueeze(-1)

        with torch.no_grad():
            if len(batch_encoder_solar_wind) > BATCH_SIZE:
                for i in range(len(batch_encoder_solar_wind) // BATCH_SIZE + 1):
                    mse, q05, q95 = model.inference(
                        batch_encoder_solar_wind[
                            i * BATCH_SIZE : (i + 1) * BATCH_SIZE
                        ].to(device),
                        batch_encoder_ldi[i * BATCH_SIZE : (i + 1) * BATCH_SIZE].to(
                            device
                        ),
                        batch_decoder_first_ldi[
                            i * BATCH_SIZE : (i + 1) * BATCH_SIZE
                        ].to(device),
                        batch_decoder_ldi_position[
                            i * BATCH_SIZE : (i + 1) * BATCH_SIZE
                        ].to(device),
                    )

                    predictions_q05.append(q05)
                    predictions_q95.append(q95)
                    predictions_mse.append(mse)

                predictions_q05 = torch.cat(predictions_q05)
                predictions_q95 = torch.cat(predictions_q95)
                predictions_mse = torch.cat(predictions_mse)
            else:
                predictions_mse, predictions_q05, predictions_q95 = model.inference(
                    batch_encoder_solar_wind.to(device),
                    batch_encoder_ldi.to(device),
                    batch_decoder_first_ldi.to(device),
                    batch_decoder_ldi_position.to(device),
                )

        predictions_mse_cat = (
            predictions_mse.squeeze().cpu().numpy().reshape(-1, FORECAST_STEPS)
        )
        predictions_q05_cat = (
            predictions_q05.squeeze().cpu().numpy().reshape(-1, FORECAST_STEPS)
        )
        predictions_q95_cat = (
            predictions_q95.squeeze().cpu().numpy().reshape(-1, FORECAST_STEPS)
        )

        indices_pred_val = np.array(indices_pred_val)
        indices_pred_val = labelScaler.inverse_transform(
            indices_pred_val.reshape(-1, 1)
        )

        pred_df = pd.DataFrame(
            data=indices_pred_val, index=indices_pred, columns=[original_index]
        )
        pred_df["storm_index"] = storm_index
        pred_df = pred_df.join(all_omni)

        for i, col in enumerate(label_names):
            pred_df[f"Observed_{col}"] = labelScaler.inverse_transform(
                labels[:, i].reshape(-1, 1)
            )
            pred_df[f"Predicted_{col}"] = labelScaler.inverse_transform(
                predictions_mse_cat[:, i].reshape(-1, 1)
            )
            pred_df[f"Quantile_05_{col}"] = labelScaler.inverse_transform(
                predictions_q05_cat[:, i].reshape(-1, 1)
            )
            pred_df[f"Quantile_95_{col}"] = labelScaler.inverse_transform(
                predictions_q95_cat[:, i].reshape(-1, 1)
            )

            pred_df[f"inside_90%_{col}"] = pred_df.apply(
                inside_quantile,
                axis=1,
                label=f"Observed_{col}",
                q_lower=f"Quantile_05_{col}",
                q_upper=f"Quantile_95_{col}",
            )

        prediction_dfs_all.append(pred_df.copy())
        pred_df.to_csv(
            f"./predictions/{station}/predictions-{station}-storm-{storm_index}.csv",
            index=True,
        )
        title_str = f'Test storm {storm_index} from {start_date.strftime("%Y-%m-%d")} until {end_date.strftime("%Y-%m-%d")}'

        if PLOT_STUFF:
            fig, ax = plt.subplots(figsize=(10, 4))
            ax = pred_df[start_date:end_date][original_index].plot(
                ax=ax,
                grid=True,
                label=f"Observed {original_index}",
                color="blue",
                alpha=0.8,
            )

            ax = pred_df[start_date:end_date]["SYM_H"].plot(
                ax=ax,
                grid=True,
                label=f"SYM-H",
                color="black",
                alpha=0.4,
            )

        comparison_omni = pred_df[start_date:end_date][[original_index, "SYM_H"]].copy()
        global_sym.append(comparison_omni.copy())
        rmse_mse = metrics.rmsem(
            comparison_omni[original_index], comparison_omni["SYM_H"]
        )
        metrics_test[station][f"RMSE_SYM-H"].append(rmse_mse)
        dtw_mse = metrics.compute_dtw(
            comparison_omni[original_index], comparison_omni["SYM_H"]
        )
        metrics_test[station][f"DTW_SYM-H"].append(dtw_mse)
        # storm_rmses_mse.append(rmse_mse)
        r2_mse = metrics.r2m(comparison_omni[original_index], comparison_omni["SYM_H"])
        metrics_test[station][f"R2_SYM-H"].append(r2_mse)
        # storm_r2s_mse.append(r2_mse)
        bfe_mse = metrics.calculate_BFE(
            comparison_omni[original_index], comparison_omni["SYM_H"]
        )
        metrics_test[station][f"BFE_SYM-H"].append(bfe_mse)
        # storm_bfes_mse.append(bfe_mse)

        title_str += f"\nSYM-H Metrics -> RMSE: {rmse_mse:.3f} | R2: {r2_mse:.3f} | BFE: {bfe_mse:.3f}"

        print(
            f"Metrics for SYM_H:\n\tRMSE: {rmse_mse:.3f} | R2: {r2_mse:.3f} | BFE: {bfe_mse:.3f} "
        )

        for i, col in enumerate(label_names):

            timestep_df = pd.DataFrame(
                index=indices_pred,
                columns=[
                    f"Observed_{col}",
                    f"Predicted_{col}",
                    f"Quantile_05_{col}",
                    f"Quantile_95_{col}",
                ],
            )

            timestep_df[f"Observed_{col}"] = pred_df[f"Observed_{col}"]
            timestep_df[f"Predicted_{col}"] = pred_df[f"Predicted_{col}"]
            timestep_df[f"Quantile_05_{col}"] = pred_df[f"Quantile_05_{col}"]
            timestep_df[f"Quantile_95_{col}"] = pred_df[f"Quantile_95_{col}"]
            # print('For the first time step, before shifting')
            # display(timestep_df)
            timestep_df.index = timestep_df.index.shift(
                periods=SHIFT_FORWARD[i], freq="5min"
            )
            # print('For the first time step, after shifting')
            # display(timestep_df)
            timestep_df["storm_index"] = storm_index
            timestep_df = timestep_df.dropna()
            timestep_df = timestep_df[start_date:end_date]
            timestep_df[f"inside_90%_{col}"] = timestep_df.apply(
                inside_quantile,
                axis=1,
                label=f"Observed_{col}",
                q_lower=f"Quantile_05_{col}",
                q_upper=f"Quantile_95_{col}",
            )

            rmse_mse = metrics.rmsem(
                timestep_df[f"Observed_{col}"], timestep_df[f"Predicted_{col}"]
            )
            metrics_test[station][f"RMSE_{col}"].append(rmse_mse)
            dtw_mse = metrics.compute_dtw(
                timestep_df[f"Observed_{col}"], timestep_df[f"Predicted_{col}"]
            )
            metrics_test[station][f"DTW_{col}"].append(dtw_mse)
            # storm_rmses_mse.append(rmse_mse)
            r2_mse = metrics.r2m(
                timestep_df[f"Observed_{col}"], timestep_df[f"Predicted_{col}"]
            )
            metrics_test[station][f"R2_{col}"].append(r2_mse)
            # storm_r2s_mse.append(r2_mse)
            bfe_mse = metrics.calculate_BFE(
                timestep_df[f"Observed_{col}"], timestep_df[f"Predicted_{col}"]
            )
            metrics_test[station][f"BFE_{col}"].append(bfe_mse)
            # storm_bfes_mse.append(bfe_mse)

            pct_inside_90_val = np.mean(timestep_df[f"inside_90%_{col}"])
            metrics_test[station][f"inside_90%_{col}"].append(pct_inside_90_val)
            # pct_inside_90.append(pct_inside_90_val)

            print(
                f"Metrics for {col}:\n\tRMSE: {rmse_mse:.3f} | R2: {r2_mse:.3f} | BFE: {bfe_mse:.3f} | Inside 90%: {pct_inside_90_val:.3f}"
            )

            if PLOT_STUFF:
                ax = timestep_df[start_date:end_date][[f"Predicted_{col}"]].plot(
                    ax=ax,
                    grid=True,
                    label=[f"Predicted_{col}"],
                    color=[metrics.COLORS_MULTIPLE[i]],
                    alpha=0.6,
                )

                ax.fill_between(
                    timestep_df[start_date:end_date].index,
                    timestep_df[start_date:end_date][f"Quantile_05_{col}"],
                    timestep_df[start_date:end_date][f"Quantile_95_{col}"],
                    alpha=0.2,
                    interpolate=True,
                    color=metrics.COLORS_LIGHTER_MULTIPLE[i],
                )
                title_str += f"\n{col} Metrics -> RMSE: {rmse_mse:.3f} | R2: {r2_mse:.3f} | BFE: {bfe_mse:.3f} | Inside 90%: {pct_inside_90_val:.3f}"

            prediction_dfs[f"storm_{storm_index}-{col}"] = timestep_df.copy()

        tper = test_storm[[f"LDi_{station}"]].copy()
        tper[f"LDi_{station}"] = labelScaler.inverse_transform(
            tper[f"LDi_{station}"].values.reshape(-1, 1)
        )
        for shift_val, shift_name in zip(SHIFT_VALUES, SHIFT_NAMES):
            tper[f"persistence_LDi_{station}{shift_name}"] = tper[
                f"LDi_{station}"
            ].shift(shift_val)

        tper = tper.dropna()
        for shift_name in SHIFT_NAMES:
            rmse_persistence = metrics.rmsem(
                tper[f"LDi_{station}"], tper[f"persistence_LDi_{station}{shift_name}"]
            )
            r2_persistence = metrics.r2m(
                tper[f"LDi_{station}"], tper[f"persistence_LDi_{station}{shift_name}"]
            )
            bfe_persistence = metrics.calculate_BFE(
                tper[f"LDi_{station}"], tper[f"persistence_LDi_{station}{shift_name}"]
            )
            print(
                f"Metrics for persistence {shift_name}:\n\tRMSE: {rmse_persistence:.3f} | R2: {r2_persistence:.3f} | BFE: {bfe_persistence:.3f} "
            )
        global_presistences.append(tper.copy())

        if PLOT_STUFF:
            ax.xaxis.set_major_locator(mdates.DayLocator())
            ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m-%d"))
            ax.grid(True, which="both", axis="x", linestyle="--", linewidth=0.5)
            ax.set_title(title_str)
            leg = ax.legend(
                bbox_to_anchor=(0.5, 1.55),
                loc="upper center",
                ncol=3,
                fancybox=True,
                prop={"size": 10},
            )
            leg.get_frame().set_edgecolor("black")
            plt.setp(ax.spines.values(), lw=2, color="black", alpha=1)
            plt.close()

            if storm_index == 104:
                for col_index, col in enumerate(label_names):
                    sd_may = pd.to_datetime("20240510")
                    if station == "ABG":
                        ed_may = pd.to_datetime("20240513")
                    else:
                        ed_may = pd.to_datetime("20240514")
                    plot_title = f'Peak of May 2024 storm at {station} from {sd_may.strftime("%Y-%m-%d")} until {ed_may.strftime("%Y-%m-%d")} {col_index + 1}h forecast\nBFE: {metrics.calculate_BFE(prediction_dfs[f"storm_{storm_index}-{col}"][sd_may:ed_may][f"Observed_{col}"],prediction_dfs[f"storm_{storm_index}-{col}"][sd_may:ed_may][f"Predicted_{col}"]):.3f} | RMSE: {metrics.rmsem(prediction_dfs[f"storm_{storm_index}-{col}"][sd_may:ed_may][f"Observed_{col}"],prediction_dfs[f"storm_{storm_index}-{col}"][sd_may:ed_may][f"Predicted_{col}"]):.3f} | R2: {metrics.r2m(prediction_dfs[f"storm_{storm_index}-{col}"][sd_may:ed_may][f"Observed_{col}"],prediction_dfs[f"storm_{storm_index}-{col}"][sd_may:ed_may][f"Predicted_{col}"]):.3f} | PICP: {np.mean(prediction_dfs[f"storm_{storm_index}-{col}"][sd_may:ed_may][f"inside_90%_{col}"]) * 100:.0f}%'
                    fig, ax = plot_storm_local(
                        prediction_dfs[f"storm_{storm_index}-{col}"],
                        pred_df,
                        station,
                        color,
                        sd_may,
                        ed_may,
                        col,
                        title_text=plot_title,
                    )
                    plt.tight_layout()
                    plt.savefig(
                        f'./figs{"_colors" if same_color else ""}/{station}/forecasts/forecast-ldi-{station}-{col}-test-storm-{storm_index}-may-storm.png',
                        transparent=True,
                        bbox_inches="tight",
                    )
                    plt.close()

                    fig, (ax_q, ax_color_q) = metrics.plot_evaluation_bfe_quantile(
                        prediction_dfs[f"storm_{storm_index}-{col}"][sd_may:ed_may][
                            [f"Observed_{col}", f"Predicted_{col}", f"inside_90%_{col}"]
                        ],
                        title="",
                        full_title=f'Peak of May 2024 storm at {station} from {sd_may.strftime("%Y-%m-%d")} until {ed_may.strftime("%Y-%m-%d")} {col_index + 1}h forecast\nBFE: {metrics.calculate_BFE(prediction_dfs[f"storm_{storm_index}-{col}"][sd_may:ed_may][f"Observed_{col}"],prediction_dfs[f"storm_{storm_index}-{col}"][sd_may:ed_may][f"Predicted_{col}"]):.3f} | PICP: {np.mean(prediction_dfs[f"storm_{storm_index}-{col}"][sd_may:ed_may][f"inside_90%_{col}"])* 100:.0f}%',
                        # full_title=f'Test storm {storm_index} at station {station} | {col_index + 1} hours ahead forecast\nFrom {start_date.strftime("%Y-%m-%d")} to {end_date.strftime("%Y-%m-%d")}',
                        plot_sym_bars=False,
                        xlabel_title=f"LDi {station}",
                    )
                    plt.tight_layout()
                    plt.savefig(
                        f'./figs{"_colors" if same_color else ""}/{station}/bfe/bfe-ldi-{station}-{col}-test-storm-{storm_index}-may-storm.png',
                        transparent=True,
                        bbox_inches="tight",
                    )
                    plt.close()

                # Persistence for the paper
                for col_index, shift_name in enumerate(SHIFT_NAMES):
                    sd_may = pd.to_datetime("20240510")
                    if station == "ABG":
                        ed_may = pd.to_datetime("20240513")
                    else:
                        ed_may = pd.to_datetime("20240514")
                    plot_title = f'Peak of May 2024 storm at {station} from {sd_may.strftime("%Y-%m-%d")} until {ed_may.strftime("%Y-%m-%d")} {col_index + 1}h persistence\nBFE: {metrics.calculate_BFE(tper[sd_may:ed_may][f"LDi_{station}"],tper[sd_may:ed_may][f"persistence_LDi_{station}{shift_name}"]):.3f} | RMSE: {metrics.rmsem(tper[sd_may:ed_may][f"LDi_{station}"],tper[sd_may:ed_may][f"persistence_LDi_{station}{shift_name}"]):.3f} | R2: {metrics.r2m(tper[sd_may:ed_may][f"LDi_{station}"],tper[sd_may:ed_may][f"persistence_LDi_{station}{shift_name}"]):.3f}'
                    fig, ax = plot_storm_local_persistence(
                        tper,
                        all_omni,
                        station,
                        color,
                        sd_may,
                        ed_may,
                        col_name_obs=f"LDi_{station}",
                        col_name_pred=f"persistence_LDi_{station}{shift_name}",
                        hours=col_index + 1,
                        title_text=plot_title,
                    )
                    plt.tight_layout()
                    plt.savefig(
                        f'./figs{"_colors" if same_color else ""}/{station}/forecasts/persistence-ldi-{station}-{col_index + 1}h-test-storm-{storm_index}-may-storm.png',
                        transparent=True,
                        bbox_inches="tight",
                    )
                    plt.close()

            elif storm_index == 108:
                for col_index, col in enumerate(label_names):
                    sd_october = pd.to_datetime("2024-10-10 09:00")
                    ed_october = pd.to_datetime("2024-10-12 09:00")
                    plot_title = f'Peak of October 2024 storm at {station} from {sd_october.strftime("%Y-%m-%d")} until {ed_october.strftime("%Y-%m-%d")} {col_index + 1}h forecast\nBFE: {metrics.calculate_BFE(prediction_dfs[f"storm_{storm_index}-{col}"][sd_october:ed_october][f"Observed_{col}"],prediction_dfs[f"storm_{storm_index}-{col}"][sd_october:ed_october][f"Predicted_{col}"]):.3f} | RMSE: {metrics.rmsem(prediction_dfs[f"storm_{storm_index}-{col}"][sd_october:ed_october][f"Observed_{col}"],prediction_dfs[f"storm_{storm_index}-{col}"][sd_october:ed_october][f"Predicted_{col}"]):.3f} | R2: {metrics.r2m(prediction_dfs[f"storm_{storm_index}-{col}"][sd_october:ed_october][f"Observed_{col}"],prediction_dfs[f"storm_{storm_index}-{col}"][sd_october:ed_october][f"Predicted_{col}"]):.3f} | PICP: {np.mean(prediction_dfs[f"storm_{storm_index}-{col}"][sd_october:ed_october][f"inside_90%_{col}"])* 100:.0f}%'
                    fig, ax = plot_storm_local(
                        prediction_dfs[f"storm_{storm_index}-{col}"],
                        pred_df,
                        station,
                        color,
                        sd_october,
                        ed_october,
                        col,
                        title_text=plot_title,
                    )
                    plt.tight_layout()
                    plt.savefig(
                        f'./figs{"_colors" if same_color else ""}/{station}/forecasts/forecast-ldi-{station}-{col}-test-storm-{storm_index}-october-storm.png',
                        transparent=True,
                        bbox_inches="tight",
                    )
                    plt.close()
                    # plt.show();

                    fig, (ax_q, ax_color_q) = metrics.plot_evaluation_bfe_quantile(
                        prediction_dfs[f"storm_{storm_index}-{col}"][
                            sd_october:ed_october
                        ][[f"Observed_{col}", f"Predicted_{col}", f"inside_90%_{col}"]],
                        title="",
                        full_title=f'Peak of October 2024 storm at {station} from {sd_october.strftime("%Y-%m-%d")} until {ed_october.strftime("%Y-%m-%d")} {col_index + 1}h forecast\nBFE: {metrics.calculate_BFE(prediction_dfs[f"storm_{storm_index}-{col}"][sd_october:ed_october][f"Observed_{col}"],prediction_dfs[f"storm_{storm_index}-{col}"][sd_october:ed_october][f"Predicted_{col}"]):.3f} | PICP: {np.mean(prediction_dfs[f"storm_{storm_index}-{col}"][sd_october:ed_october][f"inside_90%_{col}"])* 100:.0f}%',
                        # full_title=f'Test storm {storm_index} at station {station} | {col_index + 1} hours ahead forecast\nFrom {start_date.strftime("%Y-%m-%d")} to {end_date.strftime("%Y-%m-%d")}',
                        plot_sym_bars=False,
                        xlabel_title=f"LDi {station}",
                    )
                    plt.tight_layout()
                    plt.savefig(
                        f'./figs{"_colors" if same_color else ""}/{station}/bfe/bfe-ldi-{station}-{col}-test-storm-{storm_index}-october-storm.png',
                        transparent=True,
                        bbox_inches="tight",
                    )
                    plt.close()

        if SAVE_FIGS:
            for col_index, col in enumerate(label_names):
                if storm_index == 104:
                    sd_may = pd.to_datetime("20240510")
                    ed_may = pd.to_datetime("20240515")
                    plot_title = f'Test storm {storm_index} at {station} from {start_date.strftime("%Y-%m-%d")} until {end_date.strftime("%Y-%m-%d")} | {col_index + 1}h ahead forecast\nBFE: {metrics_test[station][f"BFE_{col}"][-1]:.3f} | RMSE: {metrics_test[station][f"RMSE_{col}"][-1]:.3f} | R2: {metrics_test[station][f"R2_{col}"][-1]:.3f} | PICP: {metrics_test[station][f"inside_90%_{col}"][-1] * 100:.0f}%'
                    fig, ax = plot_storm_local(
                        prediction_dfs[f"storm_{storm_index}-{col}"],
                        pred_df,
                        station,
                        color,
                        sd_may,
                        ed_may,
                        col,
                        title_text=plot_title,
                    )
                    plt.tight_layout()
                    # plt.savefig(f'./figs/{station}/forecasts/forecast-ldi-{station}-{col}-test-storm-{storm_index}-may-storm.png', transparent = True, bbox_inches='tight')
                    plt.close()

                if storm_index == 108:
                    sd_may = pd.to_datetime("20241009")
                    ed_may = pd.to_datetime("20241013")
                    plot_title = f'Test storm {storm_index} at {station} from {start_date.strftime("%Y-%m-%d")} until {end_date.strftime("%Y-%m-%d")} | {col_index + 1}h ahead forecast\nBFE: {metrics_test[station][f"BFE_{col}"][-1]:.3f} | RMSE: {metrics_test[station][f"RMSE_{col}"][-1]:.3f} | R2: {metrics_test[station][f"R2_{col}"][-1]:.3f} | PICP: {metrics_test[station][f"inside_90%_{col}"][-1] * 100:.0f}%'
                    fig, ax = plot_storm_local(
                        prediction_dfs[f"storm_{storm_index}-{col}"],
                        pred_df,
                        station,
                        color,
                        sd_may,
                        ed_may,
                        col,
                        title_text=plot_title,
                    )
                    plt.tight_layout()
                    # plt.savefig(f'./figs/{station}/forecasts/forecast-ldi-{station}-{col}-test-storm-{storm_index}-may-storm.png', transparent = True, bbox_inches='tight')
                    plt.close()

                plot_title = f'Test storm {storm_index} at {station} from {start_date.strftime("%Y-%m-%d")} until {end_date.strftime("%Y-%m-%d")} | {col_index + 1}h forecast\nBFE: {metrics_test[station][f"BFE_{col}"][-1]:.3f} | RMSE: {metrics_test[station][f"RMSE_{col}"][-1]:.3f} | R2: {metrics_test[station][f"R2_{col}"][-1]:.3f} | PICP: {metrics_test[station][f"inside_90%_{col}"][-1] * 100:.0f}%'
                fig, ax = plot_storm_local(
                    prediction_dfs[f"storm_{storm_index}-{col}"],
                    pred_df,
                    station,
                    color,
                    start_date,
                    end_date,
                    col,
                    title_text=plot_title,
                )
                plt.tight_layout()
                plt.savefig(
                    f'./figs{"_colors" if same_color else ""}/{station}/forecasts/forecast-ldi-{station}-{col}-test-storm-{storm_index}.png',
                    transparent=True,
                    bbox_inches="tight",
                )
                plt.close()
                fig, (ax_q, ax_color_q) = metrics.plot_evaluation_bfe_quantile(
                    prediction_dfs[f"storm_{storm_index}-{col}"][
                        [f"Observed_{col}", f"Predicted_{col}", f"inside_90%_{col}"]
                    ],
                    title="",
                    full_title=f'Test storm {storm_index} at {station} from {start_date.strftime("%Y-%m-%d")} until {end_date.strftime("%Y-%m-%d")} {col_index + 1}h forecast\nBFE: {metrics_test[station][f"BFE_{col}"][-1]:.3f} | PICP: {metrics_test[station][f"inside_90%_{col}"][-1] * 100:.0f}%',
                    # full_title=f'Test storm {storm_index} at station {station} | {col_index + 1} hours ahead forecast\nFrom {start_date.strftime("%Y-%m-%d")} to {end_date.strftime("%Y-%m-%d")}',
                    plot_sym_bars=False,
                    xlabel_title=f"LDi {station}",
                )
                plt.tight_layout()
                plt.savefig(
                    f'./figs{"_colors" if same_color else ""}/{station}/bfe/bfe-ldi-{station}-{col}-test-storm-{storm_index}.png',
                    transparent=True,
                    bbox_inches="tight",
                )
                plt.close()

        print("------------------------------------------------")

    metrics_test[station]["Mean_BFE_SYM-H"] = np.mean(
        metrics_test[station]["BFE_SYM-H"]
    )
    metrics_test[station]["Mean_DTW_SYM-H"] = np.mean(
        metrics_test[station]["DTW_SYM-H"]
    )
    metrics_test[station]["Mean_RMSE_SYM-H"] = np.mean(
        metrics_test[station]["RMSE_SYM-H"]
    )
    metrics_test[station]["Mean_R2_SYM-H"] = np.mean(metrics_test[station]["R2_SYM-H"])

    for col in label_names:
        metrics_test[station][f"Mean_BFE_{col}"] = np.mean(
            metrics_test[station][f"BFE_{col}"]
        )
        metrics_test[station][f"Mean_DTW_{col}"] = np.mean(
            metrics_test[station][f"DTW_{col}"]
        )
        metrics_test[station][f"Mean_RMSE_{col}"] = np.mean(
            metrics_test[station][f"RMSE_{col}"]
        )
        metrics_test[station][f"Mean_R2_{col}"] = np.mean(
            metrics_test[station][f"R2_{col}"]
        )
        metrics_test[station][f"Mean_inside_90%_{col}"] = np.mean(
            metrics_test[station][f"inside_90%_{col}"]
        )

    global_sym = pd.concat(global_sym)
    rmse_global_sym = metrics.rmsem(global_sym[original_index], global_sym["SYM_H"])
    dtw_global_sym = metrics.compute_dtw(
        global_sym[original_index], global_sym["SYM_H"]
    )
    r2_global_sym = metrics.r2m(global_sym[original_index], global_sym["SYM_H"])
    bfe_global_sym = metrics.calculate_BFE(
        global_sym[original_index], global_sym["SYM_H"]
    )

    metrics_test[station][f"Global_BFE_SYM-H"] = bfe_global_sym
    metrics_test[station][f"Global_RMSE_SYM-H"] = rmse_global_sym
    metrics_test[station][f"Global_R2_SYM-H"] = r2_global_sym
    metrics_test[station][f"Global_DTW_SYM-H"] = dtw_global_sym

    global_dfs = []
    for col in label_names:
        global_df = None
        for start_date, end_date, storm_index in storm_dates.TEST_STORMS:
            if global_df is None:
                if f"storm_{storm_index}-{col}" in prediction_dfs:
                    global_df = prediction_dfs[f"storm_{storm_index}-{col}"].copy()
            else:
                if f"storm_{storm_index}-{col}" in prediction_dfs:
                    global_df = pd.concat(
                        [global_df, prediction_dfs[f"storm_{storm_index}-{col}"]]
                    )
        rmse_global = metrics.rmsem(
            global_df[f"Observed_{col}"], global_df[f"Predicted_{col}"]
        )
        dtw_global = metrics.compute_dtw(
            global_df[f"Observed_{col}"], global_df[f"Predicted_{col}"]
        )
        r2_global = metrics.r2m(
            global_df[f"Observed_{col}"], global_df[f"Predicted_{col}"]
        )
        bfe_global = metrics.calculate_BFE(
            global_df[f"Observed_{col}"], global_df[f"Predicted_{col}"]
        )
        pct_inside_90_global = np.mean(global_df[f"inside_90%_{col}"])

        metrics_test[station][f"Global_BFE_{col}"] = bfe_global
        metrics_test[station][f"Global_DTW_{col}"] = dtw_global
        metrics_test[station][f"Global_RMSE_{col}"] = rmse_global
        metrics_test[station][f"Global_R2_{col}"] = r2_global
        metrics_test[station][f"Global_inside_90%_{col}"] = pct_inside_90_global
        global_dfs.append(global_df.copy())

    summary_df = pd.DataFrame(columns=summary_columns)

    names_metrics_dict = []
    mean_names_metrics_dict = []
    global_names_metrics_dict = []

    names_metrics_dict.append("BFE_SYM-H")
    mean_names_metrics_dict.append("Mean_BFE_SYM-H")
    global_names_metrics_dict.append("Global_BFE_SYM-H")
    names_metrics_dict.append("DTW_SYM-H")
    mean_names_metrics_dict.append("Mean_DTW_SYM-H")
    global_names_metrics_dict.append("Global_DTW_SYM-H")
    names_metrics_dict.append("RMSE_SYM-H")
    mean_names_metrics_dict.append("Mean_RMSE_SYM-H")
    global_names_metrics_dict.append("Global_RMSE_SYM-H")
    names_metrics_dict.append("R2_SYM-H")
    mean_names_metrics_dict.append("Mean_R2_SYM-H")
    global_names_metrics_dict.append("Global_R2_SYM-H")

    for col in label_names:
        names_metrics_dict.append(f"BFE_{col}")
        mean_names_metrics_dict.append(f"Mean_BFE_{col}")
        global_names_metrics_dict.append(f"Global_BFE_{col}")

    for col in label_names:
        names_metrics_dict.append(f"DTW_{col}")
        mean_names_metrics_dict.append(f"Mean_DTW_{col}")
        global_names_metrics_dict.append(f"Global_DTW_{col}")

    for col in label_names:
        names_metrics_dict.append(f"RMSE_{col}")
        mean_names_metrics_dict.append(f"Mean_RMSE_{col}")
        global_names_metrics_dict.append(f"Global_RMSE_{col}")

    for col in label_names:
        names_metrics_dict.append(f"R2_{col}")
        mean_names_metrics_dict.append(f"Mean_R2_{col}")
        global_names_metrics_dict.append(f"Global_R2_{col}")

    for col in label_names:
        names_metrics_dict.append(f"inside_90%_{col}")
        mean_names_metrics_dict.append(f"Mean_inside_90%_{col}")
        global_names_metrics_dict.append(f"Global_inside_90%_{col}")

    mets_to_return = ["Global_BFE_SYM-H", "Global_RMSE_SYM-H", "Global_R2_SYM-H"]
    for col in label_names:
        mets_to_return.append(f"Global_RMSE_{col}")
        mets_to_return.append(f"Global_BFE_{col}")
        mets_to_return.append(f"Global_R2_{col}")
        mets_to_return.append(f"Global_inside_90%_{col}")

    for col in label_names:
        mets_to_return.append(f"RMSE_persistence_{col}")
        mets_to_return.append(f"BFE_persistence_{col}")
        mets_to_return.append(f"R2_persistence_{col}")

    storm_i = 0
    for index_storm in valid_indices:
        row_to_add = [station, index_storm]
        for name in names_metrics_dict:
            row_to_add.append(metrics_test[station][name][storm_i])
        summary_df.loc[len(summary_df)] = row_to_add
        storm_i += 1

    means_to_add = [station, "Mean"]
    for name in mean_names_metrics_dict:
        means_to_add.append(metrics_test[station][name])
    summary_df.loc[len(summary_df)] = means_to_add

    globals_to_add = [station, "Global"]
    for name in global_names_metrics_dict:
        globals_to_add.append(metrics_test[station][name])
    summary_df.loc[len(summary_df)] = globals_to_add

    print("Metrics for the MSE output")
    display(summary_df.round(3))

    print("Mean and global MSE output")
    display(summary_df.iloc[-2:].round(3))

    print(summary_df.set_index("StormIndex").iloc[-2:, :5].round(3).to_string())

    tpers = pd.concat(global_presistences)
    str_return_persistence = ""

    for col in label_names:
        rmse_persistence = metrics.rmsem(
            tpers[f"LDi_{station}"], tpers[f"persistence_{col}"]
        )
        metrics_test[station][f"RMSE_persistence_{col}"] = rmse_persistence
        r2_persistence = metrics.r2m(
            tpers[f"LDi_{station}"], tpers[f"persistence_{col}"]
        )
        metrics_test[station][f"R2_persistence_{col}"] = r2_persistence
        bfe_persistence = metrics.calculate_BFE(
            tpers[f"LDi_{station}"], tpers[f"persistence_{col}"]
        )
        metrics_test[station][f"BFE_persistence_{col}"] = bfe_persistence
        print(
            f"Metrics for persistence {shift_name}:\n\tRMSE: {rmse_persistence:.3f} | R2: {r2_persistence:.3f} | BFE: {bfe_persistence:.3f} "
        )
        str_return_persistence += f"Metrics for persistence {col}:\n\tRMSE: {rmse_persistence:.3f} | BFE: {bfe_persistence:.3f}\n"

    metrics.plot_evaluation_bfe(
        global_sym[[original_index, "SYM_H"]],
        title=f"Global BFE LDi {station} vs SYM-H nowcast",
        xlabel_title=f"LDi {station}",
    )
    if SAVE_FIGS:
        plt.tight_layout()
        plt.savefig(
            f'./figs{"_colors" if same_color else ""}/{station}/bfe/sym-h-ldi-comparison-ldi-{station}-{col}.png',
            transparent=True,
            bbox_inches="tight",
        )
    # plt.show();
    plt.close()

    for i, col in enumerate(label_names):
        fig, ax = metrics.plot_evaluation_bfe_quantile(
            global_dfs[i][[f"Observed_{col}", f"Predicted_{col}", f"inside_90%_{col}"]],
            title=f"",
            # full_title=f'Global BFE LDi {station} {i + 1} hours',
            full_title=f'Global BFE for LDi {station} {i + 1} hour{"s" if i + 1 > 1 else ""} ahead forecast\nBFE: {metrics_test[station][f"Global_BFE_{col}"]:.3f} | PICP: {metrics_test[station][f"Global_inside_90%_{col}"] * 100:.3f}%',
            xlabel_title=f"LDi {station} (nT)",
        )
        if SAVE_FIGS:
            plt.tight_layout()
            plt.savefig(
                f'./figs{"_colors" if same_color else ""}/{station}/bfe/bfe-ldi-{station}-{col}.png',
                transparent=True,
                bbox_inches="tight",
            )
            plt.close()
        # plt.show();
        plt.close()
        metrics.plot_comparison_bfe(
            global_dfs[i][[f"Observed_{col}", f"Predicted_{col}"]],
            global_sym[[original_index, "SYM_H"]],
            title=f"LDi forecast {i + 1}h",
            title_to_compare=f"SYM-H nowcast",
            xlabel_title=f"LDi {station}",
            station=station,
            is_global=True,
        )
        if SAVE_FIGS:
            plt.tight_layout()
            plt.savefig(
                f'./figs{"_colors" if same_color else ""}/{station}/bfe/bfe-comparison-sym-ldi-{station}-{col}.png',
                transparent=True,
                bbox_inches="tight",
            )
            plt.close()
        # plt.show();
        plt.close()

    display(summary_df)
    str_return = f"Information for station {station}\n{summary_df[return_columns].iloc[-2:]}\n{str_return_persistence}\n"

    extra_mets = []
    for i in range(FORECAST_STEPS):
        extra_mets.append(
            f"{len(summary_df[summary_df[f'BFE {i+1}h'] < summary_df['BFE SYM-H']])}/{len(summary_df)}"
        )
    for i in range(FORECAST_STEPS):
        extra_mets.append(
            f"{len(summary_df[summary_df[f'RMSE {i+1}h'] < summary_df['RMSE SYM-H']])}/{len(summary_df)}"
        )

    return (
        str_return,
        [station]
        + [metrics_test[station][metric_name] for metric_name in mets_to_return]
        + extra_mets,
        summary_df,
    )

In [ ]:
summary_df = pd.DataFrame(columns=metrics_return)

station = constants.STATIONS[0]

color = "magenta"
sum_dfs_stations = []

str_summary = ""

str_return, metrics_station, sum_df_station = test_on_station(
    station, color, model, same_color=True
)
str_summary += str_return
sum_dfs_stations.append(sum_df_station)
summary_df.loc[len(summary_df)] = metrics_station

color = constants.COLOR_STATIONS[station]
_, _, _ = test_on_station(station, color, model, same_color=False)

Testing model RELDi
Evaluating for on station ABG
Test storm number 89, from 2017-09-06 00:00:00 until 2017-09-15 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 26.694 | R2: 0.571 | BFE: 51.318
Metrics for LDi_ABG-1h:
	RMSE: 11.743 | R2: 0.917 | BFE: 20.252 | Inside 90%: 0.891
Metrics for LDi_ABG-2h:
	RMSE: 19.057 | R2: 0.782 | BFE: 33.472 | Inside 90%: 0.760
Metrics for persistence -1h:
	RMSE: 15.108 | R2: 0.840 | BFE: 21.632
Metrics for persistence -2h:
	RMSE: 23.173 | R2: 0.625 | BFE: 30.768
------------------------------------------------
Test storm number 90, from 2017-09-26 00:00:00 until 2017-10-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 15.757 | R2: 0.450 | BFE: 22.046
Metrics for LDi_ABG-1h:
	RMSE: 8.172 | R2: 0.852 | BFE: 10.234 | Inside 90%: 0.919
Metrics for LDi_ABG-2h:
	RMSE: 11.436 | R2: 0.710 | BFE: 15.431 | Inside 90%: 0.862
Metrics for persistence -1h:
	RMSE: 8.881 | R2: 0.807 | BFE: 15.878
Metrics for persistence -2h:
	RMSE: 12.040 | R2: 0.646 | BFE: 22.822
------------------------------------------------
Test storm number 91, from 2018-08-24 00:00:00 until 2018-09-01 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 18.686 | R2: 0.799 | BFE: 29.525
Metrics for LDi_ABG-1h:
	RMSE: 8.581 | R2: 0.958 | BFE: 11.295 | Inside 90%: 0.951
Metrics for LDi_ABG-2h:
	RMSE: 13.624 | R2: 0.893 | BFE: 20.230 | Inside 90%: 0.868
Metrics for persistence -1h:
	RMSE: 10.051 | R2: 0.932 | BFE: 17.057
Metrics for persistence -2h:
	RMSE: 15.970 | R2: 0.829 | BFE: 27.444
------------------------------------------------
Test storm number 92, from 2021-11-02 00:00:00 until 2021-11-10 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 14.601 | R2: 0.772 | BFE: 31.660
Metrics for LDi_ABG-1h:
	RMSE: 10.766 | R2: 0.876 | BFE: 13.660 | Inside 90%: 0.816
Metrics for LDi_ABG-2h:
	RMSE: 16.971 | R2: 0.692 | BFE: 26.248 | Inside 90%: 0.669
Metrics for persistence -1h:
	RMSE: 11.100 | R2: 0.847 | BFE: 21.576
Metrics for persistence -2h:
	RMSE: 16.088 | R2: 0.678 | BFE: 28.254
------------------------------------------------
Skipping blacklisted test storm 93 for ABG from 2022-01-12 00:00:00 - 2022-01-20 00:00:00
Test storm number 94, from 2022-11-05 00:00:00 until 2022-11-13 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 16.151 | R2: 0.717 | BFE: 29.084
Metrics for LDi_ABG-1h:
	RMSE: 7.852 | R2: 0.933 | BFE: 9.298 | Inside 90%: 0.931
Metrics for LDi_ABG-2h:
	RMSE: 14.647 | R2: 0.767 | BFE: 19.287 | Inside 90%: 0.781
Metrics for persistence -1h:
	RMSE: 9.236 | R2: 0.900 | BFE: 15.517
Metrics for persistence -2h:
	RMSE: 15.857 | R2: 0.706 | BFE: 28.216
------------------------------------------------
Test storm number 95, from 2023-02-25 00:00:00 until 2023-03-06 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 19.457 | R2: 0.751 | BFE: 37.289
Metrics for LDi_ABG-1h:
	RMSE: 12.428 | R2: 0.899 | BFE: 18.204 | Inside 90%: 0.890
Metrics for LDi_ABG-2h:
	RMSE: 18.433 | R2: 0.777 | BFE: 22.769 | Inside 90%: 0.736
Metrics for persistence -1h:
	RMSE: 13.045 | R2: 0.870 | BFE: 24.384
Metrics for persistence -2h:
	RMSE: 17.675 | R2: 0.761 | BFE: 33.272
------------------------------------------------
Test storm number 96, from 2023-03-21 00:00:00 until 2023-03-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 18.377 | R2: 0.782 | BFE: 24.434
Metrics for LDi_ABG-1h:
	RMSE: 11.087 | R2: 0.920 | BFE: 13.289 | Inside 90%: 0.853
Metrics for LDi_ABG-2h:
	RMSE: 15.496 | R2: 0.845 | BFE: 19.835 | Inside 90%: 0.765
Metrics for persistence -1h:
	RMSE: 11.949 | R2: 0.896 | BFE: 15.424
Metrics for persistence -2h:
	RMSE: 17.668 | R2: 0.774 | BFE: 22.476
------------------------------------------------
Test storm number 97, from 2023-04-21 00:00:00 until 2023-04-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 20.975 | R2: 0.785 | BFE: 17.032
Metrics for LDi_ABG-1h:
	RMSE: 11.008 | R2: 0.941 | BFE: 14.359 | Inside 90%: 0.897
Metrics for LDi_ABG-2h:
	RMSE: 16.248 | R2: 0.871 | BFE: 20.669 | Inside 90%: 0.790
Metrics for persistence -1h:
	RMSE: 11.299 | R2: 0.931 | BFE: 15.969
Metrics for persistence -2h:
	RMSE: 15.800 | R2: 0.865 | BFE: 24.260
------------------------------------------------
Test storm number 98, from 2023-08-03 00:00:00 until 2023-08-11 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 8.807 | R2: 0.806 | BFE: 7.317
Metrics for LDi_ABG-1h:
	RMSE: 6.588 | R2: 0.892 | BFE: 8.692 | Inside 90%: 0.966
Metrics for LDi_ABG-2h:
	RMSE: 10.297 | R2: 0.735 | BFE: 13.429 | Inside 90%: 0.893
Metrics for persistence -1h:
	RMSE: 7.519 | R2: 0.877 | BFE: 9.253
Metrics for persistence -2h:
	RMSE: 11.406 | R2: 0.716 | BFE: 16.195
------------------------------------------------
Test storm number 99, from 2023-11-03 00:00:00 until 2023-11-12 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 15.927 | R2: 0.882 | BFE: 37.337
Metrics for LDi_ABG-1h:
	RMSE: 14.285 | R2: 0.905 | BFE: 30.148 | Inside 90%: 0.948
Metrics for LDi_ABG-2h:
	RMSE: 16.602 | R2: 0.872 | BFE: 26.389 | Inside 90%: 0.842
Metrics for persistence -1h:
	RMSE: 16.012 | R2: 0.864 | BFE: 33.748
Metrics for persistence -2h:
	RMSE: 22.130 | R2: 0.740 | BFE: 31.483
------------------------------------------------
Test storm number 100, from 2023-11-23 00:00:00 until 2023-12-08 00:00:00, number of batches: 4896
Shapes of the input tensors: torch.Size([4800, 96, 6]), torch.Size([4800, 96, 5]), torch.Size([4800, 1]), torch.Size([4800, 2, 4]), (4800, 2)
Metrics for SYM_H:
	RMSE: 14.864 | R2: 0.742 | BFE: 28.931
Metrics for LDi_ABG-1h:
	RMSE: 9.020 | R2: 0.905 | BFE: 13.113 | Inside 90%: 0.937
Metrics for LDi_ABG-2h:
	RMSE: 16.567 | R2: 0.680 | BFE: 36.112 | Inside 90%: 0.826
Metrics for persistence -1h:
	RMSE: 10.929 | R2: 0.855 | BFE: 16.965
Metrics for persistence -2h:
	RMSE: 15.907 | R2: 0.692 | BFE: 24.601
------------------------------------------------
Test storm number 101, from 2024-03-01 00:00:00 until 2024-03-09 00:00:00, number of batches: 2881
Shapes of the input tensors: torch.Size([2785, 96, 6]), torch.Size([2785, 96, 5]), torch.Size([2785, 1]), torch.Size([2785, 2, 4]), (2785, 2)
Metrics for SYM_H:
	RMSE: 15.516 | R2: 0.745 | BFE: 32.441
Metrics for LDi_ABG-1h:
	RMSE: 7.531 | R2: 0.940 | BFE: 12.013 | Inside 90%: 0.961
Metrics for LDi_ABG-2h:
	RMSE: 12.853 | R2: 0.825 | BFE: 14.747 | Inside 90%: 0.870
Metrics for persistence -1h:
	RMSE: 10.096 | R2: 0.878 | BFE: 18.606
Metrics for persistence -2h:
	RMSE: 16.644 | R2: 0.667 | BFE: 31.380
------------------------------------------------
Test storm number 102, from 2024-03-22 00:00:00 until 2024-03-30 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 22.499 | R2: 0.480 | BFE: 31.685
Metrics for LDi_ABG-1h:
	RMSE: 10.287 | R2: 0.891 | BFE: 17.489 | Inside 90%: 0.870
Metrics for LDi_ABG-2h:
	RMSE: 15.487 | R2: 0.754 | BFE: 27.742 | Inside 90%: 0.719
Metrics for persistence -1h:
	RMSE: 13.801 | R2: 0.822 | BFE: 14.984
Metrics for persistence -2h:
	RMSE: 19.442 | R2: 0.646 | BFE: 19.125
------------------------------------------------
Skipping blacklisted test storm 103 for ABG from 2024-04-17 00:00:00 - 2024-04-25 00:00:00
Test storm number 104, from 2024-04-30 00:00:00 until 2024-05-24 00:00:00, number of batches: 7488
Shapes of the input tensors: torch.Size([7392, 96, 6]), torch.Size([7392, 96, 5]), torch.Size([7392, 1]), torch.Size([7392, 2, 4]), (7392, 2)
Metrics for SYM_H:
	RMSE: 19.596 | R2: 0.927 | BFE: 35.040
Metrics for LDi_ABG-1h:
	RMSE: 12.637 | R2: 0.969 | BFE: 27.746 | Inside 90%: 0.932
Metrics for LDi_ABG-2h:
	RMSE: 20.966 | R2: 0.916 | BFE: 45.431 | Inside 90%: 0.819
Metrics for persistence -1h:
	RMSE: 18.106 | R2: 0.933 | BFE: 47.260
Metrics for persistence -2h:
	RMSE: 25.764 | R2: 0.865 | BFE: 66.761
------------------------------------------------
Test storm number 105, from 2024-06-26 00:00:00 until 2024-07-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 18.476 | R2: 0.660 | BFE: 27.721
Metrics for LDi_ABG-1h:
	RMSE: 7.217 | R2: 0.948 | BFE: 9.325 | Inside 90%: 0.964
Metrics for LDi_ABG-2h:
	RMSE: 11.817 | R2: 0.861 | BFE: 17.827 | Inside 90%: 0.878
Metrics for persistence -1h:
	RMSE: 9.279 | R2: 0.904 | BFE: 18.609
Metrics for persistence -2h:
	RMSE: 14.318 | R2: 0.771 | BFE: 23.598
------------------------------------------------
Test storm number 106, from 2024-08-02 00:00:00 until 2024-08-19 00:00:00, number of batches: 5472
Shapes of the input tensors: torch.Size([5376, 96, 6]), torch.Size([5376, 96, 5]), torch.Size([5376, 1]), torch.Size([5376, 2, 4]), (5376, 2)
Metrics for SYM_H:
	RMSE: 28.192 | R2: 0.663 | BFE: 39.481
Metrics for LDi_ABG-1h:
	RMSE: 9.450 | R2: 0.962 | BFE: 11.562 | Inside 90%: 0.930
Metrics for LDi_ABG-2h:
	RMSE: 15.320 | R2: 0.900 | BFE: 17.114 | Inside 90%: 0.805
Metrics for persistence -1h:
	RMSE: 11.396 | R2: 0.941 | BFE: 16.139
Metrics for persistence -2h:
	RMSE: 16.693 | R2: 0.873 | BFE: 23.529
------------------------------------------------
Test storm number 107, from 2024-09-10 00:00:00 until 2024-09-23 00:00:00, number of batches: 4320
Shapes of the input tensors: torch.Size([4224, 96, 6]), torch.Size([4224, 96, 5]), torch.Size([4224, 1]), torch.Size([4224, 2, 4]), (4224, 2)
Metrics for SYM_H:
	RMSE: 16.456 | R2: 0.850 | BFE: 23.703
Metrics for LDi_ABG-1h:
	RMSE: 11.494 | R2: 0.927 | BFE: 15.044 | Inside 90%: 0.894
Metrics for LDi_ABG-2h:
	RMSE: 17.629 | R2: 0.828 | BFE: 24.888 | Inside 90%: 0.746
Metrics for persistence -1h:
	RMSE: 12.351 | R2: 0.913 | BFE: 14.373
Metrics for persistence -2h:
	RMSE: 18.406 | R2: 0.807 | BFE: 26.342
------------------------------------------------
Test storm number 108, from 2024-10-05 00:00:00 until 2024-10-17 00:00:00, number of batches: 4032
Shapes of the input tensors: torch.Size([3936, 96, 6]), torch.Size([3936, 96, 5]), torch.Size([3936, 1]), torch.Size([3936, 2, 4]), (3936, 2)
Metrics for SYM_H:
	RMSE: 23.421 | R2: 0.899 | BFE: 31.617
Metrics for LDi_ABG-1h:
	RMSE: 18.188 | R2: 0.939 | BFE: 27.678 | Inside 90%: 0.839
Metrics for LDi_ABG-2h:
	RMSE: 26.420 | R2: 0.871 | BFE: 39.186 | Inside 90%: 0.716
Metrics for persistence -1h:
	RMSE: 18.885 | R2: 0.929 | BFE: 28.137
Metrics for persistence -2h:
	RMSE: 26.818 | R2: 0.857 | BFE: 37.216
------------------------------------------------
Skipping blacklisted test storm 109 for ABG from 2024-11-07 00:00:00 - 2024-11-15 00:00:00
Metrics for the MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,ABG,89,51.318,19.426,26.694,0.571,20.252001,33.472000,7.563,12.157,11.743,19.057,0.917,0.782,0.891,0.760
1,ABG,90,22.046,12.131,15.757,0.450,10.234000,15.431000,5.656,8.121,8.172,11.436,0.852,0.710,0.919,0.862
2,ABG,91,29.525,12.406,18.686,0.799,11.295000,20.230000,5.444,8.680,8.581,13.624,0.958,0.893,0.951,0.868
3,ABG,92,31.660,9.375,14.601,0.772,13.660000,26.247999,7.476,11.575,10.766,16.971,0.876,0.692,0.816,0.669
4,ABG,94,29.084,12.950,16.151,0.717,9.298000,19.287001,5.315,9.934,7.852,14.647,0.933,0.767,0.931,0.781
5,ABG,95,37.289,14.424,19.457,0.751,18.204000,22.768999,7.989,12.140,12.428,18.433,0.899,0.777,0.890,0.736
6,ABG,96,24.434,11.188,18.377,0.782,13.289000,19.834999,7.138,10.686,11.087,15.496,0.920,0.845,0.853,0.765
7,ABG,97,17.032,18.278,20.975,0.785,14.359000,20.669001,7.339,11.392,11.008,16.248,0.941,0.871,0.897,0.790
8,ABG,98,7.317,6.739,8.807,0.806,8.692000,13.429000,4.820,7.694,6.588,10.297,0.892,0.735,0.966,0.893
9,ABG,99,37.337,9.740,15.927,0.882,30.148001,26.389000,8.339,11.464,14.285,16.602,0.905,0.872,0.948,0.842
10,ABG,100,28.931,9.990,14.864,0.742,13.113000,36.112000,5.761,9.608,9.020,16.567,0.905,0.680,0.937,0.826
11,ABG,101,32.441,9.620,15.516,0.745,12.013000,14.747000,4.904,7.718,7.531,12.853,0.940,0.825,0.961,0.870
12,ABG,102,31.685,20.045,22.499,0.480,17.489000,27.742001,6.839,10.203,10.287,15.487,0.891,0.754,0.870,0.719
13,ABG,104,35.040,12.751,19.596,0.927,27.746000,45.431000,7.363,12.063,12.637,20.966,0.969,0.916,0.932,0.819
14,ABG,105,27.721,15.438,18.476,0.660,9.325000,17.827000,5.169,8.481,7.217,11.817,0.948,0.861,0.964,0.878
15,ABG,106,39.481,24.073,28.192,0.663,11.562000,17.114000,6.127,9.967,9.450,15.320,0.962,0.900,0.930,0.805
16,ABG,107,23.703,11.869,16.456,0.850,15.044000,24.888000,7.553,11.883,11.494,17.629,0.927,0.828,0.894,0.746
17,ABG,108,31.617,17.465,23.421,0.899,27.677999,39.186001,10.452,15.734,18.188,26.420,0.939,0.871,0.839,0.716
18,ABG,Mean,29.870,13.773,18.581,0.738,15.744000,24.489000,6.736,10.528,10.463,16.104,0.921,0.810,0.910,0.797
19,ABG,Global,44.530,14.085,19.621,0.830,25.634001,40.916000,6.848,10.769,11.129,17.194,0.945,0.870,0.912,0.797

Mean and global MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
18,ABG,Mean,29.87,13.773,18.581,0.738,15.744000,24.489,6.736,10.528,10.463,16.104,0.921,0.81,0.910,0.797
19,ABG,Global,44.53,14.085,19.621,0.830,25.634001,40.916,6.848,10.769,11.129,17.194,0.945,0.87,0.912,0.797

           Station  BFE SYM-H  DTW SYM-H  RMSE SYM-H  R2 SYM_H
StormIndex
Mean           ABG      29.87     13.773      18.581     0.738
Global         ABG      44.53     14.085      19.621     0.830
Metrics for persistence -2h:
	RMSE: 13.092 | R2: 0.916 | BFE: 36.519
Metrics for persistence -2h:
	RMSE: 19.043 | R2: 0.822 | BFE: 52.786
Diff BFE (SYM-H nowcast - LDi forecast 1h):
Total: 18.896
Diff BFE (SYM-H nowcast - LDi forecast 2h):
Total: 3.614

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,ABG,89,51.317759,19.426228,26.693588,0.571418,20.251646,33.472221,7.562903,12.156519,11.742769,19.056625,0.917061,0.781570,0.890860,0.760123
1,ABG,90,22.046410,12.131271,15.756771,0.449524,10.234109,15.431261,5.656320,8.120926,8.171618,11.435536,0.851946,0.710054,0.919306,0.862039
2,ABG,91,29.525274,12.406395,18.686430,0.798634,11.295156,20.230370,5.444482,8.679736,8.581061,13.624454,0.957537,0.892954,0.950976,0.868113
3,ABG,92,31.660090,9.374594,14.600516,0.771799,13.660373,26.247932,7.476053,11.575391,10.766204,16.970741,0.875919,0.691694,0.815618,0.669414
4,ABG,94,29.083728,12.950148,16.150822,0.716789,9.298187,19.286816,5.314987,9.933503,7.851702,14.647009,0.933066,0.767074,0.931020,0.780911
5,ABG,95,37.289321,14.423606,19.456602,0.751398,18.203932,22.769079,7.989240,12.140351,12.428012,18.433069,0.898568,0.776866,0.890089,0.735827
6,ABG,96,24.433559,11.187536,18.376741,0.781544,13.288501,19.834919,7.137598,10.685829,11.086800,15.495961,0.920487,0.844667,0.853452,0.764751
7,ABG,97,17.032236,18.277609,20.974766,0.785222,14.358891,20.668797,7.339070,11.392482,11.008047,16.248240,0.940841,0.871113,0.897030,0.789819
8,ABG,98,7.316731,6.738902,8.807268,0.806347,8.692373,13.428818,4.819615,7.693836,6.587850,10.296861,0.891650,0.735301,0.966161,0.892842
9,ABG,99,37.336920,9.740413,15.927495,0.881778,30.147572,26.388510,8.339153,11.463689,14.284958,16.601902,0.904904,0.871555,0.947551,0.841882
10,ABG,100,28.931281,9.990051,14.864123,0.742198,13.112892,36.112190,5.761431,9.607727,9.020435,16.567101,0.905057,0.679742,0.936820,0.825966
11,ABG,101,32.440945,9.619822,15.516281,0.745185,12.012779,14.746623,4.903722,7.717627,7.530991,12.852617,0.939972,0.825163,0.960954,0.870282
12,ABG,102,31.685187,20.044859,22.498795,0.479805,17.488724,27.742283,6.839328,10.203048,10.287399,15.487444,0.891243,0.753506,0.869848,0.718872
13,ABG,104,35.040489,12.751295,19.596272,0.926575,27.745958,45.431416,7.362846,12.062735,12.637288,20.965929,0.969464,0.915952,0.931578,0.818892
14,ABG,105,27.720771,15.438069,18.476276,0.660215,9.325393,17.826916,5.169438,8.480823,7.216821,11.817385,0.948160,0.860999,0.964425,0.878091
15,ABG,106,39.480632,24.073196,28.191772,0.662543,11.561953,17.113657,6.126679,9.966680,9.449982,15.320019,0.962083,0.900347,0.930161,0.804983
16,ABG,107,23.702795,11.869132,16.455557,0.849729,15.043929,24.888405,7.552808,11.883060,11.493978,17.629204,0.926685,0.827529,0.894259,0.745527
17,ABG,108,31.617061,17.465138,23.421146,0.898575,27.677557,39.186028,10.451834,15.733792,18.187851,26.419947,0.938837,0.870939,0.838588,0.715649
18,ABG,Mean,29.870066,13.772681,18.580623,0.737738,15.744441,24.489235,6.735973,10.527653,10.462987,16.103891,0.920749,0.809835,0.910483,0.796888
19,ABG,Global,44.530046,14.084832,19.620636,0.830243,25.633680,40.916145,6.848358,10.769022,11.128581,17.194424,0.945389,0.869631,0.911835,0.796649

Testing model RELDi
Evaluating for on station ABG
Test storm number 89, from 2017-09-06 00:00:00 until 2017-09-15 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 26.694 | R2: 0.571 | BFE: 51.318
Metrics for LDi_ABG-1h:
	RMSE: 11.743 | R2: 0.917 | BFE: 20.252 | Inside 90%: 0.891
Metrics for LDi_ABG-2h:
	RMSE: 19.057 | R2: 0.782 | BFE: 33.472 | Inside 90%: 0.760
Metrics for persistence -1h:
	RMSE: 15.108 | R2: 0.840 | BFE: 21.632
Metrics for persistence -2h:
	RMSE: 23.173 | R2: 0.625 | BFE: 30.768
------------------------------------------------
Test storm number 90, from 2017-09-26 00:00:00 until 2017-10-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 15.757 | R2: 0.450 | BFE: 22.046
Metrics for LDi_ABG-1h:
	RMSE: 8.172 | R2: 0.852 | BFE: 10.234 | Inside 90%: 0.919
Metrics for LDi_ABG-2h:
	RMSE: 11.436 | R2: 0.710 | BFE: 15.431 | Inside 90%: 0.862
Metrics for persistence -1h:
	RMSE: 8.881 | R2: 0.807 | BFE: 15.878
Metrics for persistence -2h:
	RMSE: 12.040 | R2: 0.646 | BFE: 22.822
------------------------------------------------
Test storm number 91, from 2018-08-24 00:00:00 until 2018-09-01 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 18.686 | R2: 0.799 | BFE: 29.525
Metrics for LDi_ABG-1h:
	RMSE: 8.581 | R2: 0.958 | BFE: 11.295 | Inside 90%: 0.951
Metrics for LDi_ABG-2h:
	RMSE: 13.624 | R2: 0.893 | BFE: 20.230 | Inside 90%: 0.868
Metrics for persistence -1h:
	RMSE: 10.051 | R2: 0.932 | BFE: 17.057
Metrics for persistence -2h:
	RMSE: 15.970 | R2: 0.829 | BFE: 27.444
------------------------------------------------
Test storm number 92, from 2021-11-02 00:00:00 until 2021-11-10 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 14.601 | R2: 0.772 | BFE: 31.660
Metrics for LDi_ABG-1h:
	RMSE: 10.766 | R2: 0.876 | BFE: 13.660 | Inside 90%: 0.816
Metrics for LDi_ABG-2h:
	RMSE: 16.971 | R2: 0.692 | BFE: 26.248 | Inside 90%: 0.669
Metrics for persistence -1h:
	RMSE: 11.100 | R2: 0.847 | BFE: 21.576
Metrics for persistence -2h:
	RMSE: 16.088 | R2: 0.678 | BFE: 28.254
------------------------------------------------
Skipping blacklisted test storm 93 for ABG from 2022-01-12 00:00:00 - 2022-01-20 00:00:00
Test storm number 94, from 2022-11-05 00:00:00 until 2022-11-13 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 16.151 | R2: 0.717 | BFE: 29.084
Metrics for LDi_ABG-1h:
	RMSE: 7.852 | R2: 0.933 | BFE: 9.298 | Inside 90%: 0.931
Metrics for LDi_ABG-2h:
	RMSE: 14.647 | R2: 0.767 | BFE: 19.287 | Inside 90%: 0.781
Metrics for persistence -1h:
	RMSE: 9.236 | R2: 0.900 | BFE: 15.517
Metrics for persistence -2h:
	RMSE: 15.857 | R2: 0.706 | BFE: 28.216
------------------------------------------------
Test storm number 95, from 2023-02-25 00:00:00 until 2023-03-06 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 19.457 | R2: 0.751 | BFE: 37.289
Metrics for LDi_ABG-1h:
	RMSE: 12.428 | R2: 0.899 | BFE: 18.204 | Inside 90%: 0.890
Metrics for LDi_ABG-2h:
	RMSE: 18.433 | R2: 0.777 | BFE: 22.769 | Inside 90%: 0.736
Metrics for persistence -1h:
	RMSE: 13.045 | R2: 0.870 | BFE: 24.384
Metrics for persistence -2h:
	RMSE: 17.675 | R2: 0.761 | BFE: 33.272
------------------------------------------------
Test storm number 96, from 2023-03-21 00:00:00 until 2023-03-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 18.377 | R2: 0.782 | BFE: 24.434
Metrics for LDi_ABG-1h:
	RMSE: 11.087 | R2: 0.920 | BFE: 13.289 | Inside 90%: 0.853
Metrics for LDi_ABG-2h:
	RMSE: 15.496 | R2: 0.845 | BFE: 19.835 | Inside 90%: 0.765
Metrics for persistence -1h:
	RMSE: 11.949 | R2: 0.896 | BFE: 15.424
Metrics for persistence -2h:
	RMSE: 17.668 | R2: 0.774 | BFE: 22.476
------------------------------------------------
Test storm number 97, from 2023-04-21 00:00:00 until 2023-04-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 20.975 | R2: 0.785 | BFE: 17.032
Metrics for LDi_ABG-1h:
	RMSE: 11.008 | R2: 0.941 | BFE: 14.359 | Inside 90%: 0.897
Metrics for LDi_ABG-2h:
	RMSE: 16.248 | R2: 0.871 | BFE: 20.669 | Inside 90%: 0.790
Metrics for persistence -1h:
	RMSE: 11.299 | R2: 0.931 | BFE: 15.969
Metrics for persistence -2h:
	RMSE: 15.800 | R2: 0.865 | BFE: 24.260
------------------------------------------------
Test storm number 98, from 2023-08-03 00:00:00 until 2023-08-11 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 8.807 | R2: 0.806 | BFE: 7.317
Metrics for LDi_ABG-1h:
	RMSE: 6.588 | R2: 0.892 | BFE: 8.692 | Inside 90%: 0.966
Metrics for LDi_ABG-2h:
	RMSE: 10.297 | R2: 0.735 | BFE: 13.429 | Inside 90%: 0.893
Metrics for persistence -1h:
	RMSE: 7.519 | R2: 0.877 | BFE: 9.253
Metrics for persistence -2h:
	RMSE: 11.406 | R2: 0.716 | BFE: 16.195
------------------------------------------------
Test storm number 99, from 2023-11-03 00:00:00 until 2023-11-12 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 15.927 | R2: 0.882 | BFE: 37.337
Metrics for LDi_ABG-1h:
	RMSE: 14.285 | R2: 0.905 | BFE: 30.148 | Inside 90%: 0.948
Metrics for LDi_ABG-2h:
	RMSE: 16.602 | R2: 0.872 | BFE: 26.389 | Inside 90%: 0.842
Metrics for persistence -1h:
	RMSE: 16.012 | R2: 0.864 | BFE: 33.748
Metrics for persistence -2h:
	RMSE: 22.130 | R2: 0.740 | BFE: 31.483
------------------------------------------------
Test storm number 100, from 2023-11-23 00:00:00 until 2023-12-08 00:00:00, number of batches: 4896
Shapes of the input tensors: torch.Size([4800, 96, 6]), torch.Size([4800, 96, 5]), torch.Size([4800, 1]), torch.Size([4800, 2, 4]), (4800, 2)
Metrics for SYM_H:
	RMSE: 14.864 | R2: 0.742 | BFE: 28.931
Metrics for LDi_ABG-1h:
	RMSE: 9.020 | R2: 0.905 | BFE: 13.113 | Inside 90%: 0.937
Metrics for LDi_ABG-2h:
	RMSE: 16.567 | R2: 0.680 | BFE: 36.112 | Inside 90%: 0.826
Metrics for persistence -1h:
	RMSE: 10.929 | R2: 0.855 | BFE: 16.965
Metrics for persistence -2h:
	RMSE: 15.907 | R2: 0.692 | BFE: 24.601
------------------------------------------------
Test storm number 101, from 2024-03-01 00:00:00 until 2024-03-09 00:00:00, number of batches: 2881
Shapes of the input tensors: torch.Size([2785, 96, 6]), torch.Size([2785, 96, 5]), torch.Size([2785, 1]), torch.Size([2785, 2, 4]), (2785, 2)
Metrics for SYM_H:
	RMSE: 15.516 | R2: 0.745 | BFE: 32.441
Metrics for LDi_ABG-1h:
	RMSE: 7.531 | R2: 0.940 | BFE: 12.013 | Inside 90%: 0.961
Metrics for LDi_ABG-2h:
	RMSE: 12.853 | R2: 0.825 | BFE: 14.747 | Inside 90%: 0.870
Metrics for persistence -1h:
	RMSE: 10.096 | R2: 0.878 | BFE: 18.606
Metrics for persistence -2h:
	RMSE: 16.644 | R2: 0.667 | BFE: 31.380
------------------------------------------------
Test storm number 102, from 2024-03-22 00:00:00 until 2024-03-30 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 22.499 | R2: 0.480 | BFE: 31.685
Metrics for LDi_ABG-1h:
	RMSE: 10.287 | R2: 0.891 | BFE: 17.489 | Inside 90%: 0.870
Metrics for LDi_ABG-2h:
	RMSE: 15.487 | R2: 0.754 | BFE: 27.742 | Inside 90%: 0.719
Metrics for persistence -1h:
	RMSE: 13.801 | R2: 0.822 | BFE: 14.984
Metrics for persistence -2h:
	RMSE: 19.442 | R2: 0.646 | BFE: 19.125
------------------------------------------------
Skipping blacklisted test storm 103 for ABG from 2024-04-17 00:00:00 - 2024-04-25 00:00:00
Test storm number 104, from 2024-04-30 00:00:00 until 2024-05-24 00:00:00, number of batches: 7488
Shapes of the input tensors: torch.Size([7392, 96, 6]), torch.Size([7392, 96, 5]), torch.Size([7392, 1]), torch.Size([7392, 2, 4]), (7392, 2)
Metrics for SYM_H:
	RMSE: 19.596 | R2: 0.927 | BFE: 35.040
Metrics for LDi_ABG-1h:
	RMSE: 12.637 | R2: 0.969 | BFE: 27.746 | Inside 90%: 0.932
Metrics for LDi_ABG-2h:
	RMSE: 20.966 | R2: 0.916 | BFE: 45.431 | Inside 90%: 0.819
Metrics for persistence -1h:
	RMSE: 18.106 | R2: 0.933 | BFE: 47.260
Metrics for persistence -2h:
	RMSE: 25.764 | R2: 0.865 | BFE: 66.761
------------------------------------------------
Test storm number 105, from 2024-06-26 00:00:00 until 2024-07-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 18.476 | R2: 0.660 | BFE: 27.721
Metrics for LDi_ABG-1h:
	RMSE: 7.217 | R2: 0.948 | BFE: 9.325 | Inside 90%: 0.964
Metrics for LDi_ABG-2h:
	RMSE: 11.817 | R2: 0.861 | BFE: 17.827 | Inside 90%: 0.878
Metrics for persistence -1h:
	RMSE: 9.279 | R2: 0.904 | BFE: 18.609
Metrics for persistence -2h:
	RMSE: 14.318 | R2: 0.771 | BFE: 23.598
------------------------------------------------
Test storm number 106, from 2024-08-02 00:00:00 until 2024-08-19 00:00:00, number of batches: 5472
Shapes of the input tensors: torch.Size([5376, 96, 6]), torch.Size([5376, 96, 5]), torch.Size([5376, 1]), torch.Size([5376, 2, 4]), (5376, 2)
Metrics for SYM_H:
	RMSE: 28.192 | R2: 0.663 | BFE: 39.481
Metrics for LDi_ABG-1h:
	RMSE: 9.450 | R2: 0.962 | BFE: 11.562 | Inside 90%: 0.930
Metrics for LDi_ABG-2h:
	RMSE: 15.320 | R2: 0.900 | BFE: 17.114 | Inside 90%: 0.805
Metrics for persistence -1h:
	RMSE: 11.396 | R2: 0.941 | BFE: 16.139
Metrics for persistence -2h:
	RMSE: 16.693 | R2: 0.873 | BFE: 23.529
------------------------------------------------
Test storm number 107, from 2024-09-10 00:00:00 until 2024-09-23 00:00:00, number of batches: 4320
Shapes of the input tensors: torch.Size([4224, 96, 6]), torch.Size([4224, 96, 5]), torch.Size([4224, 1]), torch.Size([4224, 2, 4]), (4224, 2)
Metrics for SYM_H:
	RMSE: 16.456 | R2: 0.850 | BFE: 23.703
Metrics for LDi_ABG-1h:
	RMSE: 11.494 | R2: 0.927 | BFE: 15.044 | Inside 90%: 0.894
Metrics for LDi_ABG-2h:
	RMSE: 17.629 | R2: 0.828 | BFE: 24.888 | Inside 90%: 0.746
Metrics for persistence -1h:
	RMSE: 12.351 | R2: 0.913 | BFE: 14.373
Metrics for persistence -2h:
	RMSE: 18.406 | R2: 0.807 | BFE: 26.342
------------------------------------------------
Test storm number 108, from 2024-10-05 00:00:00 until 2024-10-17 00:00:00, number of batches: 4032
Shapes of the input tensors: torch.Size([3936, 96, 6]), torch.Size([3936, 96, 5]), torch.Size([3936, 1]), torch.Size([3936, 2, 4]), (3936, 2)
Metrics for SYM_H:
	RMSE: 23.421 | R2: 0.899 | BFE: 31.617
Metrics for LDi_ABG-1h:
	RMSE: 18.188 | R2: 0.939 | BFE: 27.678 | Inside 90%: 0.839
Metrics for LDi_ABG-2h:
	RMSE: 26.420 | R2: 0.871 | BFE: 39.186 | Inside 90%: 0.716
Metrics for persistence -1h:
	RMSE: 18.885 | R2: 0.929 | BFE: 28.137
Metrics for persistence -2h:
	RMSE: 26.818 | R2: 0.857 | BFE: 37.216
------------------------------------------------
Skipping blacklisted test storm 109 for ABG from 2024-11-07 00:00:00 - 2024-11-15 00:00:00
Metrics for the MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,ABG,89,51.318,19.426,26.694,0.571,20.252001,33.472000,7.563,12.157,11.743,19.057,0.917,0.782,0.891,0.760
1,ABG,90,22.046,12.131,15.757,0.450,10.234000,15.431000,5.656,8.121,8.172,11.436,0.852,0.710,0.919,0.862
2,ABG,91,29.525,12.406,18.686,0.799,11.295000,20.230000,5.444,8.680,8.581,13.624,0.958,0.893,0.951,0.868
3,ABG,92,31.660,9.375,14.601,0.772,13.660000,26.247999,7.476,11.575,10.766,16.971,0.876,0.692,0.816,0.669
4,ABG,94,29.084,12.950,16.151,0.717,9.298000,19.287001,5.315,9.934,7.852,14.647,0.933,0.767,0.931,0.781
5,ABG,95,37.289,14.424,19.457,0.751,18.204000,22.768999,7.989,12.140,12.428,18.433,0.899,0.777,0.890,0.736
6,ABG,96,24.434,11.188,18.377,0.782,13.289000,19.834999,7.138,10.686,11.087,15.496,0.920,0.845,0.853,0.765
7,ABG,97,17.032,18.278,20.975,0.785,14.359000,20.669001,7.339,11.392,11.008,16.248,0.941,0.871,0.897,0.790
8,ABG,98,7.317,6.739,8.807,0.806,8.692000,13.429000,4.820,7.694,6.588,10.297,0.892,0.735,0.966,0.893
9,ABG,99,37.337,9.740,15.927,0.882,30.148001,26.389000,8.339,11.464,14.285,16.602,0.905,0.872,0.948,0.842
10,ABG,100,28.931,9.990,14.864,0.742,13.113000,36.112000,5.761,9.608,9.020,16.567,0.905,0.680,0.937,0.826
11,ABG,101,32.441,9.620,15.516,0.745,12.013000,14.747000,4.904,7.718,7.531,12.853,0.940,0.825,0.961,0.870
12,ABG,102,31.685,20.045,22.499,0.480,17.489000,27.742001,6.839,10.203,10.287,15.487,0.891,0.754,0.870,0.719
13,ABG,104,35.040,12.751,19.596,0.927,27.746000,45.431000,7.363,12.063,12.637,20.966,0.969,0.916,0.932,0.819
14,ABG,105,27.721,15.438,18.476,0.660,9.325000,17.827000,5.169,8.481,7.217,11.817,0.948,0.861,0.964,0.878
15,ABG,106,39.481,24.073,28.192,0.663,11.562000,17.114000,6.127,9.967,9.450,15.320,0.962,0.900,0.930,0.805
16,ABG,107,23.703,11.869,16.456,0.850,15.044000,24.888000,7.553,11.883,11.494,17.629,0.927,0.828,0.894,0.746
17,ABG,108,31.617,17.465,23.421,0.899,27.677999,39.186001,10.452,15.734,18.188,26.420,0.939,0.871,0.839,0.716
18,ABG,Mean,29.870,13.773,18.581,0.738,15.744000,24.489000,6.736,10.528,10.463,16.104,0.921,0.810,0.910,0.797
19,ABG,Global,44.530,14.085,19.621,0.830,25.634001,40.916000,6.848,10.769,11.129,17.194,0.945,0.870,0.912,0.797

Mean and global MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
18,ABG,Mean,29.87,13.773,18.581,0.738,15.744000,24.489,6.736,10.528,10.463,16.104,0.921,0.81,0.910,0.797
19,ABG,Global,44.53,14.085,19.621,0.830,25.634001,40.916,6.848,10.769,11.129,17.194,0.945,0.87,0.912,0.797

           Station  BFE SYM-H  DTW SYM-H  RMSE SYM-H  R2 SYM_H
StormIndex
Mean           ABG      29.87     13.773      18.581     0.738
Global         ABG      44.53     14.085      19.621     0.830
Metrics for persistence -2h:
	RMSE: 13.092 | R2: 0.916 | BFE: 36.519
Metrics for persistence -2h:
	RMSE: 19.043 | R2: 0.822 | BFE: 52.786
Diff BFE (SYM-H nowcast - LDi forecast 1h):
Total: 18.896
Diff BFE (SYM-H nowcast - LDi forecast 2h):
Total: 3.614

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,ABG,89,51.317759,19.426228,26.693588,0.571418,20.251646,33.472221,7.562903,12.156519,11.742769,19.056625,0.917061,0.781570,0.890860,0.760123
1,ABG,90,22.046410,12.131271,15.756771,0.449524,10.234109,15.431261,5.656320,8.120926,8.171618,11.435536,0.851946,0.710054,0.919306,0.862039
2,ABG,91,29.525274,12.406395,18.686430,0.798634,11.295156,20.230370,5.444482,8.679736,8.581061,13.624454,0.957537,0.892954,0.950976,0.868113
3,ABG,92,31.660090,9.374594,14.600516,0.771799,13.660373,26.247932,7.476053,11.575391,10.766204,16.970741,0.875919,0.691694,0.815618,0.669414
4,ABG,94,29.083728,12.950148,16.150822,0.716789,9.298187,19.286816,5.314987,9.933503,7.851702,14.647009,0.933066,0.767074,0.931020,0.780911
5,ABG,95,37.289321,14.423606,19.456602,0.751398,18.203932,22.769079,7.989240,12.140351,12.428012,18.433069,0.898568,0.776866,0.890089,0.735827
6,ABG,96,24.433559,11.187536,18.376741,0.781544,13.288501,19.834919,7.137598,10.685829,11.086800,15.495961,0.920487,0.844667,0.853452,0.764751
7,ABG,97,17.032236,18.277609,20.974766,0.785222,14.358891,20.668797,7.339070,11.392482,11.008047,16.248240,0.940841,0.871113,0.897030,0.789819
8,ABG,98,7.316731,6.738902,8.807268,0.806347,8.692373,13.428818,4.819615,7.693836,6.587850,10.296861,0.891650,0.735301,0.966161,0.892842
9,ABG,99,37.336920,9.740413,15.927495,0.881778,30.147572,26.388510,8.339153,11.463689,14.284958,16.601902,0.904904,0.871555,0.947551,0.841882
10,ABG,100,28.931281,9.990051,14.864123,0.742198,13.112892,36.112190,5.761431,9.607727,9.020435,16.567101,0.905057,0.679742,0.936820,0.825966
11,ABG,101,32.440945,9.619822,15.516281,0.745185,12.012779,14.746623,4.903722,7.717627,7.530991,12.852617,0.939972,0.825163,0.960954,0.870282
12,ABG,102,31.685187,20.044859,22.498795,0.479805,17.488724,27.742283,6.839328,10.203048,10.287399,15.487444,0.891243,0.753506,0.869848,0.718872
13,ABG,104,35.040489,12.751295,19.596272,0.926575,27.745958,45.431416,7.362846,12.062735,12.637288,20.965929,0.969464,0.915952,0.931578,0.818892
14,ABG,105,27.720771,15.438069,18.476276,0.660215,9.325393,17.826916,5.169438,8.480823,7.216821,11.817385,0.948160,0.860999,0.964425,0.878091
15,ABG,106,39.480632,24.073196,28.191772,0.662543,11.561953,17.113657,6.126679,9.966680,9.449982,15.320019,0.962083,0.900347,0.930161,0.804983
16,ABG,107,23.702795,11.869132,16.455557,0.849729,15.043929,24.888405,7.552808,11.883060,11.493978,17.629204,0.926685,0.827529,0.894259,0.745527
17,ABG,108,31.617061,17.465138,23.421146,0.898575,27.677557,39.186028,10.451834,15.733792,18.187851,26.419947,0.938837,0.870939,0.838588,0.715649
18,ABG,Mean,29.870066,13.772681,18.580623,0.737738,15.744441,24.489235,6.735973,10.527653,10.462987,16.103891,0.920749,0.809835,0.910483,0.796888
19,ABG,Global,44.530046,14.084832,19.620636,0.830243,25.633680,40.916145,6.848358,10.769022,11.128581,17.194424,0.945389,0.869631,0.911835,0.796649

In [ ]:
station = constants.STATIONS[1]
color = "magenta"

str_return, metrics_station, sum_df_station = test_on_station(
    station, color, model, same_color=True
)
str_summary += str_return
sum_dfs_stations.append(sum_df_station)
summary_df.loc[len(summary_df)] = metrics_station

color = constants.COLOR_STATIONS[station]
_, _, _ = test_on_station(station, color, model, same_color=False)

Testing model RELDi
Evaluating for on station MMB
Test storm number 89, from 2017-09-06 00:00:00 until 2017-09-15 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 15.483 | R2: 0.759 | BFE: 28.970
Metrics for LDi_MMB-1h:
	RMSE: 13.880 | R2: 0.807 | BFE: 25.760 | Inside 90%: 0.941
Metrics for LDi_MMB-2h:
	RMSE: 22.257 | R2: 0.503 | BFE: 49.103 | Inside 90%: 0.858
Metrics for persistence -1h:
	RMSE: 15.056 | R2: 0.739 | BFE: 24.768
Metrics for persistence -2h:
	RMSE: 20.894 | R2: 0.497 | BFE: 32.174
------------------------------------------------
Test storm number 90, from 2017-09-26 00:00:00 until 2017-10-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 15.468 | R2: 0.427 | BFE: 20.572
Metrics for LDi_MMB-1h:
	RMSE: 10.774 | R2: 0.722 | BFE: 16.339 | Inside 90%: 0.933
Metrics for LDi_MMB-2h:
	RMSE: 14.437 | R2: 0.501 | BFE: 22.264 | Inside 90%: 0.901
Metrics for persistence -1h:
	RMSE: 10.703 | R2: 0.683 | BFE: 16.739
Metrics for persistence -2h:
	RMSE: 13.517 | R2: 0.494 | BFE: 24.956
------------------------------------------------
Test storm number 91, from 2018-08-24 00:00:00 until 2018-09-01 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 19.515 | R2: 0.653 | BFE: 20.044
Metrics for LDi_MMB-1h:
	RMSE: 10.348 | R2: 0.903 | BFE: 17.977 | Inside 90%: 0.948
Metrics for LDi_MMB-2h:
	RMSE: 12.207 | R2: 0.864 | BFE: 18.676 | Inside 90%: 0.884
Metrics for persistence -1h:
	RMSE: 10.514 | R2: 0.882 | BFE: 22.892
Metrics for persistence -2h:
	RMSE: 13.840 | R2: 0.795 | BFE: 24.253
------------------------------------------------
Test storm number 92, from 2021-11-02 00:00:00 until 2021-11-10 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 16.054 | R2: 0.638 | BFE: 20.394
Metrics for LDi_MMB-1h:
	RMSE: 10.835 | R2: 0.835 | BFE: 18.179 | Inside 90%: 0.892
Metrics for LDi_MMB-2h:
	RMSE: 15.445 | R2: 0.665 | BFE: 25.665 | Inside 90%: 0.812
Metrics for persistence -1h:
	RMSE: 11.238 | R2: 0.795 | BFE: 21.665
Metrics for persistence -2h:
	RMSE: 15.010 | R2: 0.633 | BFE: 28.446
------------------------------------------------
Skipping blacklisted test storm 93 for MMB from 2022-01-12 00:00:00 - 2022-01-20 00:00:00
Skipping blacklisted test storm 94 for MMB from 2022-11-05 00:00:00 - 2022-11-13 00:00:00
Test storm number 95, from 2023-02-25 00:00:00 until 2023-03-06 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 24.232 | R2: 0.286 | BFE: 25.188
Metrics for LDi_MMB-1h:
	RMSE: 12.854 | R2: 0.799 | BFE: 18.181 | Inside 90%: 0.916
Metrics for LDi_MMB-2h:
	RMSE: 16.305 | R2: 0.677 | BFE: 19.060 | Inside 90%: 0.836
Metrics for persistence -1h:
	RMSE: 14.338 | R2: 0.717 | BFE: 29.439
Metrics for persistence -2h:
	RMSE: 16.996 | R2: 0.602 | BFE: 40.279
------------------------------------------------
Test storm number 96, from 2023-03-21 00:00:00 until 2023-03-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 16.946 | R2: 0.706 | BFE: 20.727
Metrics for LDi_MMB-1h:
	RMSE: 10.050 | R2: 0.896 | BFE: 11.816 | Inside 90%: 0.921
Metrics for LDi_MMB-2h:
	RMSE: 13.196 | R2: 0.822 | BFE: 14.473 | Inside 90%: 0.828
Metrics for persistence -1h:
	RMSE: 11.344 | R2: 0.854 | BFE: 15.350
Metrics for persistence -2h:
	RMSE: 14.605 | R2: 0.757 | BFE: 18.044
------------------------------------------------
Test storm number 97, from 2023-04-21 00:00:00 until 2023-04-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 26.474 | R2: 0.563 | BFE: 26.895
Metrics for LDi_MMB-1h:
	RMSE: 12.357 | R2: 0.905 | BFE: 18.354 | Inside 90%: 0.892
Metrics for LDi_MMB-2h:
	RMSE: 18.908 | R2: 0.777 | BFE: 33.809 | Inside 90%: 0.772
Metrics for persistence -1h:
	RMSE: 12.289 | R2: 0.901 | BFE: 18.387
Metrics for persistence -2h:
	RMSE: 16.970 | R2: 0.811 | BFE: 25.446
------------------------------------------------
Test storm number 98, from 2023-08-03 00:00:00 until 2023-08-11 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 18.004 | R2: 0.190 | BFE: 22.471
Metrics for LDi_MMB-1h:
	RMSE: 7.809 | R2: 0.848 | BFE: 9.325 | Inside 90%: 0.939
Metrics for LDi_MMB-2h:
	RMSE: 11.453 | R2: 0.672 | BFE: 12.853 | Inside 90%: 0.866
Metrics for persistence -1h:
	RMSE: 8.866 | R2: 0.809 | BFE: 10.705
Metrics for persistence -2h:
	RMSE: 12.008 | R2: 0.650 | BFE: 14.912
------------------------------------------------
Test storm number 99, from 2023-11-03 00:00:00 until 2023-11-12 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 23.675 | R2: 0.462 | BFE: 25.406
Metrics for LDi_MMB-1h:
	RMSE: 12.232 | R2: 0.856 | BFE: 21.173 | Inside 90%: 0.963
Metrics for LDi_MMB-2h:
	RMSE: 14.893 | R2: 0.787 | BFE: 26.246 | Inside 90%: 0.941
Metrics for persistence -1h:
	RMSE: 12.928 | R2: 0.820 | BFE: 23.993
Metrics for persistence -2h:
	RMSE: 17.650 | R2: 0.664 | BFE: 24.771
------------------------------------------------
Test storm number 100, from 2023-11-23 00:00:00 until 2023-12-08 00:00:00, number of batches: 4896
Shapes of the input tensors: torch.Size([4800, 96, 6]), torch.Size([4800, 96, 5]), torch.Size([4800, 1]), torch.Size([4800, 2, 4]), (4800, 2)
Metrics for SYM_H:
	RMSE: 23.778 | R2: -0.276 | BFE: 24.676
Metrics for LDi_MMB-1h:
	RMSE: 9.708 | R2: 0.787 | BFE: 17.882 | Inside 90%: 0.959
Metrics for LDi_MMB-2h:
	RMSE: 15.650 | R2: 0.447 | BFE: 39.703 | Inside 90%: 0.861
Metrics for persistence -1h:
	RMSE: 10.380 | R2: 0.758 | BFE: 17.796
Metrics for persistence -2h:
	RMSE: 13.356 | R2: 0.599 | BFE: 20.497
------------------------------------------------
Test storm number 101, from 2024-03-01 00:00:00 until 2024-03-09 00:00:00, number of batches: 2881
Shapes of the input tensors: torch.Size([2785, 96, 6]), torch.Size([2785, 96, 5]), torch.Size([2785, 1]), torch.Size([2785, 2, 4]), (2785, 2)
Metrics for SYM_H:
	RMSE: 18.803 | R2: 0.132 | BFE: 18.836
Metrics for LDi_MMB-1h:
	RMSE: 6.725 | R2: 0.889 | BFE: 7.718 | Inside 90%: 0.973
Metrics for LDi_MMB-2h:
	RMSE: 10.603 | R2: 0.724 | BFE: 10.161 | Inside 90%: 0.934
Metrics for persistence -1h:
	RMSE: 6.941 | R2: 0.866 | BFE: 6.939
Metrics for persistence -2h:
	RMSE: 9.877 | R2: 0.729 | BFE: 11.470
------------------------------------------------
Test storm number 102, from 2024-03-22 00:00:00 until 2024-03-30 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 24.531 | R2: -0.374 | BFE: 38.202
Metrics for LDi_MMB-1h:
	RMSE: 11.168 | R2: 0.715 | BFE: 27.872 | Inside 90%: 0.924
Metrics for LDi_MMB-2h:
	RMSE: 15.810 | R2: 0.429 | BFE: 42.408 | Inside 90%: 0.810
Metrics for persistence -1h:
	RMSE: 13.613 | R2: 0.608 | BFE: 25.261
Metrics for persistence -2h:
	RMSE: 17.981 | R2: 0.316 | BFE: 43.169
------------------------------------------------
Test storm number 103, from 2024-04-17 00:00:00 until 2024-04-25 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 18.004 | R2: 0.181 | BFE: 18.364
Metrics for LDi_MMB-1h:
	RMSE: 8.089 | R2: 0.835 | BFE: 7.592 | Inside 90%: 0.912
Metrics for LDi_MMB-2h:
	RMSE: 11.364 | R2: 0.674 | BFE: 11.281 | Inside 90%: 0.792
Metrics for persistence -1h:
	RMSE: 8.766 | R2: 0.814 | BFE: 8.103
Metrics for persistence -2h:
	RMSE: 11.779 | R2: 0.664 | BFE: 11.416
------------------------------------------------
Test storm number 104, from 2024-04-30 00:00:00 until 2024-05-24 00:00:00, number of batches: 7488
Shapes of the input tensors: torch.Size([7392, 96, 6]), torch.Size([7392, 96, 5]), torch.Size([7392, 1]), torch.Size([7392, 2, 4]), (7392, 2)
Metrics for SYM_H:
	RMSE: 28.405 | R2: 0.768 | BFE: 57.562
Metrics for LDi_MMB-1h:
	RMSE: 17.681 | R2: 0.910 | BFE: 53.038 | Inside 90%: 0.950
Metrics for LDi_MMB-2h:
	RMSE: 24.171 | R2: 0.832 | BFE: 77.850 | Inside 90%: 0.891
Metrics for persistence -1h:
	RMSE: 22.884 | R2: 0.840 | BFE: 72.104
Metrics for persistence -2h:
	RMSE: 28.502 | R2: 0.752 | BFE: 86.025
------------------------------------------------
Test storm number 105, from 2024-06-26 00:00:00 until 2024-07-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 29.356 | R2: -1.178 | BFE: 22.544
Metrics for LDi_MMB-1h:
	RMSE: 8.993 | R2: 0.796 | BFE: 14.833 | Inside 90%: 0.969
Metrics for LDi_MMB-2h:
	RMSE: 12.576 | R2: 0.600 | BFE: 14.846 | Inside 90%: 0.914
Metrics for persistence -1h:
	RMSE: 9.396 | R2: 0.763 | BFE: 22.432
Metrics for persistence -2h:
	RMSE: 11.969 | R2: 0.615 | BFE: 27.609
------------------------------------------------
Test storm number 106, from 2024-08-02 00:00:00 until 2024-08-19 00:00:00, number of batches: 5472
Shapes of the input tensors: torch.Size([5376, 96, 6]), torch.Size([5376, 96, 5]), torch.Size([5376, 1]), torch.Size([5376, 2, 4]), (5376, 2)
Metrics for SYM_H:
	RMSE: 17.233 | R2: 0.754 | BFE: 23.127
Metrics for LDi_MMB-1h:
	RMSE: 11.716 | R2: 0.886 | BFE: 17.885 | Inside 90%: 0.934
Metrics for LDi_MMB-2h:
	RMSE: 16.408 | R2: 0.777 | BFE: 22.306 | Inside 90%: 0.848
Metrics for persistence -1h:
	RMSE: 13.828 | R2: 0.830 | BFE: 21.898
Metrics for persistence -2h:
	RMSE: 17.015 | R2: 0.742 | BFE: 24.398
------------------------------------------------
Test storm number 107, from 2024-09-10 00:00:00 until 2024-09-23 00:00:00, number of batches: 4320
Shapes of the input tensors: torch.Size([4224, 96, 6]), torch.Size([4224, 96, 5]), torch.Size([4224, 1]), torch.Size([4224, 2, 4]), (4224, 2)
Metrics for SYM_H:
	RMSE: 21.492 | R2: 0.592 | BFE: 19.025
Metrics for LDi_MMB-1h:
	RMSE: 13.384 | R2: 0.842 | BFE: 16.183 | Inside 90%: 0.865
Metrics for LDi_MMB-2h:
	RMSE: 18.359 | R2: 0.703 | BFE: 23.106 | Inside 90%: 0.732
Metrics for persistence -1h:
	RMSE: 13.721 | R2: 0.826 | BFE: 17.484
Metrics for persistence -2h:
	RMSE: 19.219 | R2: 0.659 | BFE: 27.274
------------------------------------------------
Test storm number 108, from 2024-10-05 00:00:00 until 2024-10-17 00:00:00, number of batches: 4032
Shapes of the input tensors: torch.Size([3936, 96, 6]), torch.Size([3936, 96, 5]), torch.Size([3936, 1]), torch.Size([3936, 2, 4]), (3936, 2)
Metrics for SYM_H:
	RMSE: 20.573 | R2: 0.870 | BFE: 32.421
Metrics for LDi_MMB-1h:
	RMSE: 20.597 | R2: 0.870 | BFE: 40.398 | Inside 90%: 0.846
Metrics for LDi_MMB-2h:
	RMSE: 28.043 | R2: 0.759 | BFE: 53.098 | Inside 90%: 0.730
Metrics for persistence -1h:
	RMSE: 19.710 | R2: 0.872 | BFE: 41.118
Metrics for persistence -2h:
	RMSE: 25.209 | R2: 0.791 | BFE: 50.289
------------------------------------------------
Test storm number 109, from 2024-11-07 00:00:00 until 2024-11-15 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 17.155 | R2: 0.492 | BFE: 14.339
Metrics for LDi_MMB-1h:
	RMSE: 9.953 | R2: 0.829 | BFE: 9.270 | Inside 90%: 0.925
Metrics for LDi_MMB-2h:
	RMSE: 15.076 | R2: 0.608 | BFE: 12.232 | Inside 90%: 0.780
Metrics for persistence -1h:
	RMSE: 8.674 | R2: 0.851 | BFE: 11.452
Metrics for persistence -2h:
	RMSE: 12.358 | R2: 0.697 | BFE: 16.964
------------------------------------------------
Metrics for the MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,MMB,89,28.970,10.558,15.483,0.759,25.760000,49.103001,7.834,12.457,13.880,22.257,0.807,0.503,0.941,0.858
1,MMB,90,20.572,11.795,15.468,0.427,16.339001,22.264000,7.175,9.793,10.774,14.437,0.722,0.501,0.933,0.901
2,MMB,91,20.044,15.881,19.515,0.653,17.976999,18.676001,6.474,9.295,10.348,12.207,0.903,0.864,0.948,0.884
3,MMB,92,20.394,13.135,16.054,0.638,18.179001,25.665001,6.903,10.619,10.835,15.445,0.835,0.665,0.892,0.812
4,MMB,95,25.188,18.132,24.232,0.286,18.181000,19.059999,8.536,11.126,12.854,16.305,0.799,0.677,0.916,0.836
5,MMB,96,20.727,12.164,16.946,0.706,11.816000,14.473000,6.774,9.770,10.050,13.196,0.896,0.822,0.921,0.828
6,MMB,97,26.895,22.179,26.474,0.563,18.354000,33.808998,8.462,12.895,12.357,18.908,0.905,0.777,0.892,0.772
7,MMB,98,22.471,13.493,18.004,0.190,9.325000,12.853000,5.502,8.637,7.809,11.453,0.848,0.672,0.939,0.866
8,MMB,99,25.406,21.195,23.675,0.462,21.173000,26.246000,7.235,9.988,12.232,14.893,0.856,0.787,0.963,0.941
9,MMB,100,24.676,21.315,23.778,-0.276,17.882000,39.702999,6.168,10.066,9.708,15.650,0.787,0.447,0.959,0.861
10,MMB,101,18.836,16.207,18.803,0.132,7.718000,10.161000,4.954,7.970,6.725,10.603,0.889,0.724,0.973,0.934
11,MMB,102,38.202,19.467,24.531,-0.374,27.872000,42.408001,7.079,10.532,11.168,15.810,0.715,0.429,0.924,0.810
12,MMB,103,18.364,14.036,18.004,0.181,7.592000,11.281000,6.099,8.875,8.089,11.364,0.835,0.674,0.912,0.792
13,MMB,104,57.562,22.137,28.405,0.768,53.037998,77.849998,8.389,12.237,17.681,24.171,0.910,0.832,0.950,0.891
14,MMB,105,22.544,27.318,29.356,-1.178,14.833000,14.846000,5.975,9.167,8.993,12.576,0.796,0.600,0.969,0.914
15,MMB,106,23.127,12.180,17.233,0.754,17.885000,22.306000,7.511,11.053,11.716,16.408,0.886,0.777,0.934,0.848
16,MMB,107,19.025,15.928,21.492,0.592,16.183001,23.106001,8.608,12.918,13.384,18.359,0.842,0.703,0.865,0.732
17,MMB,108,32.421,13.762,20.573,0.870,40.397999,53.098000,11.273,15.675,20.597,28.043,0.870,0.759,0.846,0.730
18,MMB,109,14.339,14.482,17.155,0.492,9.270000,12.232000,7.495,11.720,9.953,15.076,0.829,0.608,0.925,0.780
19,MMB,Mean,25.251,16.598,20.799,0.350,19.462000,27.850000,7.287,10.779,11.534,16.166,0.838,0.675,0.926,0.842
20,MMB,Global,48.868,16.944,21.841,0.648,51.676998,77.945000,7.472,11.048,12.723,17.774,0.881,0.767,0.927,0.842

Mean and global MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
19,MMB,Mean,25.251,16.598,20.799,0.350,19.462000,27.850,7.287,10.779,11.534,16.166,0.838,0.675,0.926,0.842
20,MMB,Global,48.868,16.944,21.841,0.648,51.676998,77.945,7.472,11.048,12.723,17.774,0.881,0.767,0.927,0.842

           Station  BFE SYM-H  DTW SYM-H  RMSE SYM-H  R2 SYM_H
StormIndex
Mean           MMB     25.251     16.598      20.799     0.350
Global         MMB     48.868     16.944      21.841     0.648
Metrics for persistence -2h:
	RMSE: 13.976 | R2: 0.840 | BFE: 63.204
Metrics for persistence -2h:
	RMSE: 18.071 | R2: 0.732 | BFE: 73.889
Diff BFE (SYM-H nowcast - LDi forecast 1h):
Total: -2.809
Diff BFE (SYM-H nowcast - LDi forecast 2h):
Total: -29.077

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,MMB,89,28.970003,10.557806,15.482639,0.759374,25.759645,49.102516,7.833791,12.456692,13.879745,22.256943,0.806618,0.502739,0.941381,0.858465
1,MMB,90,20.572237,11.794503,15.468181,0.427100,16.338943,22.263763,7.175279,9.792545,10.774351,14.437148,0.722040,0.500928,0.932755,0.901085
2,MMB,91,20.043994,15.881436,19.514948,0.653289,17.977362,18.675726,6.474243,9.294983,10.348242,12.206911,0.902509,0.864342,0.947505,0.884165
3,MMB,92,20.393878,13.135089,16.054302,0.637855,18.178793,25.665068,6.903223,10.619130,10.834508,15.445053,0.835063,0.664820,0.891540,0.812148
4,MMB,95,25.187811,18.132418,24.232353,0.285558,18.180920,19.060272,8.536189,11.126490,12.854163,16.304964,0.798969,0.676544,0.915542,0.836483
5,MMB,96,20.727015,12.164439,16.946199,0.705687,11.815985,14.473436,6.774405,9.770028,10.050018,13.195841,0.896486,0.821541,0.920555,0.827613
6,MMB,97,26.894582,22.179325,26.473621,0.562746,18.354452,33.809193,8.462420,12.894705,12.356864,18.908106,0.904737,0.776949,0.892017,0.771693
7,MMB,98,22.471309,13.492586,18.003632,0.190049,9.324956,12.853023,5.502089,8.636580,7.808781,11.452759,0.847628,0.672238,0.939262,0.865510
8,MMB,99,25.406242,21.194956,23.674667,0.461732,21.173141,26.246243,7.235442,9.987666,12.231531,14.893165,0.856321,0.786988,0.963363,0.940609
9,MMB,100,24.676463,21.314918,23.777777,-0.275570,17.881750,39.703365,6.167570,10.066218,9.707876,15.650310,0.787377,0.447404,0.958806,0.861143
10,MMB,101,18.835651,16.207098,18.802757,0.131594,7.717875,10.160761,4.954307,7.969813,6.725448,10.602581,0.888898,0.723877,0.973102,0.934056
11,MMB,102,38.202187,19.466972,24.531116,-0.373703,27.872019,42.408020,7.079087,10.532422,11.167819,15.809940,0.715295,0.429417,0.924078,0.810412
12,MMB,103,18.364280,14.035818,18.004364,0.181002,7.592054,11.281445,6.099010,8.875459,8.088731,11.364336,0.834694,0.673701,0.912364,0.791757
13,MMB,104,57.562137,22.137139,28.405371,0.768373,53.038486,77.850166,8.388877,12.236915,17.680967,24.171394,0.910257,0.832278,0.949949,0.891364
14,MMB,105,22.543611,27.317545,29.355602,-1.177748,14.832729,14.846165,5.975083,9.166723,8.993134,12.576419,0.795616,0.600295,0.969197,0.914100
15,MMB,106,23.127494,12.180417,17.233377,0.753605,17.884548,22.306076,7.511458,11.053456,11.716219,16.408165,0.886115,0.776637,0.934450,0.848479
16,MMB,107,19.024770,15.927530,21.491892,0.592464,16.182964,23.106323,8.607781,12.918103,13.383808,18.358545,0.841957,0.702633,0.864619,0.732176
17,MMB,108,32.420576,13.761791,20.573164,0.870275,40.397686,53.098465,11.273461,15.675067,20.596569,28.043213,0.869980,0.758967,0.845820,0.730113
18,MMB,109,14.338631,14.482456,17.154757,0.491846,9.270378,12.231894,7.495164,11.719671,9.953120,15.075535,0.828941,0.607561,0.924946,0.780477
19,MMB,Mean,25.250677,16.598118,20.798985,0.349765,19.461824,27.849573,7.286783,10.778561,11.534310,16.166386,0.838395,0.674729,0.926382,0.841676
20,MMB,Global,48.868305,16.943572,21.841389,0.648062,51.677444,77.944939,7.472484,11.048410,12.723472,17.774429,0.880569,0.766924,0.926617,0.841804

Testing model RELDi
Evaluating for on station MMB
Test storm number 89, from 2017-09-06 00:00:00 until 2017-09-15 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 15.483 | R2: 0.759 | BFE: 28.970
Metrics for LDi_MMB-1h:
	RMSE: 13.880 | R2: 0.807 | BFE: 25.760 | Inside 90%: 0.941
Metrics for LDi_MMB-2h:
	RMSE: 22.257 | R2: 0.503 | BFE: 49.103 | Inside 90%: 0.858
Metrics for persistence -1h:
	RMSE: 15.056 | R2: 0.739 | BFE: 24.768
Metrics for persistence -2h:
	RMSE: 20.894 | R2: 0.497 | BFE: 32.174
------------------------------------------------
Test storm number 90, from 2017-09-26 00:00:00 until 2017-10-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 15.468 | R2: 0.427 | BFE: 20.572
Metrics for LDi_MMB-1h:
	RMSE: 10.774 | R2: 0.722 | BFE: 16.339 | Inside 90%: 0.933
Metrics for LDi_MMB-2h:
	RMSE: 14.437 | R2: 0.501 | BFE: 22.264 | Inside 90%: 0.901
Metrics for persistence -1h:
	RMSE: 10.703 | R2: 0.683 | BFE: 16.739
Metrics for persistence -2h:
	RMSE: 13.517 | R2: 0.494 | BFE: 24.956
------------------------------------------------
Test storm number 91, from 2018-08-24 00:00:00 until 2018-09-01 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 19.515 | R2: 0.653 | BFE: 20.044
Metrics for LDi_MMB-1h:
	RMSE: 10.348 | R2: 0.903 | BFE: 17.977 | Inside 90%: 0.948
Metrics for LDi_MMB-2h:
	RMSE: 12.207 | R2: 0.864 | BFE: 18.676 | Inside 90%: 0.884
Metrics for persistence -1h:
	RMSE: 10.514 | R2: 0.882 | BFE: 22.892
Metrics for persistence -2h:
	RMSE: 13.840 | R2: 0.795 | BFE: 24.253
------------------------------------------------
Test storm number 92, from 2021-11-02 00:00:00 until 2021-11-10 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 16.054 | R2: 0.638 | BFE: 20.394
Metrics for LDi_MMB-1h:
	RMSE: 10.835 | R2: 0.835 | BFE: 18.179 | Inside 90%: 0.892
Metrics for LDi_MMB-2h:
	RMSE: 15.445 | R2: 0.665 | BFE: 25.665 | Inside 90%: 0.812
Metrics for persistence -1h:
	RMSE: 11.238 | R2: 0.795 | BFE: 21.665
Metrics for persistence -2h:
	RMSE: 15.010 | R2: 0.633 | BFE: 28.446
------------------------------------------------
Skipping blacklisted test storm 93 for MMB from 2022-01-12 00:00:00 - 2022-01-20 00:00:00
Skipping blacklisted test storm 94 for MMB from 2022-11-05 00:00:00 - 2022-11-13 00:00:00
Test storm number 95, from 2023-02-25 00:00:00 until 2023-03-06 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 24.232 | R2: 0.286 | BFE: 25.188
Metrics for LDi_MMB-1h:
	RMSE: 12.854 | R2: 0.799 | BFE: 18.181 | Inside 90%: 0.916
Metrics for LDi_MMB-2h:
	RMSE: 16.305 | R2: 0.677 | BFE: 19.060 | Inside 90%: 0.836
Metrics for persistence -1h:
	RMSE: 14.338 | R2: 0.717 | BFE: 29.439
Metrics for persistence -2h:
	RMSE: 16.996 | R2: 0.602 | BFE: 40.279
------------------------------------------------
Test storm number 96, from 2023-03-21 00:00:00 until 2023-03-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 16.946 | R2: 0.706 | BFE: 20.727
Metrics for LDi_MMB-1h:
	RMSE: 10.050 | R2: 0.896 | BFE: 11.816 | Inside 90%: 0.921
Metrics for LDi_MMB-2h:
	RMSE: 13.196 | R2: 0.822 | BFE: 14.473 | Inside 90%: 0.828
Metrics for persistence -1h:
	RMSE: 11.344 | R2: 0.854 | BFE: 15.350
Metrics for persistence -2h:
	RMSE: 14.605 | R2: 0.757 | BFE: 18.044
------------------------------------------------
Test storm number 97, from 2023-04-21 00:00:00 until 2023-04-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 26.474 | R2: 0.563 | BFE: 26.895
Metrics for LDi_MMB-1h:
	RMSE: 12.357 | R2: 0.905 | BFE: 18.354 | Inside 90%: 0.892
Metrics for LDi_MMB-2h:
	RMSE: 18.908 | R2: 0.777 | BFE: 33.809 | Inside 90%: 0.772
Metrics for persistence -1h:
	RMSE: 12.289 | R2: 0.901 | BFE: 18.387
Metrics for persistence -2h:
	RMSE: 16.970 | R2: 0.811 | BFE: 25.446
------------------------------------------------
Test storm number 98, from 2023-08-03 00:00:00 until 2023-08-11 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 18.004 | R2: 0.190 | BFE: 22.471
Metrics for LDi_MMB-1h:
	RMSE: 7.809 | R2: 0.848 | BFE: 9.325 | Inside 90%: 0.939
Metrics for LDi_MMB-2h:
	RMSE: 11.453 | R2: 0.672 | BFE: 12.853 | Inside 90%: 0.866
Metrics for persistence -1h:
	RMSE: 8.866 | R2: 0.809 | BFE: 10.705
Metrics for persistence -2h:
	RMSE: 12.008 | R2: 0.650 | BFE: 14.912
------------------------------------------------
Test storm number 99, from 2023-11-03 00:00:00 until 2023-11-12 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 23.675 | R2: 0.462 | BFE: 25.406
Metrics for LDi_MMB-1h:
	RMSE: 12.232 | R2: 0.856 | BFE: 21.173 | Inside 90%: 0.963
Metrics for LDi_MMB-2h:
	RMSE: 14.893 | R2: 0.787 | BFE: 26.246 | Inside 90%: 0.941
Metrics for persistence -1h:
	RMSE: 12.928 | R2: 0.820 | BFE: 23.993
Metrics for persistence -2h:
	RMSE: 17.650 | R2: 0.664 | BFE: 24.771
------------------------------------------------
Test storm number 100, from 2023-11-23 00:00:00 until 2023-12-08 00:00:00, number of batches: 4896
Shapes of the input tensors: torch.Size([4800, 96, 6]), torch.Size([4800, 96, 5]), torch.Size([4800, 1]), torch.Size([4800, 2, 4]), (4800, 2)
Metrics for SYM_H:
	RMSE: 23.778 | R2: -0.276 | BFE: 24.676
Metrics for LDi_MMB-1h:
	RMSE: 9.708 | R2: 0.787 | BFE: 17.882 | Inside 90%: 0.959
Metrics for LDi_MMB-2h:
	RMSE: 15.650 | R2: 0.447 | BFE: 39.703 | Inside 90%: 0.861
Metrics for persistence -1h:
	RMSE: 10.380 | R2: 0.758 | BFE: 17.796
Metrics for persistence -2h:
	RMSE: 13.356 | R2: 0.599 | BFE: 20.497
------------------------------------------------
Test storm number 101, from 2024-03-01 00:00:00 until 2024-03-09 00:00:00, number of batches: 2881
Shapes of the input tensors: torch.Size([2785, 96, 6]), torch.Size([2785, 96, 5]), torch.Size([2785, 1]), torch.Size([2785, 2, 4]), (2785, 2)
Metrics for SYM_H:
	RMSE: 18.803 | R2: 0.132 | BFE: 18.836
Metrics for LDi_MMB-1h:
	RMSE: 6.725 | R2: 0.889 | BFE: 7.718 | Inside 90%: 0.973
Metrics for LDi_MMB-2h:
	RMSE: 10.603 | R2: 0.724 | BFE: 10.161 | Inside 90%: 0.934
Metrics for persistence -1h:
	RMSE: 6.941 | R2: 0.866 | BFE: 6.939
Metrics for persistence -2h:
	RMSE: 9.877 | R2: 0.729 | BFE: 11.470
------------------------------------------------
Test storm number 102, from 2024-03-22 00:00:00 until 2024-03-30 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 24.531 | R2: -0.374 | BFE: 38.202
Metrics for LDi_MMB-1h:
	RMSE: 11.168 | R2: 0.715 | BFE: 27.872 | Inside 90%: 0.924
Metrics for LDi_MMB-2h:
	RMSE: 15.810 | R2: 0.429 | BFE: 42.408 | Inside 90%: 0.810
Metrics for persistence -1h:
	RMSE: 13.613 | R2: 0.608 | BFE: 25.261
Metrics for persistence -2h:
	RMSE: 17.981 | R2: 0.316 | BFE: 43.169
------------------------------------------------
Test storm number 103, from 2024-04-17 00:00:00 until 2024-04-25 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 18.004 | R2: 0.181 | BFE: 18.364
Metrics for LDi_MMB-1h:
	RMSE: 8.089 | R2: 0.835 | BFE: 7.592 | Inside 90%: 0.912
Metrics for LDi_MMB-2h:
	RMSE: 11.364 | R2: 0.674 | BFE: 11.281 | Inside 90%: 0.792
Metrics for persistence -1h:
	RMSE: 8.766 | R2: 0.814 | BFE: 8.103
Metrics for persistence -2h:
	RMSE: 11.779 | R2: 0.664 | BFE: 11.416
------------------------------------------------
Test storm number 104, from 2024-04-30 00:00:00 until 2024-05-24 00:00:00, number of batches: 7488
Shapes of the input tensors: torch.Size([7392, 96, 6]), torch.Size([7392, 96, 5]), torch.Size([7392, 1]), torch.Size([7392, 2, 4]), (7392, 2)
Metrics for SYM_H:
	RMSE: 28.405 | R2: 0.768 | BFE: 57.562
Metrics for LDi_MMB-1h:
	RMSE: 17.681 | R2: 0.910 | BFE: 53.038 | Inside 90%: 0.950
Metrics for LDi_MMB-2h:
	RMSE: 24.171 | R2: 0.832 | BFE: 77.850 | Inside 90%: 0.891
Metrics for persistence -1h:
	RMSE: 22.884 | R2: 0.840 | BFE: 72.104
Metrics for persistence -2h:
	RMSE: 28.502 | R2: 0.752 | BFE: 86.025
------------------------------------------------
Test storm number 105, from 2024-06-26 00:00:00 until 2024-07-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 29.356 | R2: -1.178 | BFE: 22.544
Metrics for LDi_MMB-1h:
	RMSE: 8.993 | R2: 0.796 | BFE: 14.833 | Inside 90%: 0.969
Metrics for LDi_MMB-2h:
	RMSE: 12.576 | R2: 0.600 | BFE: 14.846 | Inside 90%: 0.914
Metrics for persistence -1h:
	RMSE: 9.396 | R2: 0.763 | BFE: 22.432
Metrics for persistence -2h:
	RMSE: 11.969 | R2: 0.615 | BFE: 27.609
------------------------------------------------
Test storm number 106, from 2024-08-02 00:00:00 until 2024-08-19 00:00:00, number of batches: 5472
Shapes of the input tensors: torch.Size([5376, 96, 6]), torch.Size([5376, 96, 5]), torch.Size([5376, 1]), torch.Size([5376, 2, 4]), (5376, 2)
Metrics for SYM_H:
	RMSE: 17.233 | R2: 0.754 | BFE: 23.127
Metrics for LDi_MMB-1h:
	RMSE: 11.716 | R2: 0.886 | BFE: 17.885 | Inside 90%: 0.934
Metrics for LDi_MMB-2h:
	RMSE: 16.408 | R2: 0.777 | BFE: 22.306 | Inside 90%: 0.848
Metrics for persistence -1h:
	RMSE: 13.828 | R2: 0.830 | BFE: 21.898
Metrics for persistence -2h:
	RMSE: 17.015 | R2: 0.742 | BFE: 24.398
------------------------------------------------
Test storm number 107, from 2024-09-10 00:00:00 until 2024-09-23 00:00:00, number of batches: 4320
Shapes of the input tensors: torch.Size([4224, 96, 6]), torch.Size([4224, 96, 5]), torch.Size([4224, 1]), torch.Size([4224, 2, 4]), (4224, 2)
Metrics for SYM_H:
	RMSE: 21.492 | R2: 0.592 | BFE: 19.025
Metrics for LDi_MMB-1h:
	RMSE: 13.384 | R2: 0.842 | BFE: 16.183 | Inside 90%: 0.865
Metrics for LDi_MMB-2h:
	RMSE: 18.359 | R2: 0.703 | BFE: 23.106 | Inside 90%: 0.732
Metrics for persistence -1h:
	RMSE: 13.721 | R2: 0.826 | BFE: 17.484
Metrics for persistence -2h:
	RMSE: 19.219 | R2: 0.659 | BFE: 27.274
------------------------------------------------
Test storm number 108, from 2024-10-05 00:00:00 until 2024-10-17 00:00:00, number of batches: 4032
Shapes of the input tensors: torch.Size([3936, 96, 6]), torch.Size([3936, 96, 5]), torch.Size([3936, 1]), torch.Size([3936, 2, 4]), (3936, 2)
Metrics for SYM_H:
	RMSE: 20.573 | R2: 0.870 | BFE: 32.421
Metrics for LDi_MMB-1h:
	RMSE: 20.597 | R2: 0.870 | BFE: 40.398 | Inside 90%: 0.846
Metrics for LDi_MMB-2h:
	RMSE: 28.043 | R2: 0.759 | BFE: 53.098 | Inside 90%: 0.730
Metrics for persistence -1h:
	RMSE: 19.710 | R2: 0.872 | BFE: 41.118
Metrics for persistence -2h:
	RMSE: 25.209 | R2: 0.791 | BFE: 50.289
------------------------------------------------
Test storm number 109, from 2024-11-07 00:00:00 until 2024-11-15 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 17.155 | R2: 0.492 | BFE: 14.339
Metrics for LDi_MMB-1h:
	RMSE: 9.953 | R2: 0.829 | BFE: 9.270 | Inside 90%: 0.925
Metrics for LDi_MMB-2h:
	RMSE: 15.076 | R2: 0.608 | BFE: 12.232 | Inside 90%: 0.780
Metrics for persistence -1h:
	RMSE: 8.674 | R2: 0.851 | BFE: 11.452
Metrics for persistence -2h:
	RMSE: 12.358 | R2: 0.697 | BFE: 16.964
------------------------------------------------
Metrics for the MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,MMB,89,28.970,10.558,15.483,0.759,25.760000,49.103001,7.834,12.457,13.880,22.257,0.807,0.503,0.941,0.858
1,MMB,90,20.572,11.795,15.468,0.427,16.339001,22.264000,7.175,9.793,10.774,14.437,0.722,0.501,0.933,0.901
2,MMB,91,20.044,15.881,19.515,0.653,17.976999,18.676001,6.474,9.295,10.348,12.207,0.903,0.864,0.948,0.884
3,MMB,92,20.394,13.135,16.054,0.638,18.179001,25.665001,6.903,10.619,10.835,15.445,0.835,0.665,0.892,0.812
4,MMB,95,25.188,18.132,24.232,0.286,18.181000,19.059999,8.536,11.126,12.854,16.305,0.799,0.677,0.916,0.836
5,MMB,96,20.727,12.164,16.946,0.706,11.816000,14.473000,6.774,9.770,10.050,13.196,0.896,0.822,0.921,0.828
6,MMB,97,26.895,22.179,26.474,0.563,18.354000,33.808998,8.462,12.895,12.357,18.908,0.905,0.777,0.892,0.772
7,MMB,98,22.471,13.493,18.004,0.190,9.325000,12.853000,5.502,8.637,7.809,11.453,0.848,0.672,0.939,0.866
8,MMB,99,25.406,21.195,23.675,0.462,21.173000,26.246000,7.235,9.988,12.232,14.893,0.856,0.787,0.963,0.941
9,MMB,100,24.676,21.315,23.778,-0.276,17.882000,39.702999,6.168,10.066,9.708,15.650,0.787,0.447,0.959,0.861
10,MMB,101,18.836,16.207,18.803,0.132,7.718000,10.161000,4.954,7.970,6.725,10.603,0.889,0.724,0.973,0.934
11,MMB,102,38.202,19.467,24.531,-0.374,27.872000,42.408001,7.079,10.532,11.168,15.810,0.715,0.429,0.924,0.810
12,MMB,103,18.364,14.036,18.004,0.181,7.592000,11.281000,6.099,8.875,8.089,11.364,0.835,0.674,0.912,0.792
13,MMB,104,57.562,22.137,28.405,0.768,53.037998,77.849998,8.389,12.237,17.681,24.171,0.910,0.832,0.950,0.891
14,MMB,105,22.544,27.318,29.356,-1.178,14.833000,14.846000,5.975,9.167,8.993,12.576,0.796,0.600,0.969,0.914
15,MMB,106,23.127,12.180,17.233,0.754,17.885000,22.306000,7.511,11.053,11.716,16.408,0.886,0.777,0.934,0.848
16,MMB,107,19.025,15.928,21.492,0.592,16.183001,23.106001,8.608,12.918,13.384,18.359,0.842,0.703,0.865,0.732
17,MMB,108,32.421,13.762,20.573,0.870,40.397999,53.098000,11.273,15.675,20.597,28.043,0.870,0.759,0.846,0.730
18,MMB,109,14.339,14.482,17.155,0.492,9.270000,12.232000,7.495,11.720,9.953,15.076,0.829,0.608,0.925,0.780
19,MMB,Mean,25.251,16.598,20.799,0.350,19.462000,27.850000,7.287,10.779,11.534,16.166,0.838,0.675,0.926,0.842
20,MMB,Global,48.868,16.944,21.841,0.648,51.676998,77.945000,7.472,11.048,12.723,17.774,0.881,0.767,0.927,0.842

Mean and global MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
19,MMB,Mean,25.251,16.598,20.799,0.350,19.462000,27.850,7.287,10.779,11.534,16.166,0.838,0.675,0.926,0.842
20,MMB,Global,48.868,16.944,21.841,0.648,51.676998,77.945,7.472,11.048,12.723,17.774,0.881,0.767,0.927,0.842

           Station  BFE SYM-H  DTW SYM-H  RMSE SYM-H  R2 SYM_H
StormIndex
Mean           MMB     25.251     16.598      20.799     0.350
Global         MMB     48.868     16.944      21.841     0.648
Metrics for persistence -2h:
	RMSE: 13.976 | R2: 0.840 | BFE: 63.204
Metrics for persistence -2h:
	RMSE: 18.071 | R2: 0.732 | BFE: 73.889
Diff BFE (SYM-H nowcast - LDi forecast 1h):
Total: -2.809
Diff BFE (SYM-H nowcast - LDi forecast 2h):
Total: -29.077

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,MMB,89,28.970003,10.557806,15.482639,0.759374,25.759645,49.102516,7.833791,12.456692,13.879745,22.256943,0.806618,0.502739,0.941381,0.858465
1,MMB,90,20.572237,11.794503,15.468181,0.427100,16.338943,22.263763,7.175279,9.792545,10.774351,14.437148,0.722040,0.500928,0.932755,0.901085
2,MMB,91,20.043994,15.881436,19.514948,0.653289,17.977362,18.675726,6.474243,9.294983,10.348242,12.206911,0.902509,0.864342,0.947505,0.884165
3,MMB,92,20.393878,13.135089,16.054302,0.637855,18.178793,25.665068,6.903223,10.619130,10.834508,15.445053,0.835063,0.664820,0.891540,0.812148
4,MMB,95,25.187811,18.132418,24.232353,0.285558,18.180920,19.060272,8.536189,11.126490,12.854163,16.304964,0.798969,0.676544,0.915542,0.836483
5,MMB,96,20.727015,12.164439,16.946199,0.705687,11.815985,14.473436,6.774405,9.770028,10.050018,13.195841,0.896486,0.821541,0.920555,0.827613
6,MMB,97,26.894582,22.179325,26.473621,0.562746,18.354452,33.809193,8.462420,12.894705,12.356864,18.908106,0.904737,0.776949,0.892017,0.771693
7,MMB,98,22.471309,13.492586,18.003632,0.190049,9.324956,12.853023,5.502089,8.636580,7.808781,11.452759,0.847628,0.672238,0.939262,0.865510
8,MMB,99,25.406242,21.194956,23.674667,0.461732,21.173141,26.246243,7.235442,9.987666,12.231531,14.893165,0.856321,0.786988,0.963363,0.940609
9,MMB,100,24.676463,21.314918,23.777777,-0.275570,17.881750,39.703365,6.167570,10.066218,9.707876,15.650310,0.787377,0.447404,0.958806,0.861143
10,MMB,101,18.835651,16.207098,18.802757,0.131594,7.717875,10.160761,4.954307,7.969813,6.725448,10.602581,0.888898,0.723877,0.973102,0.934056
11,MMB,102,38.202187,19.466972,24.531116,-0.373703,27.872019,42.408020,7.079087,10.532422,11.167819,15.809940,0.715295,0.429417,0.924078,0.810412
12,MMB,103,18.364280,14.035818,18.004364,0.181002,7.592054,11.281445,6.099010,8.875459,8.088731,11.364336,0.834694,0.673701,0.912364,0.791757
13,MMB,104,57.562137,22.137139,28.405371,0.768373,53.038486,77.850166,8.388877,12.236915,17.680967,24.171394,0.910257,0.832278,0.949949,0.891364
14,MMB,105,22.543611,27.317545,29.355602,-1.177748,14.832729,14.846165,5.975083,9.166723,8.993134,12.576419,0.795616,0.600295,0.969197,0.914100
15,MMB,106,23.127494,12.180417,17.233377,0.753605,17.884548,22.306076,7.511458,11.053456,11.716219,16.408165,0.886115,0.776637,0.934450,0.848479
16,MMB,107,19.024770,15.927530,21.491892,0.592464,16.182964,23.106323,8.607781,12.918103,13.383808,18.358545,0.841957,0.702633,0.864619,0.732176
17,MMB,108,32.420576,13.761791,20.573164,0.870275,40.397686,53.098465,11.273461,15.675067,20.596569,28.043213,0.869980,0.758967,0.845820,0.730113
18,MMB,109,14.338631,14.482456,17.154757,0.491846,9.270378,12.231894,7.495164,11.719671,9.953120,15.075535,0.828941,0.607561,0.924946,0.780477
19,MMB,Mean,25.250677,16.598118,20.798985,0.349765,19.461824,27.849573,7.286783,10.778561,11.534310,16.166386,0.838395,0.674729,0.926382,0.841676
20,MMB,Global,48.868305,16.943572,21.841389,0.648062,51.677444,77.944939,7.472484,11.048410,12.723472,17.774429,0.880569,0.766924,0.926617,0.841804

In [ ]:
station = constants.STATIONS[2]
color = "magenta"

str_return, metrics_station, sum_df_station = test_on_station(
    station, color, model, same_color=True
)
str_summary += str_return
sum_dfs_stations.append(sum_df_station)
summary_df.loc[len(summary_df)] = metrics_station

color = constants.COLOR_STATIONS[station]
_, _, _ = test_on_station(station, color, model, same_color=False)

Testing model RELDi
Evaluating for on station CLF
Test storm number 89, from 2017-09-06 00:00:00 until 2017-09-15 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 20.225 | R2: 0.429 | BFE: 29.023
Metrics for LDi_CLF-1h:
	RMSE: 12.581 | R2: 0.779 | BFE: 19.815 | Inside 90%: 0.936
Metrics for LDi_CLF-2h:
	RMSE: 17.295 | R2: 0.582 | BFE: 31.102 | Inside 90%: 0.846
Metrics for persistence -1h:
	RMSE: 14.432 | R2: 0.674 | BFE: 18.977
Metrics for persistence -2h:
	RMSE: 18.465 | R2: 0.466 | BFE: 23.340
------------------------------------------------
Test storm number 90, from 2017-09-26 00:00:00 until 2017-10-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 20.098 | R2: -0.875 | BFE: 11.599
Metrics for LDi_CLF-1h:
	RMSE: 9.776 | R2: 0.556 | BFE: 10.888 | Inside 90%: 0.917
Metrics for LDi_CLF-2h:
	RMSE: 12.311 | R2: 0.296 | BFE: 11.859 | Inside 90%: 0.877
Metrics for persistence -1h:
	RMSE: 9.469 | R2: 0.510 | BFE: 13.961
Metrics for persistence -2h:
	RMSE: 11.204 | R2: 0.314 | BFE: 14.256
------------------------------------------------
Test storm number 91, from 2018-08-24 00:00:00 until 2018-09-01 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 30.035 | R2: -0.034 | BFE: 51.787
Metrics for LDi_CLF-1h:
	RMSE: 11.865 | R2: 0.839 | BFE: 19.524 | Inside 90%: 0.945
Metrics for LDi_CLF-2h:
	RMSE: 17.454 | R2: 0.651 | BFE: 27.134 | Inside 90%: 0.837
Metrics for persistence -1h:
	RMSE: 11.264 | R2: 0.829 | BFE: 18.932
Metrics for persistence -2h:
	RMSE: 16.142 | R2: 0.649 | BFE: 36.578
------------------------------------------------
Test storm number 92, from 2021-11-02 00:00:00 until 2021-11-10 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 16.916 | R2: 0.359 | BFE: 32.090
Metrics for LDi_CLF-1h:
	RMSE: 12.634 | R2: 0.642 | BFE: 26.579 | Inside 90%: 0.873
Metrics for LDi_CLF-2h:
	RMSE: 16.299 | R2: 0.404 | BFE: 33.107 | Inside 90%: 0.785
Metrics for persistence -1h:
	RMSE: 12.431 | R2: 0.600 | BFE: 31.990
Metrics for persistence -2h:
	RMSE: 15.443 | R2: 0.383 | BFE: 34.379
------------------------------------------------
Test storm number 93, from 2022-01-12 00:00:00 until 2022-01-20 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 20.450 | R2: -0.138 | BFE: 24.715
Metrics for LDi_CLF-1h:
	RMSE: 9.131 | R2: 0.773 | BFE: 13.680 | Inside 90%: 0.969
Metrics for LDi_CLF-2h:
	RMSE: 12.003 | R2: 0.608 | BFE: 17.554 | Inside 90%: 0.938
Metrics for persistence -1h:
	RMSE: 9.321 | R2: 0.725 | BFE: 18.397
Metrics for persistence -2h:
	RMSE: 12.139 | R2: 0.534 | BFE: 23.588
------------------------------------------------
Test storm number 94, from 2022-11-05 00:00:00 until 2022-11-13 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 28.229 | R2: -1.498 | BFE: 19.697
Metrics for LDi_CLF-1h:
	RMSE: 6.567 | R2: 0.865 | BFE: 9.855 | Inside 90%: 0.986
Metrics for LDi_CLF-2h:
	RMSE: 11.006 | R2: 0.620 | BFE: 17.781 | Inside 90%: 0.934
Metrics for persistence -1h:
	RMSE: 6.958 | R2: 0.829 | BFE: 13.392
Metrics for persistence -2h:
	RMSE: 10.319 | R2: 0.625 | BFE: 24.063
------------------------------------------------
Test storm number 95, from 2023-02-25 00:00:00 until 2023-03-06 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 24.789 | R2: 0.103 | BFE: 22.405
Metrics for LDi_CLF-1h:
	RMSE: 13.010 | R2: 0.753 | BFE: 15.226 | Inside 90%: 0.939
Metrics for LDi_CLF-2h:
	RMSE: 19.156 | R2: 0.464 | BFE: 21.454 | Inside 90%: 0.831
Metrics for persistence -1h:
	RMSE: 13.588 | R2: 0.713 | BFE: 21.618
Metrics for persistence -2h:
	RMSE: 17.738 | R2: 0.510 | BFE: 29.059
------------------------------------------------
Test storm number 96, from 2023-03-21 00:00:00 until 2023-03-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 22.895 | R2: 0.054 | BFE: 29.375
Metrics for LDi_CLF-1h:
	RMSE: 10.907 | R2: 0.785 | BFE: 15.139 | Inside 90%: 0.897
Metrics for LDi_CLF-2h:
	RMSE: 13.363 | R2: 0.678 | BFE: 18.035 | Inside 90%: 0.856
Metrics for persistence -1h:
	RMSE: 11.475 | R2: 0.745 | BFE: 20.259
Metrics for persistence -2h:
	RMSE: 14.196 | R2: 0.610 | BFE: 21.866
------------------------------------------------
Test storm number 97, from 2023-04-21 00:00:00 until 2023-04-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 35.520 | R2: -0.632 | BFE: 54.820
Metrics for LDi_CLF-1h:
	RMSE: 12.929 | R2: 0.784 | BFE: 27.682 | Inside 90%: 0.891
Metrics for LDi_CLF-2h:
	RMSE: 16.783 | R2: 0.636 | BFE: 30.516 | Inside 90%: 0.754
Metrics for persistence -1h:
	RMSE: 13.426 | R2: 0.744 | BFE: 26.755
Metrics for persistence -2h:
	RMSE: 17.424 | R2: 0.569 | BFE: 41.232
------------------------------------------------
Test storm number 98, from 2023-08-03 00:00:00 until 2023-08-11 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 16.614 | R2: -0.279 | BFE: 17.530
Metrics for LDi_CLF-1h:
	RMSE: 9.305 | R2: 0.599 | BFE: 15.617 | Inside 90%: 0.956
Metrics for LDi_CLF-2h:
	RMSE: 13.143 | R2: 0.199 | BFE: 25.833 | Inside 90%: 0.854
Metrics for persistence -1h:
	RMSE: 8.662 | R2: 0.614 | BFE: 16.407
Metrics for persistence -2h:
	RMSE: 11.072 | R2: 0.370 | BFE: 22.267
------------------------------------------------
Test storm number 99, from 2023-11-03 00:00:00 until 2023-11-12 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 25.002 | R2: 0.372 | BFE: 31.256
Metrics for LDi_CLF-1h:
	RMSE: 12.408 | R2: 0.845 | BFE: 21.349 | Inside 90%: 0.976
Metrics for LDi_CLF-2h:
	RMSE: 16.082 | R2: 0.740 | BFE: 32.405 | Inside 90%: 0.944
Metrics for persistence -1h:
	RMSE: 12.407 | R2: 0.831 | BFE: 23.749
Metrics for persistence -2h:
	RMSE: 18.077 | R2: 0.640 | BFE: 37.035
------------------------------------------------
Test storm number 100, from 2023-11-23 00:00:00 until 2023-12-08 00:00:00, number of batches: 4896
Shapes of the input tensors: torch.Size([4800, 96, 6]), torch.Size([4800, 96, 5]), torch.Size([4800, 1]), torch.Size([4800, 2, 4]), (4800, 2)
Metrics for SYM_H:
	RMSE: 25.427 | R2: -0.499 | BFE: 28.102
Metrics for LDi_CLF-1h:
	RMSE: 9.340 | R2: 0.798 | BFE: 15.520 | Inside 90%: 0.955
Metrics for LDi_CLF-2h:
	RMSE: 15.050 | R2: 0.475 | BFE: 21.621 | Inside 90%: 0.895
Metrics for persistence -1h:
	RMSE: 10.079 | R2: 0.763 | BFE: 18.263
Metrics for persistence -2h:
	RMSE: 13.145 | R2: 0.596 | BFE: 26.793
------------------------------------------------
Test storm number 101, from 2024-03-01 00:00:00 until 2024-03-09 00:00:00, number of batches: 2881
Shapes of the input tensors: torch.Size([2785, 96, 6]), torch.Size([2785, 96, 5]), torch.Size([2785, 1]), torch.Size([2785, 2, 4]), (2785, 2)
Metrics for SYM_H:
	RMSE: 20.225 | R2: -0.039 | BFE: 20.982
Metrics for LDi_CLF-1h:
	RMSE: 7.952 | R2: 0.839 | BFE: 14.310 | Inside 90%: 0.955
Metrics for LDi_CLF-2h:
	RMSE: 11.679 | R2: 0.653 | BFE: 18.588 | Inside 90%: 0.908
Metrics for persistence -1h:
	RMSE: 9.090 | R2: 0.753 | BFE: 22.048
Metrics for persistence -2h:
	RMSE: 12.825 | R2: 0.509 | BFE: 33.801
------------------------------------------------
Test storm number 102, from 2024-03-22 00:00:00 until 2024-03-30 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 21.946 | R2: -0.073 | BFE: 29.617
Metrics for LDi_CLF-1h:
	RMSE: 8.550 | R2: 0.837 | BFE: 18.639 | Inside 90%: 0.943
Metrics for LDi_CLF-2h:
	RMSE: 13.247 | R2: 0.609 | BFE: 35.779 | Inside 90%: 0.891
Metrics for persistence -1h:
	RMSE: 11.732 | R2: 0.717 | BFE: 23.468
Metrics for persistence -2h:
	RMSE: 15.231 | R2: 0.524 | BFE: 32.953
------------------------------------------------
Test storm number 103, from 2024-04-17 00:00:00 until 2024-04-25 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 20.012 | R2: -0.434 | BFE: 24.737
Metrics for LDi_CLF-1h:
	RMSE: 8.715 | R2: 0.728 | BFE: 8.349 | Inside 90%: 0.894
Metrics for LDi_CLF-2h:
	RMSE: 12.304 | R2: 0.458 | BFE: 9.611 | Inside 90%: 0.753
Metrics for persistence -1h:
	RMSE: 8.569 | R2: 0.755 | BFE: 13.566
Metrics for persistence -2h:
	RMSE: 10.736 | R2: 0.616 | BFE: 12.189
------------------------------------------------
Test storm number 104, from 2024-04-30 00:00:00 until 2024-05-24 00:00:00, number of batches: 7488
Shapes of the input tensors: torch.Size([7392, 96, 6]), torch.Size([7392, 96, 5]), torch.Size([7392, 1]), torch.Size([7392, 2, 4]), (7392, 2)
Metrics for SYM_H:
	RMSE: 44.245 | R2: -0.074 | BFE: 102.022
Metrics for LDi_CLF-1h:
	RMSE: 19.590 | R2: 0.789 | BFE: 66.692 | Inside 90%: 0.937
Metrics for LDi_CLF-2h:
	RMSE: 25.906 | R2: 0.632 | BFE: 75.280 | Inside 90%: 0.854
Metrics for persistence -1h:
	RMSE: 21.782 | R2: 0.724 | BFE: 70.036
Metrics for persistence -2h:
	RMSE: 27.963 | R2: 0.546 | BFE: 107.803
------------------------------------------------
Test storm number 105, from 2024-06-26 00:00:00 until 2024-07-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 33.508 | R2: -2.563 | BFE: 31.515
Metrics for LDi_CLF-1h:
	RMSE: 10.340 | R2: 0.661 | BFE: 18.689 | Inside 90%: 0.916
Metrics for LDi_CLF-2h:
	RMSE: 13.555 | R2: 0.417 | BFE: 16.377 | Inside 90%: 0.841
Metrics for persistence -1h:
	RMSE: 10.244 | R2: 0.646 | BFE: 26.063
Metrics for persistence -2h:
	RMSE: 11.957 | R2: 0.518 | BFE: 27.681
------------------------------------------------
Test storm number 106, from 2024-08-02 00:00:00 until 2024-08-19 00:00:00, number of batches: 5472
Shapes of the input tensors: torch.Size([5376, 96, 6]), torch.Size([5376, 96, 5]), torch.Size([5376, 1]), torch.Size([5376, 2, 4]), (5376, 2)
Metrics for SYM_H:
	RMSE: 25.926 | R2: 0.163 | BFE: 32.538
Metrics for LDi_CLF-1h:
	RMSE: 11.139 | R2: 0.845 | BFE: 17.091 | Inside 90%: 0.957
Metrics for LDi_CLF-2h:
	RMSE: 15.385 | R2: 0.705 | BFE: 26.059 | Inside 90%: 0.912
Metrics for persistence -1h:
	RMSE: 11.008 | R2: 0.835 | BFE: 19.544
Metrics for persistence -2h:
	RMSE: 13.520 | R2: 0.751 | BFE: 20.850
------------------------------------------------
Test storm number 107, from 2024-09-10 00:00:00 until 2024-09-23 00:00:00, number of batches: 4320
Shapes of the input tensors: torch.Size([4224, 96, 6]), torch.Size([4224, 96, 5]), torch.Size([4224, 1]), torch.Size([4224, 2, 4]), (4224, 2)
Metrics for SYM_H:
	RMSE: 28.152 | R2: -0.062 | BFE: 19.992
Metrics for LDi_CLF-1h:
	RMSE: 12.339 | R2: 0.796 | BFE: 16.161 | Inside 90%: 0.908
Metrics for LDi_CLF-2h:
	RMSE: 17.788 | R2: 0.576 | BFE: 25.681 | Inside 90%: 0.825
Metrics for persistence -1h:
	RMSE: 12.365 | R2: 0.795 | BFE: 21.097
Metrics for persistence -2h:
	RMSE: 16.575 | R2: 0.632 | BFE: 30.936
------------------------------------------------
Test storm number 108, from 2024-10-05 00:00:00 until 2024-10-17 00:00:00, number of batches: 4032
Shapes of the input tensors: torch.Size([3936, 96, 6]), torch.Size([3936, 96, 5]), torch.Size([3936, 1]), torch.Size([3936, 2, 4]), (3936, 2)
Metrics for SYM_H:
	RMSE: 32.478 | R2: 0.540 | BFE: 40.107
Metrics for LDi_CLF-1h:
	RMSE: 19.097 | R2: 0.841 | BFE: 39.032 | Inside 90%: 0.888
Metrics for LDi_CLF-2h:
	RMSE: 25.541 | R2: 0.716 | BFE: 52.178 | Inside 90%: 0.793
Metrics for persistence -1h:
	RMSE: 18.733 | R2: 0.833 | BFE: 41.315
Metrics for persistence -2h:
	RMSE: 23.998 | R2: 0.726 | BFE: 52.387
------------------------------------------------
Test storm number 109, from 2024-11-07 00:00:00 until 2024-11-15 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 18.980 | R2: 0.224 | BFE: 20.314
Metrics for LDi_CLF-1h:
	RMSE: 10.849 | R2: 0.746 | BFE: 17.983 | Inside 90%: 0.948
Metrics for LDi_CLF-2h:
	RMSE: 14.662 | R2: 0.537 | BFE: 18.696 | Inside 90%: 0.882
Metrics for persistence -1h:
	RMSE: 10.836 | R2: 0.715 | BFE: 18.929
Metrics for persistence -2h:
	RMSE: 14.429 | R2: 0.495 | BFE: 25.019
------------------------------------------------
Metrics for the MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,CLF,89,29.023,12.591,20.225,0.429,19.815001,31.101999,7.882,11.656,12.581,17.295,0.779,0.582,0.936,0.846
1,CLF,90,11.599,15.927,20.098,-0.875,10.888000,11.859000,7.056,9.527,9.776,12.311,0.556,0.296,0.917,0.877
2,CLF,91,51.787,21.559,30.035,-0.034,19.524000,27.134001,7.531,12.040,11.865,17.454,0.839,0.651,0.945,0.837
3,CLF,92,32.090,12.921,16.916,0.359,26.579000,33.106998,8.230,11.748,12.634,16.299,0.642,0.404,0.873,0.785
4,CLF,93,24.715,16.407,20.450,-0.138,13.680000,17.554001,6.421,9.360,9.131,12.003,0.773,0.608,0.969,0.938
5,CLF,94,19.697,26.323,28.229,-1.498,9.855000,17.781000,4.947,8.418,6.567,11.006,0.865,0.620,0.986,0.934
6,CLF,95,22.405,18.205,24.789,0.103,15.226000,21.454000,8.732,13.367,13.010,19.156,0.753,0.464,0.939,0.831
7,CLF,96,29.375,14.182,22.895,0.054,15.139000,18.035000,6.860,9.638,10.907,13.363,0.785,0.678,0.897,0.856
8,CLF,97,54.820,27.407,35.520,-0.632,27.681999,30.516001,8.731,12.350,12.929,16.783,0.784,0.636,0.891,0.754
9,CLF,98,17.530,10.245,16.614,-0.279,15.617000,25.833000,6.371,9.190,9.305,13.143,0.599,0.199,0.956,0.854
10,CLF,99,31.256,20.190,25.002,0.372,21.349001,32.404999,7.183,10.700,12.408,16.082,0.845,0.740,0.976,0.944
11,CLF,100,28.102,23.154,25.427,-0.499,15.520000,21.621000,6.093,9.467,9.340,15.050,0.798,0.475,0.955,0.895
12,CLF,101,20.982,17.141,20.225,-0.039,14.310000,18.587999,5.524,8.493,7.952,11.679,0.839,0.653,0.955,0.908
13,CLF,102,29.617,17.647,21.946,-0.073,18.639000,35.778999,5.712,8.766,8.550,13.247,0.837,0.609,0.943,0.891
14,CLF,103,24.737,15.718,20.012,-0.434,8.349000,9.611000,6.222,9.498,8.715,12.304,0.728,0.458,0.894,0.753
15,CLF,104,102.022,30.558,44.245,-0.074,66.692001,75.279999,9.340,13.290,19.590,25.906,0.789,0.632,0.937,0.854
16,CLF,105,31.515,29.963,33.508,-2.563,18.688999,16.377001,7.129,10.139,10.340,13.555,0.661,0.417,0.916,0.841
17,CLF,106,32.538,15.863,25.926,0.163,17.091000,26.059000,7.019,10.186,11.139,15.385,0.845,0.705,0.957,0.912
18,CLF,107,19.992,19.681,28.152,-0.062,16.160999,25.681999,7.847,11.827,12.339,17.788,0.796,0.576,0.908,0.825
19,CLF,108,40.107,20.015,32.478,0.540,39.032001,52.178001,10.417,14.752,19.097,25.541,0.841,0.716,0.888,0.793
20,CLF,109,20.314,15.660,18.980,0.224,17.983000,18.695999,7.353,10.628,10.849,14.662,0.746,0.537,0.948,0.882
21,CLF,Mean,32.106,19.112,25.318,-0.236,20.372000,26.983000,7.267,10.716,11.382,15.715,0.767,0.555,0.933,0.858
22,CLF,Global,73.670,19.979,28.088,0.064,64.436996,74.647003,7.460,10.966,12.653,17.308,0.810,0.645,0.933,0.859

Mean and global MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
21,CLF,Mean,32.106,19.112,25.318,-0.236,20.372000,26.983000,7.267,10.716,11.382,15.715,0.767,0.555,0.933,0.858
22,CLF,Global,73.670,19.979,28.088,0.064,64.436996,74.647003,7.460,10.966,12.653,17.308,0.810,0.645,0.933,0.859

           Station  BFE SYM-H  DTW SYM-H  RMSE SYM-H  R2 SYM_H
StormIndex
Mean           CLF     32.106     19.112      25.318    -0.236
Global         CLF     73.670     19.979      28.088     0.064
Metrics for persistence -2h:
	RMSE: 13.115 | R2: 0.774 | BFE: 66.489
Metrics for persistence -2h:
	RMSE: 17.000 | R2: 0.620 | BFE: 100.731
Diff BFE (SYM-H nowcast - LDi forecast 1h):
Total: 9.233
Diff BFE (SYM-H nowcast - LDi forecast 2h):
Total: -0.977

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,CLF,89,29.022701,12.591280,20.225471,0.428736,19.815281,31.102060,7.882171,11.656203,12.581303,17.294760,0.778950,0.582296,0.935596,0.845739
1,CLF,90,11.598647,15.927202,20.098200,-0.875462,10.888056,11.859143,7.056229,9.526742,9.775786,12.310779,0.556292,0.296337,0.917137,0.876790
2,CLF,91,51.786812,21.558681,30.034981,-0.034254,19.523720,27.133652,7.531140,12.039882,11.864594,17.453571,0.838609,0.650746,0.945336,0.837310
3,CLF,92,32.090188,12.920742,16.915661,0.358527,26.579252,33.106655,8.229828,11.748114,12.633847,16.299416,0.642174,0.404414,0.872885,0.785249
4,CLF,93,24.715146,16.406712,20.449997,-0.137736,13.679865,17.554382,6.421145,9.359586,9.131367,12.003187,0.773156,0.608034,0.969197,0.937527
5,CLF,94,19.697226,26.322950,28.228559,-1.498036,9.855026,17.781281,4.947400,8.418427,6.567156,11.005636,0.864800,0.620290,0.986117,0.933623
6,CLF,95,22.404838,18.205199,24.789005,0.102701,15.226352,21.453890,8.731922,13.367037,13.009989,19.156385,0.752843,0.464146,0.938681,0.831084
7,CLF,96,29.374508,14.181984,22.894989,0.053858,15.139376,18.035261,6.860385,9.637814,10.907060,13.362988,0.785271,0.677683,0.897030,0.856151
8,CLF,97,54.820490,27.406575,35.519718,-0.631544,27.681923,30.516241,8.730739,12.350303,12.928798,16.782640,0.783840,0.635766,0.890860,0.754339
9,CLF,98,17.530063,10.245236,16.614473,-0.279384,15.616583,25.833092,6.370857,9.190394,9.305398,13.142600,0.598674,0.199447,0.955748,0.853796
10,CLF,99,31.255916,20.189711,25.001732,0.371645,21.349094,32.404793,7.183467,10.699791,12.408024,16.081945,0.845236,0.740019,0.976475,0.943695
11,CLF,100,28.102395,23.153626,25.426905,-0.499397,15.520041,21.620684,6.092937,9.467366,9.339590,15.050385,0.797705,0.474679,0.954872,0.895163
12,CLF,101,20.981903,17.140573,20.224682,-0.039088,14.310339,18.587807,5.524170,8.493097,7.952024,11.679374,0.839363,0.653480,0.955315,0.908026
13,CLF,102,29.616871,17.646512,21.945900,-0.073128,18.638767,35.778900,5.711735,8.766345,8.549642,13.246655,0.837130,0.609018,0.943167,0.890672
14,CLF,103,24.737299,15.717783,20.012260,-0.433681,8.348531,9.610890,6.222141,9.497701,8.714866,12.304059,0.728117,0.458053,0.893709,0.752711
15,CLF,104,102.022334,30.557538,44.244659,-0.073772,66.691757,75.280357,9.340243,13.290014,19.590338,25.906483,0.789489,0.631865,0.937075,0.854332
16,CLF,105,31.514702,29.962768,33.507927,-2.562715,18.688828,16.377153,7.129499,10.138715,10.340316,13.555401,0.660724,0.416943,0.916269,0.840781
17,CLF,106,32.537522,15.863024,25.926121,0.162568,17.090517,26.058914,7.019126,10.185850,11.138812,15.384720,0.845420,0.705114,0.957117,0.911987
18,CLF,107,19.991647,19.681194,28.151882,-0.062195,16.161196,25.681499,7.846572,11.827269,12.338636,17.788200,0.795956,0.575915,0.907877,0.824833
19,CLF,108,40.107243,20.015467,32.478302,0.540425,39.032215,52.178333,10.417423,14.752236,19.096899,25.540617,0.841110,0.715795,0.888053,0.793463
20,CLF,109,20.314206,15.659601,18.980103,0.223769,17.983335,18.695568,7.353462,10.628218,10.849350,14.661707,0.746370,0.536806,0.947505,0.881562
21,CLF,Mean,32.105841,19.112112,25.317692,-0.236103,20.372385,26.983358,7.266790,10.716243,11.382085,15.714834,0.766725,0.555088,0.932668,0.857563
22,CLF,Global,73.669954,19.979334,28.087835,0.064327,64.437164,74.647003,7.459647,10.966128,12.652555,17.307835,0.810135,0.644718,0.933223,0.858612

Testing model RELDi
Evaluating for on station CLF
Test storm number 89, from 2017-09-06 00:00:00 until 2017-09-15 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 20.225 | R2: 0.429 | BFE: 29.023
Metrics for LDi_CLF-1h:
	RMSE: 12.581 | R2: 0.779 | BFE: 19.815 | Inside 90%: 0.936
Metrics for LDi_CLF-2h:
	RMSE: 17.295 | R2: 0.582 | BFE: 31.102 | Inside 90%: 0.846
Metrics for persistence -1h:
	RMSE: 14.432 | R2: 0.674 | BFE: 18.977
Metrics for persistence -2h:
	RMSE: 18.465 | R2: 0.466 | BFE: 23.340
------------------------------------------------
Test storm number 90, from 2017-09-26 00:00:00 until 2017-10-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 20.098 | R2: -0.875 | BFE: 11.599
Metrics for LDi_CLF-1h:
	RMSE: 9.776 | R2: 0.556 | BFE: 10.888 | Inside 90%: 0.917
Metrics for LDi_CLF-2h:
	RMSE: 12.311 | R2: 0.296 | BFE: 11.859 | Inside 90%: 0.877
Metrics for persistence -1h:
	RMSE: 9.469 | R2: 0.510 | BFE: 13.961
Metrics for persistence -2h:
	RMSE: 11.204 | R2: 0.314 | BFE: 14.256
------------------------------------------------
Test storm number 91, from 2018-08-24 00:00:00 until 2018-09-01 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 30.035 | R2: -0.034 | BFE: 51.787
Metrics for LDi_CLF-1h:
	RMSE: 11.865 | R2: 0.839 | BFE: 19.524 | Inside 90%: 0.945
Metrics for LDi_CLF-2h:
	RMSE: 17.454 | R2: 0.651 | BFE: 27.134 | Inside 90%: 0.837
Metrics for persistence -1h:
	RMSE: 11.264 | R2: 0.829 | BFE: 18.932
Metrics for persistence -2h:
	RMSE: 16.142 | R2: 0.649 | BFE: 36.578
------------------------------------------------
Test storm number 92, from 2021-11-02 00:00:00 until 2021-11-10 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 16.916 | R2: 0.359 | BFE: 32.090
Metrics for LDi_CLF-1h:
	RMSE: 12.634 | R2: 0.642 | BFE: 26.579 | Inside 90%: 0.873
Metrics for LDi_CLF-2h:
	RMSE: 16.299 | R2: 0.404 | BFE: 33.107 | Inside 90%: 0.785
Metrics for persistence -1h:
	RMSE: 12.431 | R2: 0.600 | BFE: 31.990
Metrics for persistence -2h:
	RMSE: 15.443 | R2: 0.383 | BFE: 34.379
------------------------------------------------
Test storm number 93, from 2022-01-12 00:00:00 until 2022-01-20 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 20.450 | R2: -0.138 | BFE: 24.715
Metrics for LDi_CLF-1h:
	RMSE: 9.131 | R2: 0.773 | BFE: 13.680 | Inside 90%: 0.969
Metrics for LDi_CLF-2h:
	RMSE: 12.003 | R2: 0.608 | BFE: 17.554 | Inside 90%: 0.938
Metrics for persistence -1h:
	RMSE: 9.321 | R2: 0.725 | BFE: 18.397
Metrics for persistence -2h:
	RMSE: 12.139 | R2: 0.534 | BFE: 23.588
------------------------------------------------
Test storm number 94, from 2022-11-05 00:00:00 until 2022-11-13 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 28.229 | R2: -1.498 | BFE: 19.697
Metrics for LDi_CLF-1h:
	RMSE: 6.567 | R2: 0.865 | BFE: 9.855 | Inside 90%: 0.986
Metrics for LDi_CLF-2h:
	RMSE: 11.006 | R2: 0.620 | BFE: 17.781 | Inside 90%: 0.934
Metrics for persistence -1h:
	RMSE: 6.958 | R2: 0.829 | BFE: 13.392
Metrics for persistence -2h:
	RMSE: 10.319 | R2: 0.625 | BFE: 24.063
------------------------------------------------
Test storm number 95, from 2023-02-25 00:00:00 until 2023-03-06 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 24.789 | R2: 0.103 | BFE: 22.405
Metrics for LDi_CLF-1h:
	RMSE: 13.010 | R2: 0.753 | BFE: 15.226 | Inside 90%: 0.939
Metrics for LDi_CLF-2h:
	RMSE: 19.156 | R2: 0.464 | BFE: 21.454 | Inside 90%: 0.831
Metrics for persistence -1h:
	RMSE: 13.588 | R2: 0.713 | BFE: 21.618
Metrics for persistence -2h:
	RMSE: 17.738 | R2: 0.510 | BFE: 29.059
------------------------------------------------
Test storm number 96, from 2023-03-21 00:00:00 until 2023-03-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 22.895 | R2: 0.054 | BFE: 29.375
Metrics for LDi_CLF-1h:
	RMSE: 10.907 | R2: 0.785 | BFE: 15.139 | Inside 90%: 0.897
Metrics for LDi_CLF-2h:
	RMSE: 13.363 | R2: 0.678 | BFE: 18.035 | Inside 90%: 0.856
Metrics for persistence -1h:
	RMSE: 11.475 | R2: 0.745 | BFE: 20.259
Metrics for persistence -2h:
	RMSE: 14.196 | R2: 0.610 | BFE: 21.866
------------------------------------------------
Test storm number 97, from 2023-04-21 00:00:00 until 2023-04-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 35.520 | R2: -0.632 | BFE: 54.820
Metrics for LDi_CLF-1h:
	RMSE: 12.929 | R2: 0.784 | BFE: 27.682 | Inside 90%: 0.891
Metrics for LDi_CLF-2h:
	RMSE: 16.783 | R2: 0.636 | BFE: 30.516 | Inside 90%: 0.754
Metrics for persistence -1h:
	RMSE: 13.426 | R2: 0.744 | BFE: 26.755
Metrics for persistence -2h:
	RMSE: 17.424 | R2: 0.569 | BFE: 41.232
------------------------------------------------
Test storm number 98, from 2023-08-03 00:00:00 until 2023-08-11 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 16.614 | R2: -0.279 | BFE: 17.530
Metrics for LDi_CLF-1h:
	RMSE: 9.305 | R2: 0.599 | BFE: 15.617 | Inside 90%: 0.956
Metrics for LDi_CLF-2h:
	RMSE: 13.143 | R2: 0.199 | BFE: 25.833 | Inside 90%: 0.854
Metrics for persistence -1h:
	RMSE: 8.662 | R2: 0.614 | BFE: 16.407
Metrics for persistence -2h:
	RMSE: 11.072 | R2: 0.370 | BFE: 22.267
------------------------------------------------
Test storm number 99, from 2023-11-03 00:00:00 until 2023-11-12 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 25.002 | R2: 0.372 | BFE: 31.256
Metrics for LDi_CLF-1h:
	RMSE: 12.408 | R2: 0.845 | BFE: 21.349 | Inside 90%: 0.976
Metrics for LDi_CLF-2h:
	RMSE: 16.082 | R2: 0.740 | BFE: 32.405 | Inside 90%: 0.944
Metrics for persistence -1h:
	RMSE: 12.407 | R2: 0.831 | BFE: 23.749
Metrics for persistence -2h:
	RMSE: 18.077 | R2: 0.640 | BFE: 37.035
------------------------------------------------
Test storm number 100, from 2023-11-23 00:00:00 until 2023-12-08 00:00:00, number of batches: 4896
Shapes of the input tensors: torch.Size([4800, 96, 6]), torch.Size([4800, 96, 5]), torch.Size([4800, 1]), torch.Size([4800, 2, 4]), (4800, 2)
Metrics for SYM_H:
	RMSE: 25.427 | R2: -0.499 | BFE: 28.102
Metrics for LDi_CLF-1h:
	RMSE: 9.340 | R2: 0.798 | BFE: 15.520 | Inside 90%: 0.955
Metrics for LDi_CLF-2h:
	RMSE: 15.050 | R2: 0.475 | BFE: 21.621 | Inside 90%: 0.895
Metrics for persistence -1h:
	RMSE: 10.079 | R2: 0.763 | BFE: 18.263
Metrics for persistence -2h:
	RMSE: 13.145 | R2: 0.596 | BFE: 26.793
------------------------------------------------
Test storm number 101, from 2024-03-01 00:00:00 until 2024-03-09 00:00:00, number of batches: 2881
Shapes of the input tensors: torch.Size([2785, 96, 6]), torch.Size([2785, 96, 5]), torch.Size([2785, 1]), torch.Size([2785, 2, 4]), (2785, 2)
Metrics for SYM_H:
	RMSE: 20.225 | R2: -0.039 | BFE: 20.982
Metrics for LDi_CLF-1h:
	RMSE: 7.952 | R2: 0.839 | BFE: 14.310 | Inside 90%: 0.955
Metrics for LDi_CLF-2h:
	RMSE: 11.679 | R2: 0.653 | BFE: 18.588 | Inside 90%: 0.908
Metrics for persistence -1h:
	RMSE: 9.090 | R2: 0.753 | BFE: 22.048
Metrics for persistence -2h:
	RMSE: 12.825 | R2: 0.509 | BFE: 33.801
------------------------------------------------
Test storm number 102, from 2024-03-22 00:00:00 until 2024-03-30 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 21.946 | R2: -0.073 | BFE: 29.617
Metrics for LDi_CLF-1h:
	RMSE: 8.550 | R2: 0.837 | BFE: 18.639 | Inside 90%: 0.943
Metrics for LDi_CLF-2h:
	RMSE: 13.247 | R2: 0.609 | BFE: 35.779 | Inside 90%: 0.891
Metrics for persistence -1h:
	RMSE: 11.732 | R2: 0.717 | BFE: 23.468
Metrics for persistence -2h:
	RMSE: 15.231 | R2: 0.524 | BFE: 32.953
------------------------------------------------
Test storm number 103, from 2024-04-17 00:00:00 until 2024-04-25 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 20.012 | R2: -0.434 | BFE: 24.737
Metrics for LDi_CLF-1h:
	RMSE: 8.715 | R2: 0.728 | BFE: 8.349 | Inside 90%: 0.894
Metrics for LDi_CLF-2h:
	RMSE: 12.304 | R2: 0.458 | BFE: 9.611 | Inside 90%: 0.753
Metrics for persistence -1h:
	RMSE: 8.569 | R2: 0.755 | BFE: 13.566
Metrics for persistence -2h:
	RMSE: 10.736 | R2: 0.616 | BFE: 12.189
------------------------------------------------
Test storm number 104, from 2024-04-30 00:00:00 until 2024-05-24 00:00:00, number of batches: 7488
Shapes of the input tensors: torch.Size([7392, 96, 6]), torch.Size([7392, 96, 5]), torch.Size([7392, 1]), torch.Size([7392, 2, 4]), (7392, 2)
Metrics for SYM_H:
	RMSE: 44.245 | R2: -0.074 | BFE: 102.022
Metrics for LDi_CLF-1h:
	RMSE: 19.590 | R2: 0.789 | BFE: 66.692 | Inside 90%: 0.937
Metrics for LDi_CLF-2h:
	RMSE: 25.906 | R2: 0.632 | BFE: 75.280 | Inside 90%: 0.854
Metrics for persistence -1h:
	RMSE: 21.782 | R2: 0.724 | BFE: 70.036
Metrics for persistence -2h:
	RMSE: 27.963 | R2: 0.546 | BFE: 107.803
------------------------------------------------
Test storm number 105, from 2024-06-26 00:00:00 until 2024-07-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 33.508 | R2: -2.563 | BFE: 31.515
Metrics for LDi_CLF-1h:
	RMSE: 10.340 | R2: 0.661 | BFE: 18.689 | Inside 90%: 0.916
Metrics for LDi_CLF-2h:
	RMSE: 13.555 | R2: 0.417 | BFE: 16.377 | Inside 90%: 0.841
Metrics for persistence -1h:
	RMSE: 10.244 | R2: 0.646 | BFE: 26.063
Metrics for persistence -2h:
	RMSE: 11.957 | R2: 0.518 | BFE: 27.681
------------------------------------------------
Test storm number 106, from 2024-08-02 00:00:00 until 2024-08-19 00:00:00, number of batches: 5472
Shapes of the input tensors: torch.Size([5376, 96, 6]), torch.Size([5376, 96, 5]), torch.Size([5376, 1]), torch.Size([5376, 2, 4]), (5376, 2)
Metrics for SYM_H:
	RMSE: 25.926 | R2: 0.163 | BFE: 32.538
Metrics for LDi_CLF-1h:
	RMSE: 11.139 | R2: 0.845 | BFE: 17.091 | Inside 90%: 0.957
Metrics for LDi_CLF-2h:
	RMSE: 15.385 | R2: 0.705 | BFE: 26.059 | Inside 90%: 0.912
Metrics for persistence -1h:
	RMSE: 11.008 | R2: 0.835 | BFE: 19.544
Metrics for persistence -2h:
	RMSE: 13.520 | R2: 0.751 | BFE: 20.850
------------------------------------------------
Test storm number 107, from 2024-09-10 00:00:00 until 2024-09-23 00:00:00, number of batches: 4320
Shapes of the input tensors: torch.Size([4224, 96, 6]), torch.Size([4224, 96, 5]), torch.Size([4224, 1]), torch.Size([4224, 2, 4]), (4224, 2)
Metrics for SYM_H:
	RMSE: 28.152 | R2: -0.062 | BFE: 19.992
Metrics for LDi_CLF-1h:
	RMSE: 12.339 | R2: 0.796 | BFE: 16.161 | Inside 90%: 0.908
Metrics for LDi_CLF-2h:
	RMSE: 17.788 | R2: 0.576 | BFE: 25.681 | Inside 90%: 0.825
Metrics for persistence -1h:
	RMSE: 12.365 | R2: 0.795 | BFE: 21.097
Metrics for persistence -2h:
	RMSE: 16.575 | R2: 0.632 | BFE: 30.936
------------------------------------------------
Test storm number 108, from 2024-10-05 00:00:00 until 2024-10-17 00:00:00, number of batches: 4032
Shapes of the input tensors: torch.Size([3936, 96, 6]), torch.Size([3936, 96, 5]), torch.Size([3936, 1]), torch.Size([3936, 2, 4]), (3936, 2)
Metrics for SYM_H:
	RMSE: 32.478 | R2: 0.540 | BFE: 40.107
Metrics for LDi_CLF-1h:
	RMSE: 19.097 | R2: 0.841 | BFE: 39.032 | Inside 90%: 0.888
Metrics for LDi_CLF-2h:
	RMSE: 25.541 | R2: 0.716 | BFE: 52.178 | Inside 90%: 0.793
Metrics for persistence -1h:
	RMSE: 18.733 | R2: 0.833 | BFE: 41.315
Metrics for persistence -2h:
	RMSE: 23.998 | R2: 0.726 | BFE: 52.387
------------------------------------------------
Test storm number 109, from 2024-11-07 00:00:00 until 2024-11-15 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 18.980 | R2: 0.224 | BFE: 20.314
Metrics for LDi_CLF-1h:
	RMSE: 10.849 | R2: 0.746 | BFE: 17.983 | Inside 90%: 0.948
Metrics for LDi_CLF-2h:
	RMSE: 14.662 | R2: 0.537 | BFE: 18.696 | Inside 90%: 0.882
Metrics for persistence -1h:
	RMSE: 10.836 | R2: 0.715 | BFE: 18.929
Metrics for persistence -2h:
	RMSE: 14.429 | R2: 0.495 | BFE: 25.019
------------------------------------------------
Metrics for the MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,CLF,89,29.023,12.591,20.225,0.429,19.815001,31.101999,7.882,11.656,12.581,17.295,0.779,0.582,0.936,0.846
1,CLF,90,11.599,15.927,20.098,-0.875,10.888000,11.859000,7.056,9.527,9.776,12.311,0.556,0.296,0.917,0.877
2,CLF,91,51.787,21.559,30.035,-0.034,19.524000,27.134001,7.531,12.040,11.865,17.454,0.839,0.651,0.945,0.837
3,CLF,92,32.090,12.921,16.916,0.359,26.579000,33.106998,8.230,11.748,12.634,16.299,0.642,0.404,0.873,0.785
4,CLF,93,24.715,16.407,20.450,-0.138,13.680000,17.554001,6.421,9.360,9.131,12.003,0.773,0.608,0.969,0.938
5,CLF,94,19.697,26.323,28.229,-1.498,9.855000,17.781000,4.947,8.418,6.567,11.006,0.865,0.620,0.986,0.934
6,CLF,95,22.405,18.205,24.789,0.103,15.226000,21.454000,8.732,13.367,13.010,19.156,0.753,0.464,0.939,0.831
7,CLF,96,29.375,14.182,22.895,0.054,15.139000,18.035000,6.860,9.638,10.907,13.363,0.785,0.678,0.897,0.856
8,CLF,97,54.820,27.407,35.520,-0.632,27.681999,30.516001,8.731,12.350,12.929,16.783,0.784,0.636,0.891,0.754
9,CLF,98,17.530,10.245,16.614,-0.279,15.617000,25.833000,6.371,9.190,9.305,13.143,0.599,0.199,0.956,0.854
10,CLF,99,31.256,20.190,25.002,0.372,21.349001,32.404999,7.183,10.700,12.408,16.082,0.845,0.740,0.976,0.944
11,CLF,100,28.102,23.154,25.427,-0.499,15.520000,21.621000,6.093,9.467,9.340,15.050,0.798,0.475,0.955,0.895
12,CLF,101,20.982,17.141,20.225,-0.039,14.310000,18.587999,5.524,8.493,7.952,11.679,0.839,0.653,0.955,0.908
13,CLF,102,29.617,17.647,21.946,-0.073,18.639000,35.778999,5.712,8.766,8.550,13.247,0.837,0.609,0.943,0.891
14,CLF,103,24.737,15.718,20.012,-0.434,8.349000,9.611000,6.222,9.498,8.715,12.304,0.728,0.458,0.894,0.753
15,CLF,104,102.022,30.558,44.245,-0.074,66.692001,75.279999,9.340,13.290,19.590,25.906,0.789,0.632,0.937,0.854
16,CLF,105,31.515,29.963,33.508,-2.563,18.688999,16.377001,7.129,10.139,10.340,13.555,0.661,0.417,0.916,0.841
17,CLF,106,32.538,15.863,25.926,0.163,17.091000,26.059000,7.019,10.186,11.139,15.385,0.845,0.705,0.957,0.912
18,CLF,107,19.992,19.681,28.152,-0.062,16.160999,25.681999,7.847,11.827,12.339,17.788,0.796,0.576,0.908,0.825
19,CLF,108,40.107,20.015,32.478,0.540,39.032001,52.178001,10.417,14.752,19.097,25.541,0.841,0.716,0.888,0.793
20,CLF,109,20.314,15.660,18.980,0.224,17.983000,18.695999,7.353,10.628,10.849,14.662,0.746,0.537,0.948,0.882
21,CLF,Mean,32.106,19.112,25.318,-0.236,20.372000,26.983000,7.267,10.716,11.382,15.715,0.767,0.555,0.933,0.858
22,CLF,Global,73.670,19.979,28.088,0.064,64.436996,74.647003,7.460,10.966,12.653,17.308,0.810,0.645,0.933,0.859

Mean and global MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
21,CLF,Mean,32.106,19.112,25.318,-0.236,20.372000,26.983000,7.267,10.716,11.382,15.715,0.767,0.555,0.933,0.858
22,CLF,Global,73.670,19.979,28.088,0.064,64.436996,74.647003,7.460,10.966,12.653,17.308,0.810,0.645,0.933,0.859

           Station  BFE SYM-H  DTW SYM-H  RMSE SYM-H  R2 SYM_H
StormIndex
Mean           CLF     32.106     19.112      25.318    -0.236
Global         CLF     73.670     19.979      28.088     0.064
Metrics for persistence -2h:
	RMSE: 13.115 | R2: 0.774 | BFE: 66.489
Metrics for persistence -2h:
	RMSE: 17.000 | R2: 0.620 | BFE: 100.731
Diff BFE (SYM-H nowcast - LDi forecast 1h):
Total: 9.233
Diff BFE (SYM-H nowcast - LDi forecast 2h):
Total: -0.977

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,CLF,89,29.022701,12.591280,20.225471,0.428736,19.815281,31.102060,7.882171,11.656203,12.581303,17.294760,0.778950,0.582296,0.935596,0.845739
1,CLF,90,11.598647,15.927202,20.098200,-0.875462,10.888056,11.859143,7.056229,9.526742,9.775786,12.310779,0.556292,0.296337,0.917137,0.876790
2,CLF,91,51.786812,21.558681,30.034981,-0.034254,19.523720,27.133652,7.531140,12.039882,11.864594,17.453571,0.838609,0.650746,0.945336,0.837310
3,CLF,92,32.090188,12.920742,16.915661,0.358527,26.579252,33.106655,8.229828,11.748114,12.633847,16.299416,0.642174,0.404414,0.872885,0.785249
4,CLF,93,24.715146,16.406712,20.449997,-0.137736,13.679865,17.554382,6.421145,9.359586,9.131367,12.003187,0.773156,0.608034,0.969197,0.937527
5,CLF,94,19.697226,26.322950,28.228559,-1.498036,9.855026,17.781281,4.947400,8.418427,6.567156,11.005636,0.864800,0.620290,0.986117,0.933623
6,CLF,95,22.404838,18.205199,24.789005,0.102701,15.226352,21.453890,8.731922,13.367037,13.009989,19.156385,0.752843,0.464146,0.938681,0.831084
7,CLF,96,29.374508,14.181984,22.894989,0.053858,15.139376,18.035261,6.860385,9.637814,10.907060,13.362988,0.785271,0.677683,0.897030,0.856151
8,CLF,97,54.820490,27.406575,35.519718,-0.631544,27.681923,30.516241,8.730739,12.350303,12.928798,16.782640,0.783840,0.635766,0.890860,0.754339
9,CLF,98,17.530063,10.245236,16.614473,-0.279384,15.616583,25.833092,6.370857,9.190394,9.305398,13.142600,0.598674,0.199447,0.955748,0.853796
10,CLF,99,31.255916,20.189711,25.001732,0.371645,21.349094,32.404793,7.183467,10.699791,12.408024,16.081945,0.845236,0.740019,0.976475,0.943695
11,CLF,100,28.102395,23.153626,25.426905,-0.499397,15.520041,21.620684,6.092937,9.467366,9.339590,15.050385,0.797705,0.474679,0.954872,0.895163
12,CLF,101,20.981903,17.140573,20.224682,-0.039088,14.310339,18.587807,5.524170,8.493097,7.952024,11.679374,0.839363,0.653480,0.955315,0.908026
13,CLF,102,29.616871,17.646512,21.945900,-0.073128,18.638767,35.778900,5.711735,8.766345,8.549642,13.246655,0.837130,0.609018,0.943167,0.890672
14,CLF,103,24.737299,15.717783,20.012260,-0.433681,8.348531,9.610890,6.222141,9.497701,8.714866,12.304059,0.728117,0.458053,0.893709,0.752711
15,CLF,104,102.022334,30.557538,44.244659,-0.073772,66.691757,75.280357,9.340243,13.290014,19.590338,25.906483,0.789489,0.631865,0.937075,0.854332
16,CLF,105,31.514702,29.962768,33.507927,-2.562715,18.688828,16.377153,7.129499,10.138715,10.340316,13.555401,0.660724,0.416943,0.916269,0.840781
17,CLF,106,32.537522,15.863024,25.926121,0.162568,17.090517,26.058914,7.019126,10.185850,11.138812,15.384720,0.845420,0.705114,0.957117,0.911987
18,CLF,107,19.991647,19.681194,28.151882,-0.062195,16.161196,25.681499,7.846572,11.827269,12.338636,17.788200,0.795956,0.575915,0.907877,0.824833
19,CLF,108,40.107243,20.015467,32.478302,0.540425,39.032215,52.178333,10.417423,14.752236,19.096899,25.540617,0.841110,0.715795,0.888053,0.793463
20,CLF,109,20.314206,15.659601,18.980103,0.223769,17.983335,18.695568,7.353462,10.628218,10.849350,14.661707,0.746370,0.536806,0.947505,0.881562
21,CLF,Mean,32.105841,19.112112,25.317692,-0.236103,20.372385,26.983358,7.266790,10.716243,11.382085,15.714834,0.766725,0.555088,0.932668,0.857563
22,CLF,Global,73.669954,19.979334,28.087835,0.064327,64.437164,74.647003,7.459647,10.966128,12.652555,17.307835,0.810135,0.644718,0.933223,0.858612

In [ ]:
station = constants.STATIONS[3]
color = "magenta"

str_return, metrics_station, sum_df_station = test_on_station(
    station, color, model, same_color=True
)
str_summary += str_return
sum_dfs_stations.append(sum_df_station)
summary_df.loc[len(summary_df)] = metrics_station

color = constants.COLOR_STATIONS[station]
_, _, _ = test_on_station(station, color, model, same_color=False)

Testing model RELDi
Evaluating for on station TUC
Test storm number 89, from 2017-09-06 00:00:00 until 2017-09-15 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 14.876 | R2: 0.785 | BFE: 27.377
Metrics for LDi_TUC-1h:
	RMSE: 14.237 | R2: 0.803 | BFE: 24.439 | Inside 90%: 0.914
Metrics for LDi_TUC-2h:
	RMSE: 21.635 | R2: 0.545 | BFE: 40.388 | Inside 90%: 0.804
Metrics for persistence -1h:
	RMSE: 16.256 | R2: 0.710 | BFE: 29.966
Metrics for persistence -2h:
	RMSE: 21.567 | R2: 0.490 | BFE: 35.063
------------------------------------------------
Test storm number 90, from 2017-09-26 00:00:00 until 2017-10-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 15.174 | R2: 0.343 | BFE: 18.354
Metrics for LDi_TUC-1h:
	RMSE: 11.046 | R2: 0.652 | BFE: 14.391 | Inside 90%: 0.908
Metrics for LDi_TUC-2h:
	RMSE: 13.499 | R2: 0.480 | BFE: 12.627 | Inside 90%: 0.837
Metrics for persistence -1h:
	RMSE: 10.813 | R2: 0.624 | BFE: 16.321
Metrics for persistence -2h:
	RMSE: 12.633 | R2: 0.486 | BFE: 18.153
------------------------------------------------
Test storm number 91, from 2018-08-24 00:00:00 until 2018-09-01 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 19.670 | R2: 0.636 | BFE: 26.054
Metrics for LDi_TUC-1h:
	RMSE: 8.990 | R2: 0.924 | BFE: 9.840 | Inside 90%: 0.953
Metrics for LDi_TUC-2h:
	RMSE: 13.431 | R2: 0.830 | BFE: 15.406 | Inside 90%: 0.843
Metrics for persistence -1h:
	RMSE: 9.868 | R2: 0.893 | BFE: 15.942
Metrics for persistence -2h:
	RMSE: 14.632 | R2: 0.765 | BFE: 25.134
------------------------------------------------
Test storm number 92, from 2021-11-02 00:00:00 until 2021-11-10 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 18.021 | R2: 0.200 | BFE: 40.312
Metrics for LDi_TUC-1h:
	RMSE: 11.850 | R2: 0.654 | BFE: 33.561 | Inside 90%: 0.886
Metrics for LDi_TUC-2h:
	RMSE: 17.892 | R2: 0.211 | BFE: 57.998 | Inside 90%: 0.782
Metrics for persistence -1h:
	RMSE: 13.093 | R2: 0.529 | BFE: 36.587
Metrics for persistence -2h:
	RMSE: 16.628 | R2: 0.240 | BFE: 45.760
------------------------------------------------
Test storm number 93, from 2022-01-12 00:00:00 until 2022-01-20 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 18.357 | R2: 0.221 | BFE: 13.520
Metrics for LDi_TUC-1h:
	RMSE: 8.082 | R2: 0.849 | BFE: 9.607 | Inside 90%: 0.974
Metrics for LDi_TUC-2h:
	RMSE: 11.723 | R2: 0.682 | BFE: 11.927 | Inside 90%: 0.953
Metrics for persistence -1h:
	RMSE: 8.394 | R2: 0.812 | BFE: 13.290
Metrics for persistence -2h:
	RMSE: 10.749 | R2: 0.692 | BFE: 14.410
------------------------------------------------
Test storm number 94, from 2022-11-05 00:00:00 until 2022-11-13 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 29.452 | R2: -1.617 | BFE: 32.468
Metrics for LDi_TUC-1h:
	RMSE: 7.599 | R2: 0.826 | BFE: 7.582 | Inside 90%: 0.938
Metrics for LDi_TUC-2h:
	RMSE: 11.869 | R2: 0.575 | BFE: 10.704 | Inside 90%: 0.784
Metrics for persistence -1h:
	RMSE: 7.486 | R2: 0.828 | BFE: 8.548
Metrics for persistence -2h:
	RMSE: 10.634 | R2: 0.652 | BFE: 10.914
------------------------------------------------
Test storm number 95, from 2023-02-25 00:00:00 until 2023-03-06 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 23.831 | R2: 0.299 | BFE: 20.286
Metrics for LDi_TUC-1h:
	RMSE: 13.464 | R2: 0.776 | BFE: 15.744 | Inside 90%: 0.895
Metrics for LDi_TUC-2h:
	RMSE: 18.322 | R2: 0.586 | BFE: 18.662 | Inside 90%: 0.788
Metrics for persistence -1h:
	RMSE: 14.588 | R2: 0.716 | BFE: 19.917
Metrics for persistence -2h:
	RMSE: 18.396 | R2: 0.548 | BFE: 25.007
------------------------------------------------
Test storm number 96, from 2023-03-21 00:00:00 until 2023-03-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 16.795 | R2: 0.808 | BFE: 24.614
Metrics for LDi_TUC-1h:
	RMSE: 12.201 | R2: 0.899 | BFE: 19.324 | Inside 90%: 0.909
Metrics for LDi_TUC-2h:
	RMSE: 15.508 | R2: 0.836 | BFE: 24.774 | Inside 90%: 0.796
Metrics for persistence -1h:
	RMSE: 12.684 | R2: 0.874 | BFE: 20.663
Metrics for persistence -2h:
	RMSE: 16.760 | R2: 0.779 | BFE: 30.267
------------------------------------------------
Test storm number 97, from 2023-04-21 00:00:00 until 2023-04-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 30.900 | R2: 0.164 | BFE: 39.197
Metrics for LDi_TUC-1h:
	RMSE: 12.853 | R2: 0.855 | BFE: 19.197 | Inside 90%: 0.882
Metrics for LDi_TUC-2h:
	RMSE: 18.149 | R2: 0.712 | BFE: 24.765 | Inside 90%: 0.763
Metrics for persistence -1h:
	RMSE: 13.254 | R2: 0.829 | BFE: 23.666
Metrics for persistence -2h:
	RMSE: 18.509 | R2: 0.667 | BFE: 33.470
------------------------------------------------
Test storm number 98, from 2023-08-03 00:00:00 until 2023-08-11 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 12.404 | R2: 0.572 | BFE: 16.930
Metrics for LDi_TUC-1h:
	RMSE: 10.551 | R2: 0.690 | BFE: 19.230 | Inside 90%: 0.917
Metrics for LDi_TUC-2h:
	RMSE: 14.185 | R2: 0.440 | BFE: 20.191 | Inside 90%: 0.818
Metrics for persistence -1h:
	RMSE: 10.175 | R2: 0.691 | BFE: 18.787
Metrics for persistence -2h:
	RMSE: 14.464 | R2: 0.376 | BFE: 25.633
------------------------------------------------
Test storm number 99, from 2023-11-03 00:00:00 until 2023-11-12 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 21.468 | R2: 0.535 | BFE: 22.767
Metrics for LDi_TUC-1h:
	RMSE: 8.927 | R2: 0.920 | BFE: 9.705 | Inside 90%: 0.984
Metrics for LDi_TUC-2h:
	RMSE: 12.900 | R2: 0.832 | BFE: 14.770 | Inside 90%: 0.955
Metrics for persistence -1h:
	RMSE: 10.582 | R2: 0.882 | BFE: 12.967
Metrics for persistence -2h:
	RMSE: 13.872 | R2: 0.798 | BFE: 18.710
------------------------------------------------
Test storm number 100, from 2023-11-23 00:00:00 until 2023-12-08 00:00:00, number of batches: 4896
Shapes of the input tensors: torch.Size([4800, 96, 6]), torch.Size([4800, 96, 5]), torch.Size([4800, 1]), torch.Size([4800, 2, 4]), (4800, 2)
Metrics for SYM_H:
	RMSE: 23.050 | R2: -0.271 | BFE: 22.982
Metrics for LDi_TUC-1h:
	RMSE: 8.217 | R2: 0.838 | BFE: 10.991 | Inside 90%: 0.959
Metrics for LDi_TUC-2h:
	RMSE: 12.912 | R2: 0.601 | BFE: 15.736 | Inside 90%: 0.877
Metrics for persistence -1h:
	RMSE: 9.049 | R2: 0.815 | BFE: 15.144
Metrics for persistence -2h:
	RMSE: 12.261 | R2: 0.661 | BFE: 21.495
------------------------------------------------
Test storm number 101, from 2024-03-01 00:00:00 until 2024-03-09 00:00:00, number of batches: 2881
Shapes of the input tensors: torch.Size([2785, 96, 6]), torch.Size([2785, 96, 5]), torch.Size([2785, 1]), torch.Size([2785, 2, 4]), (2785, 2)
Metrics for SYM_H:
	RMSE: 15.295 | R2: 0.349 | BFE: 20.249
Metrics for LDi_TUC-1h:
	RMSE: 8.047 | R2: 0.820 | BFE: 12.829 | Inside 90%: 0.956
Metrics for LDi_TUC-2h:
	RMSE: 11.889 | R2: 0.607 | BFE: 15.082 | Inside 90%: 0.856
Metrics for persistence -1h:
	RMSE: 8.934 | R2: 0.757 | BFE: 15.032
Metrics for persistence -2h:
	RMSE: 11.881 | R2: 0.570 | BFE: 21.570
------------------------------------------------
Test storm number 102, from 2024-03-22 00:00:00 until 2024-03-30 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 15.875 | R2: 0.720 | BFE: 32.308
Metrics for LDi_TUC-1h:
	RMSE: 20.294 | R2: 0.543 | BFE: 61.824 | Inside 90%: 0.880
Metrics for LDi_TUC-2h:
	RMSE: 24.388 | R2: 0.340 | BFE: 77.089 | Inside 90%: 0.772
Metrics for persistence -1h:
	RMSE: 20.370 | R2: 0.548 | BFE: 50.353
Metrics for persistence -2h:
	RMSE: 23.553 | R2: 0.395 | BFE: 58.318
------------------------------------------------
Test storm number 103, from 2024-04-17 00:00:00 until 2024-04-25 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 15.775 | R2: 0.378 | BFE: 15.124
Metrics for LDi_TUC-1h:
	RMSE: 8.952 | R2: 0.800 | BFE: 11.638 | Inside 90%: 0.884
Metrics for LDi_TUC-2h:
	RMSE: 12.088 | R2: 0.635 | BFE: 13.338 | Inside 90%: 0.777
Metrics for persistence -1h:
	RMSE: 9.361 | R2: 0.784 | BFE: 11.502
Metrics for persistence -2h:
	RMSE: 12.222 | R2: 0.632 | BFE: 17.502
------------------------------------------------
Test storm number 104, from 2024-04-30 00:00:00 until 2024-05-24 00:00:00, number of batches: 7488
Shapes of the input tensors: torch.Size([7392, 96, 6]), torch.Size([7392, 96, 5]), torch.Size([7392, 1]), torch.Size([7392, 2, 4]), (7392, 2)
Metrics for SYM_H:
	RMSE: 28.816 | R2: 0.712 | BFE: 50.454
Metrics for LDi_TUC-1h:
	RMSE: 16.511 | R2: 0.906 | BFE: 35.345 | Inside 90%: 0.931
Metrics for LDi_TUC-2h:
	RMSE: 20.162 | R2: 0.859 | BFE: 31.660 | Inside 90%: 0.865
Metrics for persistence -1h:
	RMSE: 18.511 | R2: 0.874 | BFE: 45.486
Metrics for persistence -2h:
	RMSE: 23.322 | R2: 0.800 | BFE: 54.508
------------------------------------------------
Test storm number 105, from 2024-06-26 00:00:00 until 2024-07-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 26.577 | R2: -0.454 | BFE: 20.509
Metrics for LDi_TUC-1h:
	RMSE: 9.444 | R2: 0.816 | BFE: 7.908 | Inside 90%: 0.919
Metrics for LDi_TUC-2h:
	RMSE: 14.026 | R2: 0.595 | BFE: 11.983 | Inside 90%: 0.822
Metrics for persistence -1h:
	RMSE: 9.460 | R2: 0.806 | BFE: 9.574
Metrics for persistence -2h:
	RMSE: 13.734 | R2: 0.590 | BFE: 16.160
------------------------------------------------
Test storm number 106, from 2024-08-02 00:00:00 until 2024-08-19 00:00:00, number of batches: 5472
Shapes of the input tensors: torch.Size([5376, 96, 6]), torch.Size([5376, 96, 5]), torch.Size([5376, 1]), torch.Size([5376, 2, 4]), (5376, 2)
Metrics for SYM_H:
	RMSE: 17.721 | R2: 0.763 | BFE: 15.764
Metrics for LDi_TUC-1h:
	RMSE: 11.891 | R2: 0.893 | BFE: 17.079 | Inside 90%: 0.940
Metrics for LDi_TUC-2h:
	RMSE: 17.275 | R2: 0.775 | BFE: 25.356 | Inside 90%: 0.865
Metrics for persistence -1h:
	RMSE: 13.644 | R2: 0.847 | BFE: 18.137
Metrics for persistence -2h:
	RMSE: 18.009 | R2: 0.733 | BFE: 25.462
------------------------------------------------
Test storm number 107, from 2024-09-10 00:00:00 until 2024-09-23 00:00:00, number of batches: 4320
Shapes of the input tensors: torch.Size([4224, 96, 6]), torch.Size([4224, 96, 5]), torch.Size([4224, 1]), torch.Size([4224, 2, 4]), (4224, 2)
Metrics for SYM_H:
	RMSE: 18.695 | R2: 0.663 | BFE: 16.158
Metrics for LDi_TUC-1h:
	RMSE: 11.297 | R2: 0.877 | BFE: 12.111 | Inside 90%: 0.890
Metrics for LDi_TUC-2h:
	RMSE: 15.865 | R2: 0.757 | BFE: 25.266 | Inside 90%: 0.815
Metrics for persistence -1h:
	RMSE: 12.617 | R2: 0.841 | BFE: 14.496
Metrics for persistence -2h:
	RMSE: 16.846 | R2: 0.716 | BFE: 22.623
------------------------------------------------
Test storm number 108, from 2024-10-05 00:00:00 until 2024-10-17 00:00:00, number of batches: 4032
Shapes of the input tensors: torch.Size([3936, 96, 6]), torch.Size([3936, 96, 5]), torch.Size([3936, 1]), torch.Size([3936, 2, 4]), (3936, 2)
Metrics for SYM_H:
	RMSE: 22.799 | R2: 0.838 | BFE: 26.397
Metrics for LDi_TUC-1h:
	RMSE: 21.607 | R2: 0.854 | BFE: 32.443 | Inside 90%: 0.859
Metrics for LDi_TUC-2h:
	RMSE: 25.486 | R2: 0.797 | BFE: 43.071 | Inside 90%: 0.763
Metrics for persistence -1h:
	RMSE: 21.173 | R2: 0.850 | BFE: 37.722
Metrics for persistence -2h:
	RMSE: 25.102 | R2: 0.789 | BFE: 42.224
------------------------------------------------
Test storm number 109, from 2024-11-07 00:00:00 until 2024-11-15 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 19.580 | R2: 0.116 | BFE: 18.378
Metrics for LDi_TUC-1h:
	RMSE: 9.039 | R2: 0.812 | BFE: 9.044 | Inside 90%: 0.956
Metrics for LDi_TUC-2h:
	RMSE: 14.255 | R2: 0.532 | BFE: 12.736 | Inside 90%: 0.818
Metrics for persistence -1h:
	RMSE: 8.692 | R2: 0.800 | BFE: 11.807
Metrics for persistence -2h:
	RMSE: 12.449 | R2: 0.590 | BFE: 16.794
------------------------------------------------
Metrics for the MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,TUC,89,27.377,9.472,14.876,0.785,24.438999,40.388000,8.773,13.715,14.237,21.635,0.803,0.545,0.914,0.804
1,TUC,90,18.354,12.391,15.174,0.343,14.391000,12.627000,7.339,9.964,11.046,13.499,0.652,0.480,0.908,0.837
2,TUC,91,26.054,16.061,19.670,0.636,9.840000,15.406000,6.211,9.649,8.990,13.431,0.924,0.830,0.953,0.843
3,TUC,92,40.312,12.424,18.021,0.200,33.561001,57.998001,7.436,11.480,11.850,17.892,0.654,0.211,0.886,0.782
4,TUC,93,13.520,16.684,18.357,0.221,9.607000,11.927000,5.590,8.407,8.082,11.723,0.849,0.682,0.974,0.953
5,TUC,94,32.468,25.959,29.452,-1.617,7.582000,10.704000,5.656,9.229,7.599,11.869,0.826,0.575,0.938,0.784
6,TUC,95,20.286,17.243,23.831,0.299,15.744000,18.662001,8.874,12.765,13.464,18.322,0.776,0.586,0.895,0.788
7,TUC,96,24.614,11.846,16.795,0.808,19.323999,24.774000,7.131,10.703,12.201,15.508,0.899,0.836,0.909,0.796
8,TUC,97,39.197,27.122,30.900,0.164,19.197001,24.764999,8.871,12.645,12.853,18.149,0.855,0.712,0.882,0.763
9,TUC,98,16.930,9.662,12.404,0.572,19.230000,20.191000,6.575,10.029,10.551,14.185,0.690,0.440,0.917,0.818
10,TUC,99,22.767,17.217,21.468,0.535,9.705000,14.770000,6.025,9.350,8.927,12.900,0.920,0.832,0.984,0.955
11,TUC,100,22.982,19.500,23.050,-0.271,10.991000,15.736000,5.587,9.070,8.217,12.912,0.838,0.601,0.959,0.877
12,TUC,101,20.249,11.642,15.295,0.349,12.829000,15.082000,5.674,8.979,8.047,11.889,0.820,0.607,0.956,0.856
13,TUC,102,32.308,11.988,15.875,0.720,61.824001,77.088997,8.995,12.824,20.294,24.388,0.543,0.340,0.880,0.772
14,TUC,103,15.124,12.204,15.775,0.378,11.638000,13.338000,6.343,8.875,8.952,12.088,0.800,0.635,0.884,0.777
15,TUC,104,50.454,20.908,28.816,0.712,35.345001,31.660000,8.356,11.657,16.511,20.162,0.906,0.859,0.931,0.865
16,TUC,105,20.509,22.875,26.577,-0.454,7.908000,11.983000,6.539,10.052,9.444,14.026,0.816,0.595,0.919,0.822
17,TUC,106,15.764,11.447,17.721,0.763,17.079000,25.356001,7.297,11.046,11.891,17.275,0.893,0.775,0.940,0.865
18,TUC,107,16.158,13.469,18.695,0.663,12.111000,25.266001,7.839,10.932,11.297,15.865,0.877,0.757,0.890,0.815
19,TUC,108,26.397,15.119,22.799,0.838,32.443001,43.070999,10.697,14.372,21.607,25.486,0.854,0.797,0.859,0.763
20,TUC,109,18.378,15.654,19.580,0.116,9.044000,12.736000,6.809,10.582,9.039,14.255,0.812,0.532,0.956,0.818
21,TUC,Mean,24.772,15.757,20.244,0.322,18.754000,24.930000,7.267,10.777,11.671,16.069,0.810,0.630,0.921,0.826
22,TUC,Global,38.910,16.037,21.552,0.617,37.391998,37.348999,7.388,10.894,12.727,16.995,0.867,0.762,0.922,0.831

Mean and global MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
21,TUC,Mean,24.772,15.757,20.244,0.322,18.754000,24.930000,7.267,10.777,11.671,16.069,0.810,0.630,0.921,0.826
22,TUC,Global,38.910,16.037,21.552,0.617,37.391998,37.348999,7.388,10.894,12.727,16.995,0.867,0.762,0.922,0.831

           Station  BFE SYM-H  DTW SYM-H  RMSE SYM-H  R2 SYM_H
StormIndex
Mean           TUC     24.772     15.757      20.244     0.322
Global         TUC     38.910     16.037      21.552     0.617
Metrics for persistence -2h:
	RMSE: 13.454 | R2: 0.834 | BFE: 46.376
Metrics for persistence -2h:
	RMSE: 17.293 | R2: 0.727 | BFE: 54.432
Diff BFE (SYM-H nowcast - LDi forecast 1h):
Total: 1.519
Diff BFE (SYM-H nowcast - LDi forecast 2h):
Total: 1.561

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,TUC,89,27.377050,9.471643,14.876406,0.785007,24.438717,40.387577,8.772961,13.715310,14.236505,21.634676,0.803104,0.545295,0.914385,0.804474
1,TUC,90,18.353788,12.390967,15.174352,0.342907,14.390879,12.626810,7.338869,9.963865,11.046460,13.498765,0.651781,0.480011,0.907592,0.837310
2,TUC,91,26.053659,16.061210,19.670437,0.635996,9.839642,15.405602,6.211276,9.648616,8.990067,13.430912,0.923967,0.830297,0.953145,0.843384
3,TUC,92,40.312241,12.424412,18.020643,0.199571,33.560577,57.998047,7.436033,11.480058,11.850436,17.891600,0.653861,0.210994,0.885900,0.782213
4,TUC,93,13.520003,16.683705,18.357494,0.221382,9.606622,11.927454,5.589860,8.407442,8.081972,11.723221,0.849085,0.682465,0.974403,0.952711
5,TUC,94,32.467527,25.958712,29.452412,-1.617054,7.581527,10.703839,5.655639,9.228788,7.598772,11.869062,0.825796,0.574985,0.937961,0.783948
6,TUC,95,20.286297,17.243247,23.830587,0.299382,15.743934,18.661596,8.874243,12.765076,13.463799,18.321762,0.776361,0.585861,0.895488,0.788276
7,TUC,96,24.613627,11.846109,16.795305,0.807783,19.324160,24.773848,7.131021,10.702872,12.201094,15.507909,0.898559,0.836121,0.909371,0.795989
8,TUC,97,39.197167,27.121824,30.899662,0.164186,19.197283,24.765493,8.871183,12.644924,12.853127,18.148508,0.855383,0.711674,0.881990,0.762823
9,TUC,98,16.929598,9.661774,12.404138,0.571647,19.230019,20.190666,6.574748,10.029345,10.550587,14.184690,0.690099,0.439844,0.916703,0.817787
10,TUC,99,22.767046,17.216883,21.468472,0.534923,9.704654,14.770046,6.025352,9.350177,8.926722,12.900033,0.919591,0.832079,0.983803,0.955264
11,TUC,100,22.982412,19.500444,23.050289,-0.271079,10.990955,15.736353,5.587271,9.070461,8.216905,12.911979,0.838476,0.601154,0.959037,0.877343
12,TUC,101,20.249168,11.641605,15.295468,0.349175,12.828777,15.081844,5.673926,8.978836,8.046952,11.888529,0.819864,0.606817,0.956182,0.855531
13,TUC,102,32.308121,11.988464,15.874864,0.720298,61.823772,77.088974,8.995190,12.824004,20.293776,24.387589,0.542911,0.339895,0.880260,0.772234
14,TUC,103,15.124350,12.204486,15.774924,0.377722,11.638461,13.337858,6.342524,8.875140,8.951898,12.087634,0.799608,0.634631,0.884165,0.777440
15,TUC,104,50.454424,20.908446,28.816219,0.712266,35.345291,31.660498,8.355798,11.656872,16.511284,20.161699,0.905533,0.859145,0.930566,0.865182
16,TUC,105,20.509217,22.874994,26.577087,-0.453931,7.907685,11.983071,6.538597,10.051511,9.443903,14.025873,0.816417,0.595062,0.918872,0.822126
17,TUC,106,15.763643,11.446739,17.721489,0.763129,17.078911,25.356152,7.296626,11.046168,11.891048,17.274992,0.893352,0.774915,0.939759,0.864815
18,TUC,107,16.158155,13.469081,18.694721,0.663083,12.111027,25.266016,7.838639,10.932060,11.296673,15.865476,0.876977,0.757344,0.889720,0.814953
19,TUC,108,26.397350,15.118539,22.798651,0.837768,32.443344,43.070873,10.696894,14.371733,21.607061,25.486446,0.854284,0.797262,0.858837,0.762800
20,TUC,109,18.378283,15.654273,19.579536,0.116470,9.043596,12.736159,6.809256,10.581586,9.038752,14.254571,0.811707,0.531699,0.956182,0.818221
21,TUC,Mean,24.771577,15.756550,20.244436,0.321935,18.753803,24.929941,7.267424,10.777374,11.671323,16.069330,0.809844,0.629883,0.920682,0.826420
22,TUC,Global,38.910315,16.036721,21.551609,0.617346,37.391785,37.349285,7.388071,10.894087,12.726727,16.995157,0.866562,0.762043,0.921512,0.831022

Testing model RELDi
Evaluating for on station TUC
Test storm number 89, from 2017-09-06 00:00:00 until 2017-09-15 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 14.876 | R2: 0.785 | BFE: 27.377
Metrics for LDi_TUC-1h:
	RMSE: 14.237 | R2: 0.803 | BFE: 24.439 | Inside 90%: 0.914
Metrics for LDi_TUC-2h:
	RMSE: 21.635 | R2: 0.545 | BFE: 40.388 | Inside 90%: 0.804
Metrics for persistence -1h:
	RMSE: 16.256 | R2: 0.710 | BFE: 29.966
Metrics for persistence -2h:
	RMSE: 21.567 | R2: 0.490 | BFE: 35.063
------------------------------------------------
Test storm number 90, from 2017-09-26 00:00:00 until 2017-10-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 15.174 | R2: 0.343 | BFE: 18.354
Metrics for LDi_TUC-1h:
	RMSE: 11.046 | R2: 0.652 | BFE: 14.391 | Inside 90%: 0.908
Metrics for LDi_TUC-2h:
	RMSE: 13.499 | R2: 0.480 | BFE: 12.627 | Inside 90%: 0.837
Metrics for persistence -1h:
	RMSE: 10.813 | R2: 0.624 | BFE: 16.321
Metrics for persistence -2h:
	RMSE: 12.633 | R2: 0.486 | BFE: 18.153
------------------------------------------------
Test storm number 91, from 2018-08-24 00:00:00 until 2018-09-01 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 19.670 | R2: 0.636 | BFE: 26.054
Metrics for LDi_TUC-1h:
	RMSE: 8.990 | R2: 0.924 | BFE: 9.840 | Inside 90%: 0.953
Metrics for LDi_TUC-2h:
	RMSE: 13.431 | R2: 0.830 | BFE: 15.406 | Inside 90%: 0.843
Metrics for persistence -1h:
	RMSE: 9.868 | R2: 0.893 | BFE: 15.942
Metrics for persistence -2h:
	RMSE: 14.632 | R2: 0.765 | BFE: 25.134
------------------------------------------------
Test storm number 92, from 2021-11-02 00:00:00 until 2021-11-10 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 18.021 | R2: 0.200 | BFE: 40.312
Metrics for LDi_TUC-1h:
	RMSE: 11.850 | R2: 0.654 | BFE: 33.561 | Inside 90%: 0.886
Metrics for LDi_TUC-2h:
	RMSE: 17.892 | R2: 0.211 | BFE: 57.998 | Inside 90%: 0.782
Metrics for persistence -1h:
	RMSE: 13.093 | R2: 0.529 | BFE: 36.587
Metrics for persistence -2h:
	RMSE: 16.628 | R2: 0.240 | BFE: 45.760
------------------------------------------------
Test storm number 93, from 2022-01-12 00:00:00 until 2022-01-20 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 18.357 | R2: 0.221 | BFE: 13.520
Metrics for LDi_TUC-1h:
	RMSE: 8.082 | R2: 0.849 | BFE: 9.607 | Inside 90%: 0.974
Metrics for LDi_TUC-2h:
	RMSE: 11.723 | R2: 0.682 | BFE: 11.927 | Inside 90%: 0.953
Metrics for persistence -1h:
	RMSE: 8.394 | R2: 0.812 | BFE: 13.290
Metrics for persistence -2h:
	RMSE: 10.749 | R2: 0.692 | BFE: 14.410
------------------------------------------------
Test storm number 94, from 2022-11-05 00:00:00 until 2022-11-13 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 29.452 | R2: -1.617 | BFE: 32.468
Metrics for LDi_TUC-1h:
	RMSE: 7.599 | R2: 0.826 | BFE: 7.582 | Inside 90%: 0.938
Metrics for LDi_TUC-2h:
	RMSE: 11.869 | R2: 0.575 | BFE: 10.704 | Inside 90%: 0.784
Metrics for persistence -1h:
	RMSE: 7.486 | R2: 0.828 | BFE: 8.548
Metrics for persistence -2h:
	RMSE: 10.634 | R2: 0.652 | BFE: 10.914
------------------------------------------------
Test storm number 95, from 2023-02-25 00:00:00 until 2023-03-06 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 23.831 | R2: 0.299 | BFE: 20.286
Metrics for LDi_TUC-1h:
	RMSE: 13.464 | R2: 0.776 | BFE: 15.744 | Inside 90%: 0.895
Metrics for LDi_TUC-2h:
	RMSE: 18.322 | R2: 0.586 | BFE: 18.662 | Inside 90%: 0.788
Metrics for persistence -1h:
	RMSE: 14.588 | R2: 0.716 | BFE: 19.917
Metrics for persistence -2h:
	RMSE: 18.396 | R2: 0.548 | BFE: 25.007
------------------------------------------------
Test storm number 96, from 2023-03-21 00:00:00 until 2023-03-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 16.795 | R2: 0.808 | BFE: 24.614
Metrics for LDi_TUC-1h:
	RMSE: 12.201 | R2: 0.899 | BFE: 19.324 | Inside 90%: 0.909
Metrics for LDi_TUC-2h:
	RMSE: 15.508 | R2: 0.836 | BFE: 24.774 | Inside 90%: 0.796
Metrics for persistence -1h:
	RMSE: 12.684 | R2: 0.874 | BFE: 20.663
Metrics for persistence -2h:
	RMSE: 16.760 | R2: 0.779 | BFE: 30.267
------------------------------------------------
Test storm number 97, from 2023-04-21 00:00:00 until 2023-04-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 30.900 | R2: 0.164 | BFE: 39.197
Metrics for LDi_TUC-1h:
	RMSE: 12.853 | R2: 0.855 | BFE: 19.197 | Inside 90%: 0.882
Metrics for LDi_TUC-2h:
	RMSE: 18.149 | R2: 0.712 | BFE: 24.765 | Inside 90%: 0.763
Metrics for persistence -1h:
	RMSE: 13.254 | R2: 0.829 | BFE: 23.666
Metrics for persistence -2h:
	RMSE: 18.509 | R2: 0.667 | BFE: 33.470
------------------------------------------------
Test storm number 98, from 2023-08-03 00:00:00 until 2023-08-11 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 12.404 | R2: 0.572 | BFE: 16.930
Metrics for LDi_TUC-1h:
	RMSE: 10.551 | R2: 0.690 | BFE: 19.230 | Inside 90%: 0.917
Metrics for LDi_TUC-2h:
	RMSE: 14.185 | R2: 0.440 | BFE: 20.191 | Inside 90%: 0.818
Metrics for persistence -1h:
	RMSE: 10.175 | R2: 0.691 | BFE: 18.787
Metrics for persistence -2h:
	RMSE: 14.464 | R2: 0.376 | BFE: 25.633
------------------------------------------------
Test storm number 99, from 2023-11-03 00:00:00 until 2023-11-12 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 21.468 | R2: 0.535 | BFE: 22.767
Metrics for LDi_TUC-1h:
	RMSE: 8.927 | R2: 0.920 | BFE: 9.705 | Inside 90%: 0.984
Metrics for LDi_TUC-2h:
	RMSE: 12.900 | R2: 0.832 | BFE: 14.770 | Inside 90%: 0.955
Metrics for persistence -1h:
	RMSE: 10.582 | R2: 0.882 | BFE: 12.967
Metrics for persistence -2h:
	RMSE: 13.872 | R2: 0.798 | BFE: 18.710
------------------------------------------------
Test storm number 100, from 2023-11-23 00:00:00 until 2023-12-08 00:00:00, number of batches: 4896
Shapes of the input tensors: torch.Size([4800, 96, 6]), torch.Size([4800, 96, 5]), torch.Size([4800, 1]), torch.Size([4800, 2, 4]), (4800, 2)
Metrics for SYM_H:
	RMSE: 23.050 | R2: -0.271 | BFE: 22.982
Metrics for LDi_TUC-1h:
	RMSE: 8.217 | R2: 0.838 | BFE: 10.991 | Inside 90%: 0.959
Metrics for LDi_TUC-2h:
	RMSE: 12.912 | R2: 0.601 | BFE: 15.736 | Inside 90%: 0.877
Metrics for persistence -1h:
	RMSE: 9.049 | R2: 0.815 | BFE: 15.144
Metrics for persistence -2h:
	RMSE: 12.261 | R2: 0.661 | BFE: 21.495
------------------------------------------------
Test storm number 101, from 2024-03-01 00:00:00 until 2024-03-09 00:00:00, number of batches: 2881
Shapes of the input tensors: torch.Size([2785, 96, 6]), torch.Size([2785, 96, 5]), torch.Size([2785, 1]), torch.Size([2785, 2, 4]), (2785, 2)
Metrics for SYM_H:
	RMSE: 15.295 | R2: 0.349 | BFE: 20.249
Metrics for LDi_TUC-1h:
	RMSE: 8.047 | R2: 0.820 | BFE: 12.829 | Inside 90%: 0.956
Metrics for LDi_TUC-2h:
	RMSE: 11.889 | R2: 0.607 | BFE: 15.082 | Inside 90%: 0.856
Metrics for persistence -1h:
	RMSE: 8.934 | R2: 0.757 | BFE: 15.032
Metrics for persistence -2h:
	RMSE: 11.881 | R2: 0.570 | BFE: 21.570
------------------------------------------------
Test storm number 102, from 2024-03-22 00:00:00 until 2024-03-30 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 15.875 | R2: 0.720 | BFE: 32.308
Metrics for LDi_TUC-1h:
	RMSE: 20.294 | R2: 0.543 | BFE: 61.824 | Inside 90%: 0.880
Metrics for LDi_TUC-2h:
	RMSE: 24.388 | R2: 0.340 | BFE: 77.089 | Inside 90%: 0.772
Metrics for persistence -1h:
	RMSE: 20.370 | R2: 0.548 | BFE: 50.353
Metrics for persistence -2h:
	RMSE: 23.553 | R2: 0.395 | BFE: 58.318
------------------------------------------------
Test storm number 103, from 2024-04-17 00:00:00 until 2024-04-25 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 15.775 | R2: 0.378 | BFE: 15.124
Metrics for LDi_TUC-1h:
	RMSE: 8.952 | R2: 0.800 | BFE: 11.638 | Inside 90%: 0.884
Metrics for LDi_TUC-2h:
	RMSE: 12.088 | R2: 0.635 | BFE: 13.338 | Inside 90%: 0.777
Metrics for persistence -1h:
	RMSE: 9.361 | R2: 0.784 | BFE: 11.502
Metrics for persistence -2h:
	RMSE: 12.222 | R2: 0.632 | BFE: 17.502
------------------------------------------------
Test storm number 104, from 2024-04-30 00:00:00 until 2024-05-24 00:00:00, number of batches: 7488
Shapes of the input tensors: torch.Size([7392, 96, 6]), torch.Size([7392, 96, 5]), torch.Size([7392, 1]), torch.Size([7392, 2, 4]), (7392, 2)
Metrics for SYM_H:
	RMSE: 28.816 | R2: 0.712 | BFE: 50.454
Metrics for LDi_TUC-1h:
	RMSE: 16.511 | R2: 0.906 | BFE: 35.345 | Inside 90%: 0.931
Metrics for LDi_TUC-2h:
	RMSE: 20.162 | R2: 0.859 | BFE: 31.660 | Inside 90%: 0.865
Metrics for persistence -1h:
	RMSE: 18.511 | R2: 0.874 | BFE: 45.486
Metrics for persistence -2h:
	RMSE: 23.322 | R2: 0.800 | BFE: 54.508
------------------------------------------------
Test storm number 105, from 2024-06-26 00:00:00 until 2024-07-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 26.577 | R2: -0.454 | BFE: 20.509
Metrics for LDi_TUC-1h:
	RMSE: 9.444 | R2: 0.816 | BFE: 7.908 | Inside 90%: 0.919
Metrics for LDi_TUC-2h:
	RMSE: 14.026 | R2: 0.595 | BFE: 11.983 | Inside 90%: 0.822
Metrics for persistence -1h:
	RMSE: 9.460 | R2: 0.806 | BFE: 9.574
Metrics for persistence -2h:
	RMSE: 13.734 | R2: 0.590 | BFE: 16.160
------------------------------------------------
Test storm number 106, from 2024-08-02 00:00:00 until 2024-08-19 00:00:00, number of batches: 5472
Shapes of the input tensors: torch.Size([5376, 96, 6]), torch.Size([5376, 96, 5]), torch.Size([5376, 1]), torch.Size([5376, 2, 4]), (5376, 2)
Metrics for SYM_H:
	RMSE: 17.721 | R2: 0.763 | BFE: 15.764
Metrics for LDi_TUC-1h:
	RMSE: 11.891 | R2: 0.893 | BFE: 17.079 | Inside 90%: 0.940
Metrics for LDi_TUC-2h:
	RMSE: 17.275 | R2: 0.775 | BFE: 25.356 | Inside 90%: 0.865
Metrics for persistence -1h:
	RMSE: 13.644 | R2: 0.847 | BFE: 18.137
Metrics for persistence -2h:
	RMSE: 18.009 | R2: 0.733 | BFE: 25.462
------------------------------------------------
Test storm number 107, from 2024-09-10 00:00:00 until 2024-09-23 00:00:00, number of batches: 4320
Shapes of the input tensors: torch.Size([4224, 96, 6]), torch.Size([4224, 96, 5]), torch.Size([4224, 1]), torch.Size([4224, 2, 4]), (4224, 2)
Metrics for SYM_H:
	RMSE: 18.695 | R2: 0.663 | BFE: 16.158
Metrics for LDi_TUC-1h:
	RMSE: 11.297 | R2: 0.877 | BFE: 12.111 | Inside 90%: 0.890
Metrics for LDi_TUC-2h:
	RMSE: 15.865 | R2: 0.757 | BFE: 25.266 | Inside 90%: 0.815
Metrics for persistence -1h:
	RMSE: 12.617 | R2: 0.841 | BFE: 14.496
Metrics for persistence -2h:
	RMSE: 16.846 | R2: 0.716 | BFE: 22.623
------------------------------------------------
Test storm number 108, from 2024-10-05 00:00:00 until 2024-10-17 00:00:00, number of batches: 4032
Shapes of the input tensors: torch.Size([3936, 96, 6]), torch.Size([3936, 96, 5]), torch.Size([3936, 1]), torch.Size([3936, 2, 4]), (3936, 2)
Metrics for SYM_H:
	RMSE: 22.799 | R2: 0.838 | BFE: 26.397
Metrics for LDi_TUC-1h:
	RMSE: 21.607 | R2: 0.854 | BFE: 32.443 | Inside 90%: 0.859
Metrics for LDi_TUC-2h:
	RMSE: 25.486 | R2: 0.797 | BFE: 43.071 | Inside 90%: 0.763
Metrics for persistence -1h:
	RMSE: 21.173 | R2: 0.850 | BFE: 37.722
Metrics for persistence -2h:
	RMSE: 25.102 | R2: 0.789 | BFE: 42.224
------------------------------------------------
Test storm number 109, from 2024-11-07 00:00:00 until 2024-11-15 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 19.580 | R2: 0.116 | BFE: 18.378
Metrics for LDi_TUC-1h:
	RMSE: 9.039 | R2: 0.812 | BFE: 9.044 | Inside 90%: 0.956
Metrics for LDi_TUC-2h:
	RMSE: 14.255 | R2: 0.532 | BFE: 12.736 | Inside 90%: 0.818
Metrics for persistence -1h:
	RMSE: 8.692 | R2: 0.800 | BFE: 11.807
Metrics for persistence -2h:
	RMSE: 12.449 | R2: 0.590 | BFE: 16.794
------------------------------------------------
Metrics for the MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,TUC,89,27.377,9.472,14.876,0.785,24.438999,40.388000,8.773,13.715,14.237,21.635,0.803,0.545,0.914,0.804
1,TUC,90,18.354,12.391,15.174,0.343,14.391000,12.627000,7.339,9.964,11.046,13.499,0.652,0.480,0.908,0.837
2,TUC,91,26.054,16.061,19.670,0.636,9.840000,15.406000,6.211,9.649,8.990,13.431,0.924,0.830,0.953,0.843
3,TUC,92,40.312,12.424,18.021,0.200,33.561001,57.998001,7.436,11.480,11.850,17.892,0.654,0.211,0.886,0.782
4,TUC,93,13.520,16.684,18.357,0.221,9.607000,11.927000,5.590,8.407,8.082,11.723,0.849,0.682,0.974,0.953
5,TUC,94,32.468,25.959,29.452,-1.617,7.582000,10.704000,5.656,9.229,7.599,11.869,0.826,0.575,0.938,0.784
6,TUC,95,20.286,17.243,23.831,0.299,15.744000,18.662001,8.874,12.765,13.464,18.322,0.776,0.586,0.895,0.788
7,TUC,96,24.614,11.846,16.795,0.808,19.323999,24.774000,7.131,10.703,12.201,15.508,0.899,0.836,0.909,0.796
8,TUC,97,39.197,27.122,30.900,0.164,19.197001,24.764999,8.871,12.645,12.853,18.149,0.855,0.712,0.882,0.763
9,TUC,98,16.930,9.662,12.404,0.572,19.230000,20.191000,6.575,10.029,10.551,14.185,0.690,0.440,0.917,0.818
10,TUC,99,22.767,17.217,21.468,0.535,9.705000,14.770000,6.025,9.350,8.927,12.900,0.920,0.832,0.984,0.955
11,TUC,100,22.982,19.500,23.050,-0.271,10.991000,15.736000,5.587,9.070,8.217,12.912,0.838,0.601,0.959,0.877
12,TUC,101,20.249,11.642,15.295,0.349,12.829000,15.082000,5.674,8.979,8.047,11.889,0.820,0.607,0.956,0.856
13,TUC,102,32.308,11.988,15.875,0.720,61.824001,77.088997,8.995,12.824,20.294,24.388,0.543,0.340,0.880,0.772
14,TUC,103,15.124,12.204,15.775,0.378,11.638000,13.338000,6.343,8.875,8.952,12.088,0.800,0.635,0.884,0.777
15,TUC,104,50.454,20.908,28.816,0.712,35.345001,31.660000,8.356,11.657,16.511,20.162,0.906,0.859,0.931,0.865
16,TUC,105,20.509,22.875,26.577,-0.454,7.908000,11.983000,6.539,10.052,9.444,14.026,0.816,0.595,0.919,0.822
17,TUC,106,15.764,11.447,17.721,0.763,17.079000,25.356001,7.297,11.046,11.891,17.275,0.893,0.775,0.940,0.865
18,TUC,107,16.158,13.469,18.695,0.663,12.111000,25.266001,7.839,10.932,11.297,15.865,0.877,0.757,0.890,0.815
19,TUC,108,26.397,15.119,22.799,0.838,32.443001,43.070999,10.697,14.372,21.607,25.486,0.854,0.797,0.859,0.763
20,TUC,109,18.378,15.654,19.580,0.116,9.044000,12.736000,6.809,10.582,9.039,14.255,0.812,0.532,0.956,0.818
21,TUC,Mean,24.772,15.757,20.244,0.322,18.754000,24.930000,7.267,10.777,11.671,16.069,0.810,0.630,0.921,0.826
22,TUC,Global,38.910,16.037,21.552,0.617,37.391998,37.348999,7.388,10.894,12.727,16.995,0.867,0.762,0.922,0.831

Mean and global MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
21,TUC,Mean,24.772,15.757,20.244,0.322,18.754000,24.930000,7.267,10.777,11.671,16.069,0.810,0.630,0.921,0.826
22,TUC,Global,38.910,16.037,21.552,0.617,37.391998,37.348999,7.388,10.894,12.727,16.995,0.867,0.762,0.922,0.831

           Station  BFE SYM-H  DTW SYM-H  RMSE SYM-H  R2 SYM_H
StormIndex
Mean           TUC     24.772     15.757      20.244     0.322
Global         TUC     38.910     16.037      21.552     0.617
Metrics for persistence -2h:
	RMSE: 13.454 | R2: 0.834 | BFE: 46.376
Metrics for persistence -2h:
	RMSE: 17.293 | R2: 0.727 | BFE: 54.432
Diff BFE (SYM-H nowcast - LDi forecast 1h):
Total: 1.519
Diff BFE (SYM-H nowcast - LDi forecast 2h):
Total: 1.561

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,TUC,89,27.377050,9.471643,14.876406,0.785007,24.438717,40.387577,8.772961,13.715310,14.236505,21.634676,0.803104,0.545295,0.914385,0.804474
1,TUC,90,18.353788,12.390967,15.174352,0.342907,14.390879,12.626810,7.338869,9.963865,11.046460,13.498765,0.651781,0.480011,0.907592,0.837310
2,TUC,91,26.053659,16.061210,19.670437,0.635996,9.839642,15.405602,6.211276,9.648616,8.990067,13.430912,0.923967,0.830297,0.953145,0.843384
3,TUC,92,40.312241,12.424412,18.020643,0.199571,33.560577,57.998047,7.436033,11.480058,11.850436,17.891600,0.653861,0.210994,0.885900,0.782213
4,TUC,93,13.520003,16.683705,18.357494,0.221382,9.606622,11.927454,5.589860,8.407442,8.081972,11.723221,0.849085,0.682465,0.974403,0.952711
5,TUC,94,32.467527,25.958712,29.452412,-1.617054,7.581527,10.703839,5.655639,9.228788,7.598772,11.869062,0.825796,0.574985,0.937961,0.783948
6,TUC,95,20.286297,17.243247,23.830587,0.299382,15.743934,18.661596,8.874243,12.765076,13.463799,18.321762,0.776361,0.585861,0.895488,0.788276
7,TUC,96,24.613627,11.846109,16.795305,0.807783,19.324160,24.773848,7.131021,10.702872,12.201094,15.507909,0.898559,0.836121,0.909371,0.795989
8,TUC,97,39.197167,27.121824,30.899662,0.164186,19.197283,24.765493,8.871183,12.644924,12.853127,18.148508,0.855383,0.711674,0.881990,0.762823
9,TUC,98,16.929598,9.661774,12.404138,0.571647,19.230019,20.190666,6.574748,10.029345,10.550587,14.184690,0.690099,0.439844,0.916703,0.817787
10,TUC,99,22.767046,17.216883,21.468472,0.534923,9.704654,14.770046,6.025352,9.350177,8.926722,12.900033,0.919591,0.832079,0.983803,0.955264
11,TUC,100,22.982412,19.500444,23.050289,-0.271079,10.990955,15.736353,5.587271,9.070461,8.216905,12.911979,0.838476,0.601154,0.959037,0.877343
12,TUC,101,20.249168,11.641605,15.295468,0.349175,12.828777,15.081844,5.673926,8.978836,8.046952,11.888529,0.819864,0.606817,0.956182,0.855531
13,TUC,102,32.308121,11.988464,15.874864,0.720298,61.823772,77.088974,8.995190,12.824004,20.293776,24.387589,0.542911,0.339895,0.880260,0.772234
14,TUC,103,15.124350,12.204486,15.774924,0.377722,11.638461,13.337858,6.342524,8.875140,8.951898,12.087634,0.799608,0.634631,0.884165,0.777440
15,TUC,104,50.454424,20.908446,28.816219,0.712266,35.345291,31.660498,8.355798,11.656872,16.511284,20.161699,0.905533,0.859145,0.930566,0.865182
16,TUC,105,20.509217,22.874994,26.577087,-0.453931,7.907685,11.983071,6.538597,10.051511,9.443903,14.025873,0.816417,0.595062,0.918872,0.822126
17,TUC,106,15.763643,11.446739,17.721489,0.763129,17.078911,25.356152,7.296626,11.046168,11.891048,17.274992,0.893352,0.774915,0.939759,0.864815
18,TUC,107,16.158155,13.469081,18.694721,0.663083,12.111027,25.266016,7.838639,10.932060,11.296673,15.865476,0.876977,0.757344,0.889720,0.814953
19,TUC,108,26.397350,15.118539,22.798651,0.837768,32.443344,43.070873,10.696894,14.371733,21.607061,25.486446,0.854284,0.797262,0.858837,0.762800
20,TUC,109,18.378283,15.654273,19.579536,0.116470,9.043596,12.736159,6.809256,10.581586,9.038752,14.254571,0.811707,0.531699,0.956182,0.818221
21,TUC,Mean,24.771577,15.756550,20.244436,0.321935,18.753803,24.929941,7.267424,10.777374,11.671323,16.069330,0.809844,0.629883,0.920682,0.826420
22,TUC,Global,38.910315,16.036721,21.551609,0.617346,37.391785,37.349285,7.388071,10.894087,12.726727,16.995157,0.866562,0.762043,0.921512,0.831022

In [ ]:
station = constants.STATIONS[4]
color = "magenta"

str_return, metrics_station, sum_df_station = test_on_station(
    station, color, model, same_color=True
)
str_summary += str_return
sum_dfs_stations.append(sum_df_station)
summary_df.loc[len(summary_df)] = metrics_station

color = constants.COLOR_STATIONS[station]
_, _, _ = test_on_station(station, color, model, same_color=False)

Testing model RELDi
Evaluating for on station HON
Test storm number 89, from 2017-09-06 00:00:00 until 2017-09-15 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 16.418 | R2: 0.750 | BFE: 24.087
Metrics for LDi_HON-1h:
	RMSE: 9.055 | R2: 0.924 | BFE: 12.554 | Inside 90%: 0.975
Metrics for LDi_HON-2h:
	RMSE: 17.200 | R2: 0.725 | BFE: 31.393 | Inside 90%: 0.912
Metrics for persistence -1h:
	RMSE: 11.338 | R2: 0.867 | BFE: 14.989
Metrics for persistence -2h:
	RMSE: 17.664 | R2: 0.677 | BFE: 22.460
------------------------------------------------
Test storm number 90, from 2017-09-26 00:00:00 until 2017-10-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 13.824 | R2: 0.612 | BFE: 18.365
Metrics for LDi_HON-1h:
	RMSE: 7.591 | R2: 0.883 | BFE: 10.085 | Inside 90%: 0.948
Metrics for LDi_HON-2h:
	RMSE: 11.421 | R2: 0.735 | BFE: 11.990 | Inside 90%: 0.858
Metrics for persistence -1h:
	RMSE: 7.789 | R2: 0.864 | BFE: 8.479
Metrics for persistence -2h:
	RMSE: 11.071 | R2: 0.725 | BFE: 15.139
------------------------------------------------
Test storm number 91, from 2018-08-24 00:00:00 until 2018-09-01 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 11.817 | R2: 0.907 | BFE: 21.361
Metrics for LDi_HON-1h:
	RMSE: 9.426 | R2: 0.941 | BFE: 14.090 | Inside 90%: 0.964
Metrics for LDi_HON-2h:
	RMSE: 12.890 | R2: 0.890 | BFE: 21.999 | Inside 90%: 0.902
Metrics for persistence -1h:
	RMSE: 10.459 | R2: 0.915 | BFE: 24.220
Metrics for persistence -2h:
	RMSE: 15.663 | R2: 0.809 | BFE: 34.098
------------------------------------------------
Test storm number 92, from 2021-11-02 00:00:00 until 2021-11-10 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 11.334 | R2: 0.648 | BFE: 14.682
Metrics for LDi_HON-1h:
	RMSE: 8.125 | R2: 0.819 | BFE: 12.744 | Inside 90%: 0.926
Metrics for LDi_HON-2h:
	RMSE: 14.463 | R2: 0.427 | BFE: 21.947 | Inside 90%: 0.836
Metrics for persistence -1h:
	RMSE: 9.204 | R2: 0.755 | BFE: 17.623
Metrics for persistence -2h:
	RMSE: 12.630 | R2: 0.539 | BFE: 20.703
------------------------------------------------
Test storm number 93, from 2022-01-12 00:00:00 until 2022-01-20 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 10.751 | R2: 0.751 | BFE: 8.774
Metrics for LDi_HON-1h:
	RMSE: 6.272 | R2: 0.915 | BFE: 5.770 | Inside 90%: 0.987
Metrics for LDi_HON-2h:
	RMSE: 10.090 | R2: 0.781 | BFE: 8.345 | Inside 90%: 0.950
Metrics for persistence -1h:
	RMSE: 6.475 | R2: 0.896 | BFE: 7.010
Metrics for persistence -2h:
	RMSE: 9.035 | R2: 0.798 | BFE: 8.764
------------------------------------------------
Test storm number 94, from 2022-11-05 00:00:00 until 2022-11-13 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 21.449 | R2: -1.051 | BFE: 15.896
Metrics for LDi_HON-1h:
	RMSE: 5.601 | R2: 0.860 | BFE: 4.665 | Inside 90%: 0.975
Metrics for LDi_HON-2h:
	RMSE: 9.239 | R2: 0.619 | BFE: 8.138 | Inside 90%: 0.844
Metrics for persistence -1h:
	RMSE: 5.134 | R2: 0.888 | BFE: 4.478
Metrics for persistence -2h:
	RMSE: 7.495 | R2: 0.762 | BFE: 7.692
------------------------------------------------
Test storm number 95, from 2023-02-25 00:00:00 until 2023-03-06 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 19.937 | R2: 0.487 | BFE: 14.338
Metrics for LDi_HON-1h:
	RMSE: 9.293 | R2: 0.888 | BFE: 10.180 | Inside 90%: 0.932
Metrics for LDi_HON-2h:
	RMSE: 13.448 | R2: 0.766 | BFE: 13.676 | Inside 90%: 0.859
Metrics for persistence -1h:
	RMSE: 9.634 | R2: 0.874 | BFE: 14.893
Metrics for persistence -2h:
	RMSE: 13.282 | R2: 0.761 | BFE: 23.624
------------------------------------------------
Test storm number 96, from 2023-03-21 00:00:00 until 2023-03-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 14.699 | R2: 0.864 | BFE: 17.997
Metrics for LDi_HON-1h:
	RMSE: 9.448 | R2: 0.944 | BFE: 17.770 | Inside 90%: 0.937
Metrics for LDi_HON-2h:
	RMSE: 12.864 | R2: 0.896 | BFE: 22.751 | Inside 90%: 0.876
Metrics for persistence -1h:
	RMSE: 9.937 | R2: 0.929 | BFE: 18.195
Metrics for persistence -2h:
	RMSE: 14.658 | R2: 0.845 | BFE: 27.298
------------------------------------------------
Test storm number 97, from 2023-04-21 00:00:00 until 2023-04-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 10.649 | R2: 0.942 | BFE: 15.667
Metrics for LDi_HON-1h:
	RMSE: 8.872 | R2: 0.960 | BFE: 13.785 | Inside 90%: 0.963
Metrics for LDi_HON-2h:
	RMSE: 14.632 | R2: 0.890 | BFE: 27.476 | Inside 90%: 0.895
Metrics for persistence -1h:
	RMSE: 10.147 | R2: 0.941 | BFE: 20.309
Metrics for persistence -2h:
	RMSE: 16.025 | R2: 0.853 | BFE: 30.541
------------------------------------------------
Test storm number 98, from 2023-08-03 00:00:00 until 2023-08-11 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 9.530 | R2: 0.821 | BFE: 14.567
Metrics for LDi_HON-1h:
	RMSE: 5.989 | R2: 0.929 | BFE: 10.093 | Inside 90%: 0.970
Metrics for LDi_HON-2h:
	RMSE: 9.110 | R2: 0.836 | BFE: 12.775 | Inside 90%: 0.920
Metrics for persistence -1h:
	RMSE: 6.475 | R2: 0.919 | BFE: 12.077
Metrics for persistence -2h:
	RMSE: 10.304 | R2: 0.795 | BFE: 18.677
------------------------------------------------
Test storm number 99, from 2023-11-03 00:00:00 until 2023-11-12 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 11.404 | R2: 0.888 | BFE: 10.049
Metrics for LDi_HON-1h:
	RMSE: 8.942 | R2: 0.931 | BFE: 8.646 | Inside 90%: 0.984
Metrics for LDi_HON-2h:
	RMSE: 11.996 | R2: 0.876 | BFE: 10.222 | Inside 90%: 0.958
Metrics for persistence -1h:
	RMSE: 9.023 | R2: 0.923 | BFE: 8.537
Metrics for persistence -2h:
	RMSE: 11.353 | R2: 0.879 | BFE: 11.579
------------------------------------------------
Test storm number 100, from 2023-11-23 00:00:00 until 2023-12-08 00:00:00, number of batches: 4896
Shapes of the input tensors: torch.Size([4800, 96, 6]), torch.Size([4800, 96, 5]), torch.Size([4800, 1]), torch.Size([4800, 2, 4]), (4800, 2)
Metrics for SYM_H:
	RMSE: 12.369 | R2: 0.684 | BFE: 10.377
Metrics for LDi_HON-1h:
	RMSE: 6.628 | R2: 0.909 | BFE: 5.610 | Inside 90%: 0.968
Metrics for LDi_HON-2h:
	RMSE: 11.285 | R2: 0.737 | BFE: 10.344 | Inside 90%: 0.861
Metrics for persistence -1h:
	RMSE: 7.187 | R2: 0.901 | BFE: 7.078
Metrics for persistence -2h:
	RMSE: 9.934 | R2: 0.810 | BFE: 10.469
------------------------------------------------
Test storm number 101, from 2024-03-01 00:00:00 until 2024-03-09 00:00:00, number of batches: 2881
Shapes of the input tensors: torch.Size([2785, 96, 6]), torch.Size([2785, 96, 5]), torch.Size([2785, 1]), torch.Size([2785, 2, 4]), (2785, 2)
Metrics for SYM_H:
	RMSE: 11.250 | R2: 0.690 | BFE: 9.419
Metrics for LDi_HON-1h:
	RMSE: 5.187 | R2: 0.934 | BFE: 4.798 | Inside 90%: 0.989
Metrics for LDi_HON-2h:
	RMSE: 8.680 | R2: 0.816 | BFE: 9.190 | Inside 90%: 0.922
Metrics for persistence -1h:
	RMSE: 5.693 | R2: 0.914 | BFE: 5.809
Metrics for persistence -2h:
	RMSE: 8.590 | R2: 0.804 | BFE: 9.812
------------------------------------------------
Test storm number 102, from 2024-03-22 00:00:00 until 2024-03-30 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 13.049 | R2: 0.772 | BFE: 10.523
Metrics for LDi_HON-1h:
	RMSE: 8.739 | R2: 0.898 | BFE: 9.940 | Inside 90%: 0.934
Metrics for LDi_HON-2h:
	RMSE: 14.098 | R2: 0.734 | BFE: 18.276 | Inside 90%: 0.775
Metrics for persistence -1h:
	RMSE: 9.793 | R2: 0.878 | BFE: 9.209
Metrics for persistence -2h:
	RMSE: 14.906 | R2: 0.717 | BFE: 15.485
------------------------------------------------
Test storm number 103, from 2024-04-17 00:00:00 until 2024-04-25 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 12.657 | R2: 0.694 | BFE: 12.257
Metrics for LDi_HON-1h:
	RMSE: 6.619 | R2: 0.916 | BFE: 7.757 | Inside 90%: 0.948
Metrics for LDi_HON-2h:
	RMSE: 9.070 | R2: 0.843 | BFE: 11.149 | Inside 90%: 0.861
Metrics for persistence -1h:
	RMSE: 7.123 | R2: 0.900 | BFE: 6.929
Metrics for persistence -2h:
	RMSE: 10.769 | R2: 0.772 | BFE: 10.885
------------------------------------------------
Test storm number 104, from 2024-04-30 00:00:00 until 2024-05-24 00:00:00, number of batches: 7488
Shapes of the input tensors: torch.Size([7392, 96, 6]), torch.Size([7392, 96, 5]), torch.Size([7392, 1]), torch.Size([7392, 2, 4]), (7392, 2)
Metrics for SYM_H:
	RMSE: 16.272 | R2: 0.945 | BFE: 28.827
Metrics for LDi_HON-1h:
	RMSE: 11.247 | R2: 0.974 | BFE: 27.063 | Inside 90%: 0.970
Metrics for LDi_HON-2h:
	RMSE: 15.503 | R2: 0.950 | BFE: 29.611 | Inside 90%: 0.904
Metrics for persistence -1h:
	RMSE: 15.948 | R2: 0.944 | BFE: 45.802
Metrics for persistence -2h:
	RMSE: 21.598 | R2: 0.897 | BFE: 54.715
------------------------------------------------
Test storm number 105, from 2024-06-26 00:00:00 until 2024-07-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 12.376 | R2: 0.733 | BFE: 10.642
Metrics for LDi_HON-1h:
	RMSE: 6.165 | R2: 0.934 | BFE: 6.652 | Inside 90%: 0.987
Metrics for LDi_HON-2h:
	RMSE: 9.567 | R2: 0.840 | BFE: 9.746 | Inside 90%: 0.940
Metrics for persistence -1h:
	RMSE: 6.205 | R2: 0.921 | BFE: 7.673
Metrics for persistence -2h:
	RMSE: 9.207 | R2: 0.827 | BFE: 12.003
------------------------------------------------
Test storm number 106, from 2024-08-02 00:00:00 until 2024-08-19 00:00:00, number of batches: 5472
Shapes of the input tensors: torch.Size([5376, 96, 6]), torch.Size([5376, 96, 5]), torch.Size([5376, 1]), torch.Size([5376, 2, 4]), (5376, 2)
Metrics for SYM_H:
	RMSE: 14.521 | R2: 0.859 | BFE: 18.354
Metrics for LDi_HON-1h:
	RMSE: 8.116 | R2: 0.956 | BFE: 9.847 | Inside 90%: 0.969
Metrics for LDi_HON-2h:
	RMSE: 14.684 | R2: 0.856 | BFE: 15.447 | Inside 90%: 0.894
Metrics for persistence -1h:
	RMSE: 9.671 | R2: 0.932 | BFE: 11.289
Metrics for persistence -2h:
	RMSE: 15.015 | R2: 0.835 | BFE: 18.489
------------------------------------------------
Test storm number 107, from 2024-09-10 00:00:00 until 2024-09-23 00:00:00, number of batches: 4320
Shapes of the input tensors: torch.Size([4224, 96, 6]), torch.Size([4224, 96, 5]), torch.Size([4224, 1]), torch.Size([4224, 2, 4]), (4224, 2)
Metrics for SYM_H:
	RMSE: 12.667 | R2: 0.889 | BFE: 15.264
Metrics for LDi_HON-1h:
	RMSE: 9.082 | R2: 0.943 | BFE: 10.180 | Inside 90%: 0.928
Metrics for LDi_HON-2h:
	RMSE: 13.275 | R2: 0.878 | BFE: 12.891 | Inside 90%: 0.857
Metrics for persistence -1h:
	RMSE: 9.722 | R2: 0.932 | BFE: 9.307
Metrics for persistence -2h:
	RMSE: 15.016 | R2: 0.837 | BFE: 13.420
------------------------------------------------
Test storm number 108, from 2024-10-05 00:00:00 until 2024-10-17 00:00:00, number of batches: 4032
Shapes of the input tensors: torch.Size([3936, 96, 6]), torch.Size([3936, 96, 5]), torch.Size([3936, 1]), torch.Size([3936, 2, 4]), (3936, 2)
Metrics for SYM_H:
	RMSE: 22.819 | R2: 0.879 | BFE: 24.628
Metrics for LDi_HON-1h:
	RMSE: 15.271 | R2: 0.946 | BFE: 27.421 | Inside 90%: 0.909
Metrics for LDi_HON-2h:
	RMSE: 22.011 | R2: 0.888 | BFE: 39.748 | Inside 90%: 0.844
Metrics for persistence -1h:
	RMSE: 15.570 | R2: 0.940 | BFE: 26.573
Metrics for persistence -2h:
	RMSE: 21.877 | R2: 0.881 | BFE: 36.711
------------------------------------------------
Test storm number 109, from 2024-11-07 00:00:00 until 2024-11-15 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 13.110 | R2: 0.571 | BFE: 11.105
Metrics for LDi_HON-1h:
	RMSE: 8.435 | R2: 0.822 | BFE: 6.098 | Inside 90%: 0.976
Metrics for LDi_HON-2h:
	RMSE: 13.410 | R2: 0.551 | BFE: 9.880 | Inside 90%: 0.867
Metrics for persistence -1h:
	RMSE: 6.595 | R2: 0.871 | BFE: 7.976
Metrics for persistence -2h:
	RMSE: 9.606 | R2: 0.727 | BFE: 11.640
------------------------------------------------
Metrics for the MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,HON,89,24.087,13.696,16.418,0.750,12.554000,31.393000,5.634,10.251,9.055,17.200,0.924,0.725,0.975,0.912
1,HON,90,18.365,11.609,13.824,0.612,10.085000,11.990000,5.429,8.726,7.591,11.421,0.883,0.735,0.948,0.858
2,HON,91,21.361,8.706,11.817,0.907,14.090000,21.999001,4.883,7.845,9.426,12.890,0.941,0.890,0.964,0.902
3,HON,92,14.682,7.835,11.334,0.648,12.744000,21.947001,5.459,9.425,8.125,14.463,0.819,0.427,0.926,0.836
4,HON,93,8.774,9.116,10.751,0.751,5.770000,8.345000,4.797,7.972,6.272,10.090,0.915,0.781,0.987,0.950
5,HON,94,15.896,17.129,21.449,-1.051,4.665000,8.138000,4.349,7.346,5.601,9.239,0.860,0.619,0.975,0.844
6,HON,95,14.338,15.281,19.937,0.487,10.180000,13.676000,6.375,9.709,9.293,13.448,0.888,0.766,0.932,0.859
7,HON,96,17.997,12.018,14.699,0.864,17.770000,22.750999,5.693,8.506,9.448,12.864,0.944,0.896,0.937,0.876
8,HON,97,15.667,7.446,10.649,0.942,13.785000,27.476000,5.656,9.011,8.872,14.632,0.960,0.890,0.963,0.895
9,HON,98,14.567,7.381,9.530,0.821,10.093000,12.775000,4.095,6.462,5.989,9.110,0.929,0.836,0.970,0.920
10,HON,99,10.049,6.019,11.404,0.888,8.646000,10.222000,5.685,8.498,8.942,11.996,0.931,0.876,0.984,0.958
11,HON,100,10.377,9.699,12.369,0.684,5.610000,10.344000,4.706,8.064,6.628,11.285,0.909,0.737,0.968,0.861
12,HON,101,9.419,7.288,11.250,0.690,4.798000,9.190000,3.876,6.612,5.187,8.680,0.934,0.816,0.989,0.922
13,HON,102,10.523,8.857,13.049,0.772,9.940000,18.275999,6.079,9.995,8.739,14.098,0.898,0.734,0.934,0.775
14,HON,103,12.257,10.395,12.657,0.694,7.757000,11.149000,4.560,6.567,6.619,9.070,0.916,0.843,0.948,0.861
15,HON,104,28.827,9.278,16.272,0.945,27.063000,29.611000,5.746,8.873,11.247,15.503,0.974,0.950,0.970,0.904
16,HON,105,10.642,9.881,12.376,0.733,6.652000,9.746000,4.090,6.940,6.165,9.567,0.934,0.840,0.987,0.940
17,HON,106,18.354,9.945,14.521,0.859,9.847000,15.447000,5.295,9.142,8.116,14.684,0.956,0.856,0.969,0.894
18,HON,107,15.264,9.979,12.667,0.889,10.180000,12.891000,5.989,9.178,9.082,13.275,0.943,0.878,0.928,0.857
19,HON,108,24.628,20.113,22.819,0.879,27.421000,39.748001,8.442,12.487,15.271,22.011,0.946,0.888,0.909,0.844
20,HON,109,11.105,9.965,13.110,0.571,6.098000,9.880000,5.957,9.904,8.435,13.410,0.822,0.551,0.976,0.867
21,HON,Mean,15.580,10.554,13.948,0.683,11.226000,17.000000,5.371,8.643,8.291,12.807,0.916,0.787,0.959,0.883
22,HON,Global,29.023,10.578,14.656,0.871,26.721001,32.192001,5.456,8.760,8.922,13.617,0.952,0.889,0.959,0.883

Mean and global MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
21,HON,Mean,15.580,10.554,13.948,0.683,11.226000,17.000000,5.371,8.643,8.291,12.807,0.916,0.787,0.959,0.883
22,HON,Global,29.023,10.578,14.656,0.871,26.721001,32.192001,5.456,8.760,8.922,13.617,0.952,0.889,0.959,0.883

           Station  BFE SYM-H  DTW SYM-H  RMSE SYM-H  R2 SYM_H
StormIndex
Mean           HON     15.580     10.554      13.948     0.683
Global         HON     29.023     10.578      14.656     0.871
Metrics for persistence -2h:
	RMSE: 10.061 | R2: 0.932 | BFE: 36.434
Metrics for persistence -2h:
	RMSE: 14.496 | R2: 0.859 | BFE: 45.655
Diff BFE (SYM-H nowcast - LDi forecast 1h):
Total: 2.302
Diff BFE (SYM-H nowcast - LDi forecast 2h):
Total: -3.169

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,HON,89,24.087273,13.695542,16.417782,0.749596,12.554164,31.392675,5.634347,10.250728,9.054785,17.200062,0.923833,0.725165,0.974933,0.911685
1,HON,90,18.365037,11.609193,13.823751,0.611908,10.084810,11.990288,5.429496,8.725995,7.590697,11.421491,0.882984,0.735072,0.948373,0.857701
2,HON,91,21.361243,8.705857,11.817078,0.907304,14.090361,21.999197,4.882601,7.844621,9.425741,12.890362,0.941025,0.889701,0.964425,0.901518
3,HON,92,14.682178,7.834586,11.334126,0.648089,12.743805,21.946768,5.458649,9.424595,8.125154,14.463058,0.819149,0.426971,0.925813,0.835575
4,HON,93,8.773747,9.116456,10.750762,0.751400,5.770063,8.345233,4.797339,7.971769,6.272356,10.090349,0.915378,0.781004,0.987419,0.950108
5,HON,94,15.896121,17.128737,21.449318,-1.050778,4.665092,8.138317,4.348975,7.346022,5.600754,9.239199,0.860175,0.619495,0.975271,0.843818
6,HON,95,14.338431,15.281400,19.936592,0.486716,10.180209,13.675858,6.375165,9.709119,9.292794,13.447620,0.888481,0.766468,0.931739,0.858851
7,HON,96,17.997489,12.018317,14.698519,0.863849,17.770012,22.750555,5.693210,8.505983,9.447601,12.863937,0.943751,0.895715,0.937138,0.875820
8,HON,97,15.666986,7.445808,10.648917,0.941808,13.784632,27.475700,5.655992,9.011390,8.871846,14.632007,0.959609,0.890135,0.962977,0.895102
9,HON,98,14.566696,7.381332,9.529902,0.820954,10.093100,12.775177,4.095369,6.461593,5.989246,9.110369,0.929282,0.836371,0.970065,0.919740
10,HON,99,10.049378,6.019001,11.404463,0.887762,8.646487,10.222375,5.685185,8.497648,8.941528,11.996409,0.931006,0.875808,0.983803,0.957964
11,HON,100,10.377402,9.699218,12.368683,0.683551,5.609815,10.344285,4.705943,8.064086,6.627541,11.285064,0.909142,0.736570,0.967832,0.861143
12,HON,101,9.418515,7.288113,11.249887,0.690134,4.797516,9.190240,3.875851,6.611799,5.186801,8.679805,0.934132,0.815542,0.989154,0.921909
13,HON,102,10.522747,8.856686,13.048569,0.771747,9.940104,18.276251,6.079032,9.994671,8.739221,14.097954,0.897615,0.733557,0.934056,0.774837
14,HON,103,12.257007,10.395345,12.657219,0.693908,7.756863,11.149080,4.560048,6.566569,6.618581,9.070148,0.916304,0.842817,0.948373,0.860738
15,HON,104,28.827422,9.278338,16.272327,0.944592,27.062820,29.611143,5.745708,8.872939,11.246714,15.503309,0.973532,0.949706,0.970201,0.903804
16,HON,105,10.641548,9.880525,12.375688,0.732507,6.651642,9.745954,4.090026,6.940370,6.165496,9.567453,0.933609,0.840130,0.987419,0.940130
17,HON,106,18.353532,9.945472,14.521341,0.858884,9.846715,15.446686,5.295085,9.141924,8.115503,14.683847,0.955925,0.855708,0.968961,0.893608
18,HON,107,15.264132,9.979061,12.667396,0.888720,10.179643,12.891131,5.988625,9.178139,9.082379,13.275334,0.942794,0.877782,0.928438,0.856876
19,HON,108,24.628235,20.112608,22.819330,0.879448,27.421373,39.748474,8.442238,12.487128,15.271036,22.011387,0.946011,0.887833,0.908591,0.844374
20,HON,109,11.104874,9.964729,13.109519,0.570966,6.098333,9.880158,5.957398,9.904356,8.435490,13.409748,0.822361,0.551090,0.976139,0.867245
21,HON,Mean,15.580000,10.554111,13.947675,0.682527,11.226073,16.999788,5.371252,8.643402,8.290536,12.806615,0.915528,0.787269,0.959101,0.882502
22,HON,Global,29.023123,10.578279,14.656344,0.871474,26.721169,32.191723,5.456302,8.759767,8.921650,13.616827,0.952376,0.889059,0.958948,0.882958

Testing model RELDi
Evaluating for on station HON
Test storm number 89, from 2017-09-06 00:00:00 until 2017-09-15 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 16.418 | R2: 0.750 | BFE: 24.087
Metrics for LDi_HON-1h:
	RMSE: 9.055 | R2: 0.924 | BFE: 12.554 | Inside 90%: 0.975
Metrics for LDi_HON-2h:
	RMSE: 17.200 | R2: 0.725 | BFE: 31.393 | Inside 90%: 0.912
Metrics for persistence -1h:
	RMSE: 11.338 | R2: 0.867 | BFE: 14.989
Metrics for persistence -2h:
	RMSE: 17.664 | R2: 0.677 | BFE: 22.460
------------------------------------------------
Test storm number 90, from 2017-09-26 00:00:00 until 2017-10-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 13.824 | R2: 0.612 | BFE: 18.365
Metrics for LDi_HON-1h:
	RMSE: 7.591 | R2: 0.883 | BFE: 10.085 | Inside 90%: 0.948
Metrics for LDi_HON-2h:
	RMSE: 11.421 | R2: 0.735 | BFE: 11.990 | Inside 90%: 0.858
Metrics for persistence -1h:
	RMSE: 7.789 | R2: 0.864 | BFE: 8.479
Metrics for persistence -2h:
	RMSE: 11.071 | R2: 0.725 | BFE: 15.139
------------------------------------------------
Test storm number 91, from 2018-08-24 00:00:00 until 2018-09-01 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 11.817 | R2: 0.907 | BFE: 21.361
Metrics for LDi_HON-1h:
	RMSE: 9.426 | R2: 0.941 | BFE: 14.090 | Inside 90%: 0.964
Metrics for LDi_HON-2h:
	RMSE: 12.890 | R2: 0.890 | BFE: 21.999 | Inside 90%: 0.902
Metrics for persistence -1h:
	RMSE: 10.459 | R2: 0.915 | BFE: 24.220
Metrics for persistence -2h:
	RMSE: 15.663 | R2: 0.809 | BFE: 34.098
------------------------------------------------
Test storm number 92, from 2021-11-02 00:00:00 until 2021-11-10 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 11.334 | R2: 0.648 | BFE: 14.682
Metrics for LDi_HON-1h:
	RMSE: 8.125 | R2: 0.819 | BFE: 12.744 | Inside 90%: 0.926
Metrics for LDi_HON-2h:
	RMSE: 14.463 | R2: 0.427 | BFE: 21.947 | Inside 90%: 0.836
Metrics for persistence -1h:
	RMSE: 9.204 | R2: 0.755 | BFE: 17.623
Metrics for persistence -2h:
	RMSE: 12.630 | R2: 0.539 | BFE: 20.703
------------------------------------------------
Test storm number 93, from 2022-01-12 00:00:00 until 2022-01-20 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 10.751 | R2: 0.751 | BFE: 8.774
Metrics for LDi_HON-1h:
	RMSE: 6.272 | R2: 0.915 | BFE: 5.770 | Inside 90%: 0.987
Metrics for LDi_HON-2h:
	RMSE: 10.090 | R2: 0.781 | BFE: 8.345 | Inside 90%: 0.950
Metrics for persistence -1h:
	RMSE: 6.475 | R2: 0.896 | BFE: 7.010
Metrics for persistence -2h:
	RMSE: 9.035 | R2: 0.798 | BFE: 8.764
------------------------------------------------
Test storm number 94, from 2022-11-05 00:00:00 until 2022-11-13 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 21.449 | R2: -1.051 | BFE: 15.896
Metrics for LDi_HON-1h:
	RMSE: 5.601 | R2: 0.860 | BFE: 4.665 | Inside 90%: 0.975
Metrics for LDi_HON-2h:
	RMSE: 9.239 | R2: 0.619 | BFE: 8.138 | Inside 90%: 0.844
Metrics for persistence -1h:
	RMSE: 5.134 | R2: 0.888 | BFE: 4.478
Metrics for persistence -2h:
	RMSE: 7.495 | R2: 0.762 | BFE: 7.692
------------------------------------------------
Test storm number 95, from 2023-02-25 00:00:00 until 2023-03-06 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 19.937 | R2: 0.487 | BFE: 14.338
Metrics for LDi_HON-1h:
	RMSE: 9.293 | R2: 0.888 | BFE: 10.180 | Inside 90%: 0.932
Metrics for LDi_HON-2h:
	RMSE: 13.448 | R2: 0.766 | BFE: 13.676 | Inside 90%: 0.859
Metrics for persistence -1h:
	RMSE: 9.634 | R2: 0.874 | BFE: 14.893
Metrics for persistence -2h:
	RMSE: 13.282 | R2: 0.761 | BFE: 23.624
------------------------------------------------
Test storm number 96, from 2023-03-21 00:00:00 until 2023-03-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 14.699 | R2: 0.864 | BFE: 17.997
Metrics for LDi_HON-1h:
	RMSE: 9.448 | R2: 0.944 | BFE: 17.770 | Inside 90%: 0.937
Metrics for LDi_HON-2h:
	RMSE: 12.864 | R2: 0.896 | BFE: 22.751 | Inside 90%: 0.876
Metrics for persistence -1h:
	RMSE: 9.937 | R2: 0.929 | BFE: 18.195
Metrics for persistence -2h:
	RMSE: 14.658 | R2: 0.845 | BFE: 27.298
------------------------------------------------
Test storm number 97, from 2023-04-21 00:00:00 until 2023-04-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 10.649 | R2: 0.942 | BFE: 15.667
Metrics for LDi_HON-1h:
	RMSE: 8.872 | R2: 0.960 | BFE: 13.785 | Inside 90%: 0.963
Metrics for LDi_HON-2h:
	RMSE: 14.632 | R2: 0.890 | BFE: 27.476 | Inside 90%: 0.895
Metrics for persistence -1h:
	RMSE: 10.147 | R2: 0.941 | BFE: 20.309
Metrics for persistence -2h:
	RMSE: 16.025 | R2: 0.853 | BFE: 30.541
------------------------------------------------
Test storm number 98, from 2023-08-03 00:00:00 until 2023-08-11 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 9.530 | R2: 0.821 | BFE: 14.567
Metrics for LDi_HON-1h:
	RMSE: 5.989 | R2: 0.929 | BFE: 10.093 | Inside 90%: 0.970
Metrics for LDi_HON-2h:
	RMSE: 9.110 | R2: 0.836 | BFE: 12.775 | Inside 90%: 0.920
Metrics for persistence -1h:
	RMSE: 6.475 | R2: 0.919 | BFE: 12.077
Metrics for persistence -2h:
	RMSE: 10.304 | R2: 0.795 | BFE: 18.677
------------------------------------------------
Test storm number 99, from 2023-11-03 00:00:00 until 2023-11-12 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 11.404 | R2: 0.888 | BFE: 10.049
Metrics for LDi_HON-1h:
	RMSE: 8.942 | R2: 0.931 | BFE: 8.646 | Inside 90%: 0.984
Metrics for LDi_HON-2h:
	RMSE: 11.996 | R2: 0.876 | BFE: 10.222 | Inside 90%: 0.958
Metrics for persistence -1h:
	RMSE: 9.023 | R2: 0.923 | BFE: 8.537
Metrics for persistence -2h:
	RMSE: 11.353 | R2: 0.879 | BFE: 11.579
------------------------------------------------
Test storm number 100, from 2023-11-23 00:00:00 until 2023-12-08 00:00:00, number of batches: 4896
Shapes of the input tensors: torch.Size([4800, 96, 6]), torch.Size([4800, 96, 5]), torch.Size([4800, 1]), torch.Size([4800, 2, 4]), (4800, 2)
Metrics for SYM_H:
	RMSE: 12.369 | R2: 0.684 | BFE: 10.377
Metrics for LDi_HON-1h:
	RMSE: 6.628 | R2: 0.909 | BFE: 5.610 | Inside 90%: 0.968
Metrics for LDi_HON-2h:
	RMSE: 11.285 | R2: 0.737 | BFE: 10.344 | Inside 90%: 0.861
Metrics for persistence -1h:
	RMSE: 7.187 | R2: 0.901 | BFE: 7.078
Metrics for persistence -2h:
	RMSE: 9.934 | R2: 0.810 | BFE: 10.469
------------------------------------------------
Test storm number 101, from 2024-03-01 00:00:00 until 2024-03-09 00:00:00, number of batches: 2881
Shapes of the input tensors: torch.Size([2785, 96, 6]), torch.Size([2785, 96, 5]), torch.Size([2785, 1]), torch.Size([2785, 2, 4]), (2785, 2)
Metrics for SYM_H:
	RMSE: 11.250 | R2: 0.690 | BFE: 9.419
Metrics for LDi_HON-1h:
	RMSE: 5.187 | R2: 0.934 | BFE: 4.798 | Inside 90%: 0.989
Metrics for LDi_HON-2h:
	RMSE: 8.680 | R2: 0.816 | BFE: 9.190 | Inside 90%: 0.922
Metrics for persistence -1h:
	RMSE: 5.693 | R2: 0.914 | BFE: 5.809
Metrics for persistence -2h:
	RMSE: 8.590 | R2: 0.804 | BFE: 9.812
------------------------------------------------
Test storm number 102, from 2024-03-22 00:00:00 until 2024-03-30 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 13.049 | R2: 0.772 | BFE: 10.523
Metrics for LDi_HON-1h:
	RMSE: 8.739 | R2: 0.898 | BFE: 9.940 | Inside 90%: 0.934
Metrics for LDi_HON-2h:
	RMSE: 14.098 | R2: 0.734 | BFE: 18.276 | Inside 90%: 0.775
Metrics for persistence -1h:
	RMSE: 9.793 | R2: 0.878 | BFE: 9.209
Metrics for persistence -2h:
	RMSE: 14.906 | R2: 0.717 | BFE: 15.485
------------------------------------------------
Test storm number 103, from 2024-04-17 00:00:00 until 2024-04-25 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 12.657 | R2: 0.694 | BFE: 12.257
Metrics for LDi_HON-1h:
	RMSE: 6.619 | R2: 0.916 | BFE: 7.757 | Inside 90%: 0.948
Metrics for LDi_HON-2h:
	RMSE: 9.070 | R2: 0.843 | BFE: 11.149 | Inside 90%: 0.861
Metrics for persistence -1h:
	RMSE: 7.123 | R2: 0.900 | BFE: 6.929
Metrics for persistence -2h:
	RMSE: 10.769 | R2: 0.772 | BFE: 10.885
------------------------------------------------
Test storm number 104, from 2024-04-30 00:00:00 until 2024-05-24 00:00:00, number of batches: 7488
Shapes of the input tensors: torch.Size([7392, 96, 6]), torch.Size([7392, 96, 5]), torch.Size([7392, 1]), torch.Size([7392, 2, 4]), (7392, 2)
Metrics for SYM_H:
	RMSE: 16.272 | R2: 0.945 | BFE: 28.827
Metrics for LDi_HON-1h:
	RMSE: 11.247 | R2: 0.974 | BFE: 27.063 | Inside 90%: 0.970
Metrics for LDi_HON-2h:
	RMSE: 15.503 | R2: 0.950 | BFE: 29.611 | Inside 90%: 0.904
Metrics for persistence -1h:
	RMSE: 15.948 | R2: 0.944 | BFE: 45.802
Metrics for persistence -2h:
	RMSE: 21.598 | R2: 0.897 | BFE: 54.715
------------------------------------------------
Test storm number 105, from 2024-06-26 00:00:00 until 2024-07-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 12.376 | R2: 0.733 | BFE: 10.642
Metrics for LDi_HON-1h:
	RMSE: 6.165 | R2: 0.934 | BFE: 6.652 | Inside 90%: 0.987
Metrics for LDi_HON-2h:
	RMSE: 9.567 | R2: 0.840 | BFE: 9.746 | Inside 90%: 0.940
Metrics for persistence -1h:
	RMSE: 6.205 | R2: 0.921 | BFE: 7.673
Metrics for persistence -2h:
	RMSE: 9.207 | R2: 0.827 | BFE: 12.003
------------------------------------------------
Test storm number 106, from 2024-08-02 00:00:00 until 2024-08-19 00:00:00, number of batches: 5472
Shapes of the input tensors: torch.Size([5376, 96, 6]), torch.Size([5376, 96, 5]), torch.Size([5376, 1]), torch.Size([5376, 2, 4]), (5376, 2)
Metrics for SYM_H:
	RMSE: 14.521 | R2: 0.859 | BFE: 18.354
Metrics for LDi_HON-1h:
	RMSE: 8.116 | R2: 0.956 | BFE: 9.847 | Inside 90%: 0.969
Metrics for LDi_HON-2h:
	RMSE: 14.684 | R2: 0.856 | BFE: 15.447 | Inside 90%: 0.894
Metrics for persistence -1h:
	RMSE: 9.671 | R2: 0.932 | BFE: 11.289
Metrics for persistence -2h:
	RMSE: 15.015 | R2: 0.835 | BFE: 18.489
------------------------------------------------
Test storm number 107, from 2024-09-10 00:00:00 until 2024-09-23 00:00:00, number of batches: 4320
Shapes of the input tensors: torch.Size([4224, 96, 6]), torch.Size([4224, 96, 5]), torch.Size([4224, 1]), torch.Size([4224, 2, 4]), (4224, 2)
Metrics for SYM_H:
	RMSE: 12.667 | R2: 0.889 | BFE: 15.264
Metrics for LDi_HON-1h:
	RMSE: 9.082 | R2: 0.943 | BFE: 10.180 | Inside 90%: 0.928
Metrics for LDi_HON-2h:
	RMSE: 13.275 | R2: 0.878 | BFE: 12.891 | Inside 90%: 0.857
Metrics for persistence -1h:
	RMSE: 9.722 | R2: 0.932 | BFE: 9.307
Metrics for persistence -2h:
	RMSE: 15.016 | R2: 0.837 | BFE: 13.420
------------------------------------------------
Test storm number 108, from 2024-10-05 00:00:00 until 2024-10-17 00:00:00, number of batches: 4032
Shapes of the input tensors: torch.Size([3936, 96, 6]), torch.Size([3936, 96, 5]), torch.Size([3936, 1]), torch.Size([3936, 2, 4]), (3936, 2)
Metrics for SYM_H:
	RMSE: 22.819 | R2: 0.879 | BFE: 24.628
Metrics for LDi_HON-1h:
	RMSE: 15.271 | R2: 0.946 | BFE: 27.421 | Inside 90%: 0.909
Metrics for LDi_HON-2h:
	RMSE: 22.011 | R2: 0.888 | BFE: 39.748 | Inside 90%: 0.844
Metrics for persistence -1h:
	RMSE: 15.570 | R2: 0.940 | BFE: 26.573
Metrics for persistence -2h:
	RMSE: 21.877 | R2: 0.881 | BFE: 36.711
------------------------------------------------
Test storm number 109, from 2024-11-07 00:00:00 until 2024-11-15 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 13.110 | R2: 0.571 | BFE: 11.105
Metrics for LDi_HON-1h:
	RMSE: 8.435 | R2: 0.822 | BFE: 6.098 | Inside 90%: 0.976
Metrics for LDi_HON-2h:
	RMSE: 13.410 | R2: 0.551 | BFE: 9.880 | Inside 90%: 0.867
Metrics for persistence -1h:
	RMSE: 6.595 | R2: 0.871 | BFE: 7.976
Metrics for persistence -2h:
	RMSE: 9.606 | R2: 0.727 | BFE: 11.640
------------------------------------------------
Metrics for the MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,HON,89,24.087,13.696,16.418,0.750,12.554000,31.393000,5.634,10.251,9.055,17.200,0.924,0.725,0.975,0.912
1,HON,90,18.365,11.609,13.824,0.612,10.085000,11.990000,5.429,8.726,7.591,11.421,0.883,0.735,0.948,0.858
2,HON,91,21.361,8.706,11.817,0.907,14.090000,21.999001,4.883,7.845,9.426,12.890,0.941,0.890,0.964,0.902
3,HON,92,14.682,7.835,11.334,0.648,12.744000,21.947001,5.459,9.425,8.125,14.463,0.819,0.427,0.926,0.836
4,HON,93,8.774,9.116,10.751,0.751,5.770000,8.345000,4.797,7.972,6.272,10.090,0.915,0.781,0.987,0.950
5,HON,94,15.896,17.129,21.449,-1.051,4.665000,8.138000,4.349,7.346,5.601,9.239,0.860,0.619,0.975,0.844
6,HON,95,14.338,15.281,19.937,0.487,10.180000,13.676000,6.375,9.709,9.293,13.448,0.888,0.766,0.932,0.859
7,HON,96,17.997,12.018,14.699,0.864,17.770000,22.750999,5.693,8.506,9.448,12.864,0.944,0.896,0.937,0.876
8,HON,97,15.667,7.446,10.649,0.942,13.785000,27.476000,5.656,9.011,8.872,14.632,0.960,0.890,0.963,0.895
9,HON,98,14.567,7.381,9.530,0.821,10.093000,12.775000,4.095,6.462,5.989,9.110,0.929,0.836,0.970,0.920
10,HON,99,10.049,6.019,11.404,0.888,8.646000,10.222000,5.685,8.498,8.942,11.996,0.931,0.876,0.984,0.958
11,HON,100,10.377,9.699,12.369,0.684,5.610000,10.344000,4.706,8.064,6.628,11.285,0.909,0.737,0.968,0.861
12,HON,101,9.419,7.288,11.250,0.690,4.798000,9.190000,3.876,6.612,5.187,8.680,0.934,0.816,0.989,0.922
13,HON,102,10.523,8.857,13.049,0.772,9.940000,18.275999,6.079,9.995,8.739,14.098,0.898,0.734,0.934,0.775
14,HON,103,12.257,10.395,12.657,0.694,7.757000,11.149000,4.560,6.567,6.619,9.070,0.916,0.843,0.948,0.861
15,HON,104,28.827,9.278,16.272,0.945,27.063000,29.611000,5.746,8.873,11.247,15.503,0.974,0.950,0.970,0.904
16,HON,105,10.642,9.881,12.376,0.733,6.652000,9.746000,4.090,6.940,6.165,9.567,0.934,0.840,0.987,0.940
17,HON,106,18.354,9.945,14.521,0.859,9.847000,15.447000,5.295,9.142,8.116,14.684,0.956,0.856,0.969,0.894
18,HON,107,15.264,9.979,12.667,0.889,10.180000,12.891000,5.989,9.178,9.082,13.275,0.943,0.878,0.928,0.857
19,HON,108,24.628,20.113,22.819,0.879,27.421000,39.748001,8.442,12.487,15.271,22.011,0.946,0.888,0.909,0.844
20,HON,109,11.105,9.965,13.110,0.571,6.098000,9.880000,5.957,9.904,8.435,13.410,0.822,0.551,0.976,0.867
21,HON,Mean,15.580,10.554,13.948,0.683,11.226000,17.000000,5.371,8.643,8.291,12.807,0.916,0.787,0.959,0.883
22,HON,Global,29.023,10.578,14.656,0.871,26.721001,32.192001,5.456,8.760,8.922,13.617,0.952,0.889,0.959,0.883

Mean and global MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
21,HON,Mean,15.580,10.554,13.948,0.683,11.226000,17.000000,5.371,8.643,8.291,12.807,0.916,0.787,0.959,0.883
22,HON,Global,29.023,10.578,14.656,0.871,26.721001,32.192001,5.456,8.760,8.922,13.617,0.952,0.889,0.959,0.883

           Station  BFE SYM-H  DTW SYM-H  RMSE SYM-H  R2 SYM_H
StormIndex
Mean           HON     15.580     10.554      13.948     0.683
Global         HON     29.023     10.578      14.656     0.871
Metrics for persistence -2h:
	RMSE: 10.061 | R2: 0.932 | BFE: 36.434
Metrics for persistence -2h:
	RMSE: 14.496 | R2: 0.859 | BFE: 45.655
Diff BFE (SYM-H nowcast - LDi forecast 1h):
Total: 2.302
Diff BFE (SYM-H nowcast - LDi forecast 2h):
Total: -3.169

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,HON,89,24.087273,13.695542,16.417782,0.749596,12.554164,31.392675,5.634347,10.250728,9.054785,17.200062,0.923833,0.725165,0.974933,0.911685
1,HON,90,18.365037,11.609193,13.823751,0.611908,10.084810,11.990288,5.429496,8.725995,7.590697,11.421491,0.882984,0.735072,0.948373,0.857701
2,HON,91,21.361243,8.705857,11.817078,0.907304,14.090361,21.999197,4.882601,7.844621,9.425741,12.890362,0.941025,0.889701,0.964425,0.901518
3,HON,92,14.682178,7.834586,11.334126,0.648089,12.743805,21.946768,5.458649,9.424595,8.125154,14.463058,0.819149,0.426971,0.925813,0.835575
4,HON,93,8.773747,9.116456,10.750762,0.751400,5.770063,8.345233,4.797339,7.971769,6.272356,10.090349,0.915378,0.781004,0.987419,0.950108
5,HON,94,15.896121,17.128737,21.449318,-1.050778,4.665092,8.138317,4.348975,7.346022,5.600754,9.239199,0.860175,0.619495,0.975271,0.843818
6,HON,95,14.338431,15.281400,19.936592,0.486716,10.180209,13.675858,6.375165,9.709119,9.292794,13.447620,0.888481,0.766468,0.931739,0.858851
7,HON,96,17.997489,12.018317,14.698519,0.863849,17.770012,22.750555,5.693210,8.505983,9.447601,12.863937,0.943751,0.895715,0.937138,0.875820
8,HON,97,15.666986,7.445808,10.648917,0.941808,13.784632,27.475700,5.655992,9.011390,8.871846,14.632007,0.959609,0.890135,0.962977,0.895102
9,HON,98,14.566696,7.381332,9.529902,0.820954,10.093100,12.775177,4.095369,6.461593,5.989246,9.110369,0.929282,0.836371,0.970065,0.919740
10,HON,99,10.049378,6.019001,11.404463,0.887762,8.646487,10.222375,5.685185,8.497648,8.941528,11.996409,0.931006,0.875808,0.983803,0.957964
11,HON,100,10.377402,9.699218,12.368683,0.683551,5.609815,10.344285,4.705943,8.064086,6.627541,11.285064,0.909142,0.736570,0.967832,0.861143
12,HON,101,9.418515,7.288113,11.249887,0.690134,4.797516,9.190240,3.875851,6.611799,5.186801,8.679805,0.934132,0.815542,0.989154,0.921909
13,HON,102,10.522747,8.856686,13.048569,0.771747,9.940104,18.276251,6.079032,9.994671,8.739221,14.097954,0.897615,0.733557,0.934056,0.774837
14,HON,103,12.257007,10.395345,12.657219,0.693908,7.756863,11.149080,4.560048,6.566569,6.618581,9.070148,0.916304,0.842817,0.948373,0.860738
15,HON,104,28.827422,9.278338,16.272327,0.944592,27.062820,29.611143,5.745708,8.872939,11.246714,15.503309,0.973532,0.949706,0.970201,0.903804
16,HON,105,10.641548,9.880525,12.375688,0.732507,6.651642,9.745954,4.090026,6.940370,6.165496,9.567453,0.933609,0.840130,0.987419,0.940130
17,HON,106,18.353532,9.945472,14.521341,0.858884,9.846715,15.446686,5.295085,9.141924,8.115503,14.683847,0.955925,0.855708,0.968961,0.893608
18,HON,107,15.264132,9.979061,12.667396,0.888720,10.179643,12.891131,5.988625,9.178139,9.082379,13.275334,0.942794,0.877782,0.928438,0.856876
19,HON,108,24.628235,20.112608,22.819330,0.879448,27.421373,39.748474,8.442238,12.487128,15.271036,22.011387,0.946011,0.887833,0.908591,0.844374
20,HON,109,11.104874,9.964729,13.109519,0.570966,6.098333,9.880158,5.957398,9.904356,8.435490,13.409748,0.822361,0.551090,0.976139,0.867245
21,HON,Mean,15.580000,10.554111,13.947675,0.682527,11.226073,16.999788,5.371252,8.643402,8.290536,12.806615,0.915528,0.787269,0.959101,0.882502
22,HON,Global,29.023123,10.578279,14.656344,0.871474,26.721169,32.191723,5.456302,8.759767,8.921650,13.616827,0.952376,0.889059,0.958948,0.882958

In [ ]:
station = constants.STATIONS[5]
color = "magenta"

str_return, metrics_station, sum_df_station = test_on_station(
    station, color, model, same_color=True
)
str_summary += str_return
sum_dfs_stations.append(sum_df_station)
summary_df.loc[len(summary_df)] = metrics_station

color = constants.COLOR_STATIONS[station]
_, _, _ = test_on_station(station, color, model, same_color=False)

Testing model RELDi
Evaluating for on station SFS
Test storm number 89, from 2017-09-06 00:00:00 until 2017-09-15 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 22.758 | R2: 0.570 | BFE: 50.584
Metrics for LDi_SFS-1h:
	RMSE: 16.443 | R2: 0.775 | BFE: 30.366 | Inside 90%: 0.895
Metrics for LDi_SFS-2h:
	RMSE: 22.648 | R2: 0.574 | BFE: 47.286 | Inside 90%: 0.772
Metrics for persistence -1h:
	RMSE: 17.885 | R2: 0.695 | BFE: 25.003
Metrics for persistence -2h:
	RMSE: 23.706 | R2: 0.465 | BFE: 34.913
------------------------------------------------
Test storm number 90, from 2017-09-26 00:00:00 until 2017-10-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 18.635 | R2: 0.114 | BFE: 18.339
Metrics for LDi_SFS-1h:
	RMSE: 11.153 | R2: 0.683 | BFE: 10.038 | Inside 90%: 0.853
Metrics for LDi_SFS-2h:
	RMSE: 14.922 | R2: 0.432 | BFE: 12.969 | Inside 90%: 0.767
Metrics for persistence -1h:
	RMSE: 11.376 | R2: 0.617 | BFE: 11.893
Metrics for persistence -2h:
	RMSE: 14.803 | R2: 0.352 | BFE: 14.430
------------------------------------------------
Test storm number 91, from 2018-08-24 00:00:00 until 2018-09-01 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 23.527 | R2: 0.360 | BFE: 20.574
Metrics for LDi_SFS-1h:
	RMSE: 11.551 | R2: 0.846 | BFE: 14.848 | Inside 90%: 0.924
Metrics for LDi_SFS-2h:
	RMSE: 17.014 | R2: 0.665 | BFE: 22.636 | Inside 90%: 0.825
Metrics for persistence -1h:
	RMSE: 12.051 | R2: 0.805 | BFE: 17.152
Metrics for persistence -2h:
	RMSE: 16.828 | R2: 0.620 | BFE: 22.815
------------------------------------------------
Test storm number 92, from 2021-11-02 00:00:00 until 2021-11-10 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 16.285 | R2: 0.469 | BFE: 27.901
Metrics for LDi_SFS-1h:
	RMSE: 13.471 | R2: 0.637 | BFE: 26.235 | Inside 90%: 0.800
Metrics for LDi_SFS-2h:
	RMSE: 17.731 | R2: 0.371 | BFE: 32.936 | Inside 90%: 0.690
Metrics for persistence -1h:
	RMSE: 13.416 | R2: 0.594 | BFE: 25.175
Metrics for persistence -2h:
	RMSE: 17.587 | R2: 0.303 | BFE: 28.312
------------------------------------------------
Test storm number 93, from 2022-01-12 00:00:00 until 2022-01-20 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 20.022 | R2: 0.320 | BFE: 21.623
Metrics for LDi_SFS-1h:
	RMSE: 10.177 | R2: 0.824 | BFE: 11.698 | Inside 90%: 0.928
Metrics for LDi_SFS-2h:
	RMSE: 14.724 | R2: 0.632 | BFE: 19.107 | Inside 90%: 0.838
Metrics for persistence -1h:
	RMSE: 10.825 | R2: 0.767 | BFE: 18.488
Metrics for persistence -2h:
	RMSE: 15.072 | R2: 0.549 | BFE: 26.841
------------------------------------------------
Test storm number 94, from 2022-11-05 00:00:00 until 2022-11-13 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 23.130 | R2: -0.127 | BFE: 19.614
Metrics for LDi_SFS-1h:
	RMSE: 8.173 | R2: 0.859 | BFE: 14.734 | Inside 90%: 0.938
Metrics for LDi_SFS-2h:
	RMSE: 14.188 | R2: 0.576 | BFE: 27.121 | Inside 90%: 0.807
Metrics for persistence -1h:
	RMSE: 8.427 | R2: 0.825 | BFE: 17.553
Metrics for persistence -2h:
	RMSE: 12.920 | R2: 0.588 | BFE: 26.662
------------------------------------------------
Skipping blacklisted test storm 95 for SFS from 2023-02-25 00:00:00 - 2023-03-06 00:00:00
Test storm number 96, from 2023-03-21 00:00:00 until 2023-03-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 17.206 | R2: 0.672 | BFE: 22.693
Metrics for LDi_SFS-1h:
	RMSE: 11.743 | R2: 0.847 | BFE: 15.161 | Inside 90%: 0.859
Metrics for LDi_SFS-2h:
	RMSE: 14.529 | R2: 0.766 | BFE: 18.220 | Inside 90%: 0.806
Metrics for persistence -1h:
	RMSE: 12.313 | R2: 0.812 | BFE: 18.408
Metrics for persistence -2h:
	RMSE: 15.677 | R2: 0.696 | BFE: 21.707
------------------------------------------------
Test storm number 97, from 2023-04-21 00:00:00 until 2023-04-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 26.089 | R2: 0.302 | BFE: 27.028
Metrics for LDi_SFS-1h:
	RMSE: 13.367 | R2: 0.817 | BFE: 22.611 | Inside 90%: 0.857
Metrics for LDi_SFS-2h:
	RMSE: 16.444 | R2: 0.723 | BFE: 17.808 | Inside 90%: 0.692
Metrics for persistence -1h:
	RMSE: 14.354 | R2: 0.774 | BFE: 26.213
Metrics for persistence -2h:
	RMSE: 17.134 | R2: 0.678 | BFE: 38.045
------------------------------------------------
Test storm number 98, from 2023-08-03 00:00:00 until 2023-08-11 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 15.871 | R2: 0.168 | BFE: 23.734
Metrics for LDi_SFS-1h:
	RMSE: 9.916 | R2: 0.675 | BFE: 13.195 | Inside 90%: 0.912
Metrics for LDi_SFS-2h:
	RMSE: 14.148 | R2: 0.339 | BFE: 25.593 | Inside 90%: 0.800
Metrics for persistence -1h:
	RMSE: 9.687 | R2: 0.741 | BFE: 13.366
Metrics for persistence -2h:
	RMSE: 13.160 | R2: 0.522 | BFE: 20.913
------------------------------------------------
Test storm number 99, from 2023-11-03 00:00:00 until 2023-11-12 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 19.576 | R2: 0.747 | BFE: 32.981
Metrics for LDi_SFS-1h:
	RMSE: 13.478 | R2: 0.880 | BFE: 21.184 | Inside 90%: 0.948
Metrics for LDi_SFS-2h:
	RMSE: 18.168 | R2: 0.782 | BFE: 27.331 | Inside 90%: 0.878
Metrics for persistence -1h:
	RMSE: 15.208 | R2: 0.828 | BFE: 28.258
Metrics for persistence -2h:
	RMSE: 22.213 | R2: 0.633 | BFE: 40.945
------------------------------------------------
Test storm number 100, from 2023-11-23 00:00:00 until 2023-12-08 00:00:00, number of batches: 4896
Shapes of the input tensors: torch.Size([4800, 96, 6]), torch.Size([4800, 96, 5]), torch.Size([4800, 1]), torch.Size([4800, 2, 4]), (4800, 2)
Metrics for SYM_H:
	RMSE: 17.896 | R2: 0.459 | BFE: 26.478
Metrics for LDi_SFS-1h:
	RMSE: 10.235 | R2: 0.823 | BFE: 18.430 | Inside 90%: 0.921
Metrics for LDi_SFS-2h:
	RMSE: 16.565 | R2: 0.537 | BFE: 28.640 | Inside 90%: 0.831
Metrics for persistence -1h:
	RMSE: 12.147 | R2: 0.750 | BFE: 26.667
Metrics for persistence -2h:
	RMSE: 16.134 | R2: 0.560 | BFE: 36.332
------------------------------------------------
Test storm number 101, from 2024-03-01 00:00:00 until 2024-03-09 00:00:00, number of batches: 2881
Shapes of the input tensors: torch.Size([2785, 96, 6]), torch.Size([2785, 96, 5]), torch.Size([2785, 1]), torch.Size([2785, 2, 4]), (2785, 2)
Metrics for SYM_H:
	RMSE: 15.705 | R2: 0.646 | BFE: 22.971
Metrics for LDi_SFS-1h:
	RMSE: 9.744 | R2: 0.864 | BFE: 17.515 | Inside 90%: 0.919
Metrics for LDi_SFS-2h:
	RMSE: 14.500 | R2: 0.698 | BFE: 22.575 | Inside 90%: 0.855
Metrics for persistence -1h:
	RMSE: 11.339 | R2: 0.785 | BFE: 24.680
Metrics for persistence -2h:
	RMSE: 16.460 | R2: 0.548 | BFE: 34.533
------------------------------------------------
Test storm number 102, from 2024-03-22 00:00:00 until 2024-03-30 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 14.236 | R2: 0.748 | BFE: 22.026
Metrics for LDi_SFS-1h:
	RMSE: 12.197 | R2: 0.815 | BFE: 26.605 | Inside 90%: 0.876
Metrics for LDi_SFS-2h:
	RMSE: 20.900 | R2: 0.457 | BFE: 49.039 | Inside 90%: 0.763
Metrics for persistence -1h:
	RMSE: 17.764 | R2: 0.629 | BFE: 29.227
Metrics for persistence -2h:
	RMSE: 23.008 | R2: 0.378 | BFE: 36.053
------------------------------------------------
Test storm number 103, from 2024-04-17 00:00:00 until 2024-04-25 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 13.368 | R2: 0.653 | BFE: 10.593
Metrics for LDi_SFS-1h:
	RMSE: 8.805 | R2: 0.849 | BFE: 9.062 | Inside 90%: 0.854
Metrics for LDi_SFS-2h:
	RMSE: 12.516 | R2: 0.696 | BFE: 12.741 | Inside 90%: 0.740
Metrics for persistence -1h:
	RMSE: 9.925 | R2: 0.819 | BFE: 18.568
Metrics for persistence -2h:
	RMSE: 12.577 | R2: 0.710 | BFE: 19.745
------------------------------------------------
Test storm number 104, from 2024-04-30 00:00:00 until 2024-05-24 00:00:00, number of batches: 7488
Shapes of the input tensors: torch.Size([7392, 96, 6]), torch.Size([7392, 96, 5]), torch.Size([7392, 1]), torch.Size([7392, 2, 4]), (7392, 2)
Metrics for SYM_H:
	RMSE: 28.336 | R2: 0.742 | BFE: 60.099
Metrics for LDi_SFS-1h:
	RMSE: 17.987 | R2: 0.896 | BFE: 41.152 | Inside 90%: 0.915
Metrics for LDi_SFS-2h:
	RMSE: 24.573 | R2: 0.806 | BFE: 56.434 | Inside 90%: 0.819
Metrics for persistence -1h:
	RMSE: 21.598 | R2: 0.842 | BFE: 52.718
Metrics for persistence -2h:
	RMSE: 29.761 | R2: 0.699 | BFE: 86.095
------------------------------------------------
Test storm number 105, from 2024-06-26 00:00:00 until 2024-07-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 21.171 | R2: -0.058 | BFE: 23.234
Metrics for LDi_SFS-1h:
	RMSE: 9.099 | R2: 0.804 | BFE: 12.441 | Inside 90%: 0.909
Metrics for LDi_SFS-2h:
	RMSE: 12.458 | R2: 0.634 | BFE: 13.091 | Inside 90%: 0.838
Metrics for persistence -1h:
	RMSE: 9.381 | R2: 0.772 | BFE: 22.081
Metrics for persistence -2h:
	RMSE: 11.548 | R2: 0.655 | BFE: 24.495
------------------------------------------------
Test storm number 106, from 2024-08-02 00:00:00 until 2024-08-19 00:00:00, number of batches: 5472
Shapes of the input tensors: torch.Size([5376, 96, 6]), torch.Size([5376, 96, 5]), torch.Size([5376, 1]), torch.Size([5376, 2, 4]), (5376, 2)
Metrics for SYM_H:
	RMSE: 17.940 | R2: 0.774 | BFE: 19.602
Metrics for LDi_SFS-1h:
	RMSE: 11.579 | R2: 0.906 | BFE: 15.189 | Inside 90%: 0.910
Metrics for LDi_SFS-2h:
	RMSE: 16.474 | R2: 0.809 | BFE: 25.396 | Inside 90%: 0.814
Metrics for persistence -1h:
	RMSE: 12.793 | R2: 0.874 | BFE: 16.473
Metrics for persistence -2h:
	RMSE: 16.510 | R2: 0.790 | BFE: 23.099
------------------------------------------------
Test storm number 107, from 2024-09-10 00:00:00 until 2024-09-23 00:00:00, number of batches: 4320
Shapes of the input tensors: torch.Size([4224, 96, 6]), torch.Size([4224, 96, 5]), torch.Size([4224, 1]), torch.Size([4224, 2, 4]), (4224, 2)
Metrics for SYM_H:
	RMSE: 21.042 | R2: 0.609 | BFE: 30.159
Metrics for LDi_SFS-1h:
	RMSE: 14.077 | R2: 0.825 | BFE: 20.871 | Inside 90%: 0.846
Metrics for LDi_SFS-2h:
	RMSE: 20.517 | R2: 0.628 | BFE: 40.872 | Inside 90%: 0.739
Metrics for persistence -1h:
	RMSE: 15.263 | R2: 0.788 | BFE: 32.257
Metrics for persistence -2h:
	RMSE: 19.886 | R2: 0.639 | BFE: 40.961
------------------------------------------------
Test storm number 108, from 2024-10-05 00:00:00 until 2024-10-17 00:00:00, number of batches: 4032
Shapes of the input tensors: torch.Size([3936, 96, 6]), torch.Size([3936, 96, 5]), torch.Size([3936, 1]), torch.Size([3936, 2, 4]), (3936, 2)
Metrics for SYM_H:
	RMSE: 28.854 | R2: 0.760 | BFE: 49.262
Metrics for LDi_SFS-1h:
	RMSE: 21.441 | R2: 0.868 | BFE: 43.541 | Inside 90%: 0.817
Metrics for LDi_SFS-2h:
	RMSE: 28.315 | R2: 0.769 | BFE: 50.281 | Inside 90%: 0.695
Metrics for persistence -1h:
	RMSE: 21.882 | R2: 0.851 | BFE: 41.109
Metrics for persistence -2h:
	RMSE: 28.303 | R2: 0.751 | BFE: 51.562
------------------------------------------------
Test storm number 109, from 2024-11-07 00:00:00 until 2024-11-15 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 13.785 | R2: 0.766 | BFE: 14.788
Metrics for LDi_SFS-1h:
	RMSE: 11.795 | R2: 0.829 | BFE: 12.739 | Inside 90%: 0.899
Metrics for LDi_SFS-2h:
	RMSE: 15.907 | R2: 0.688 | BFE: 13.854 | Inside 90%: 0.776
Metrics for persistence -1h:
	RMSE: 12.545 | R2: 0.780 | BFE: 15.204
Metrics for persistence -2h:
	RMSE: 17.068 | R2: 0.592 | BFE: 21.196
------------------------------------------------
Metrics for the MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,SFS,89,50.584,12.795,22.758,0.570,30.365999,47.285999,9.126,13.773,16.443,22.648,0.775,0.574,0.895,0.772
1,SFS,90,18.339,14.217,18.635,0.114,10.038000,12.969000,7.780,11.080,11.153,14.922,0.683,0.432,0.853,0.767
2,SFS,91,20.574,14.574,23.527,0.360,14.848000,22.636000,7.263,11.410,11.551,17.014,0.846,0.665,0.924,0.825
3,SFS,92,27.901,11.100,16.285,0.469,26.235001,32.936001,8.957,12.779,13.471,17.731,0.637,0.371,0.800,0.690
4,SFS,93,21.623,15.902,20.022,0.320,11.698000,19.107000,7.090,10.856,10.177,14.724,0.824,0.632,0.928,0.838
5,SFS,94,19.614,20.399,23.130,-0.127,14.734000,27.121000,5.870,10.256,8.173,14.188,0.859,0.576,0.938,0.807
6,SFS,96,22.693,10.064,17.206,0.672,15.161000,18.219999,7.102,9.703,11.743,14.529,0.847,0.766,0.859,0.806
7,SFS,97,27.028,17.498,26.089,0.302,22.611000,17.808001,8.693,12.191,13.367,16.444,0.817,0.723,0.857,0.692
8,SFS,98,23.734,11.655,15.871,0.168,13.195000,25.593000,6.429,9.741,9.916,14.148,0.675,0.339,0.912,0.800
9,SFS,99,32.981,13.406,19.576,0.747,21.184000,27.330999,8.314,12.253,13.478,18.168,0.880,0.782,0.948,0.878
10,SFS,100,26.478,15.536,17.896,0.459,18.430000,28.639999,6.563,10.212,10.235,16.565,0.823,0.537,0.921,0.831
11,SFS,101,22.971,12.448,15.705,0.646,17.514999,22.575001,6.414,9.531,9.744,14.500,0.864,0.698,0.919,0.855
12,SFS,102,22.026,10.362,14.236,0.748,26.605000,49.039001,7.520,11.908,12.197,20.900,0.815,0.457,0.876,0.763
13,SFS,103,10.593,10.464,13.368,0.653,9.062000,12.741000,6.257,9.329,8.805,12.516,0.849,0.696,0.854,0.740
14,SFS,104,60.099,16.203,28.336,0.742,41.152000,56.433998,9.245,13.624,17.987,24.573,0.896,0.806,0.915,0.819
15,SFS,105,23.234,17.495,21.171,-0.058,12.441000,13.091000,6.502,9.494,9.099,12.458,0.804,0.634,0.909,0.838
16,SFS,106,19.602,12.373,17.940,0.774,15.189000,25.396000,7.750,11.426,11.579,16.474,0.906,0.809,0.910,0.814
17,SFS,107,30.159,14.309,21.042,0.609,20.871000,40.872002,8.788,13.171,14.077,20.517,0.825,0.628,0.846,0.739
18,SFS,108,49.262,20.318,28.854,0.760,43.541000,50.280998,11.917,16.570,21.441,28.315,0.868,0.769,0.817,0.695
19,SFS,109,14.788,10.577,13.785,0.766,12.739000,13.854000,7.948,11.561,11.795,15.907,0.829,0.688,0.899,0.776
20,SFS,Mean,27.214,14.085,19.772,0.485,19.881001,28.195999,7.776,11.543,12.322,17.362,0.816,0.629,0.889,0.787
21,SFS,Global,54.335,14.339,21.087,0.674,45.664001,56.500000,7.964,11.801,13.368,18.674,0.869,0.744,0.891,0.789

Mean and global MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
20,SFS,Mean,27.214,14.085,19.772,0.485,19.881001,28.195999,7.776,11.543,12.322,17.362,0.816,0.629,0.889,0.787
21,SFS,Global,54.335,14.339,21.087,0.674,45.664001,56.500000,7.964,11.801,13.368,18.674,0.869,0.744,0.891,0.789

           Station  BFE SYM-H  DTW SYM-H  RMSE SYM-H  R2 SYM_H
StormIndex
Mean           SFS     27.214     14.085      19.772     0.485
Global         SFS     54.335     14.339      21.087     0.674
Metrics for persistence -2h:
	RMSE: 14.739 | R2: 0.823 | BFE: 52.602
Metrics for persistence -2h:
	RMSE: 19.692 | R2: 0.685 | BFE: 85.238
Diff BFE (SYM-H nowcast - LDi forecast 1h):
Total: 8.672
Diff BFE (SYM-H nowcast - LDi forecast 2h):
Total: -2.165

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,SFS,89,50.583509,12.794882,22.757847,0.569807,30.365574,47.286335,9.126262,13.773238,16.442875,22.647701,0.775427,0.573961,0.894717,0.772464
1,SFS,90,18.338817,14.217015,18.635384,0.114263,10.037889,12.968570,7.780155,11.080265,11.153233,14.922265,0.682729,0.432066,0.853362,0.767462
2,SFS,91,20.574443,14.574017,23.526901,0.359759,14.847600,22.636118,7.262834,11.409846,11.551359,17.014166,0.845659,0.665161,0.924078,0.825163
3,SFS,92,27.901009,11.100243,16.285482,0.469231,26.235157,32.935940,8.957222,12.778894,13.470980,17.730909,0.636836,0.370833,0.800434,0.689805
4,SFS,93,21.622768,15.902404,20.022205,0.319988,11.698040,19.106506,7.089957,10.855685,10.177018,14.724424,0.824315,0.632236,0.928416,0.838178
5,SFS,94,19.613545,20.398529,23.130234,-0.127045,14.734414,27.120859,5.869899,10.255680,8.172853,14.188438,0.859289,0.575917,0.937961,0.807375
6,SFS,96,22.692748,10.063745,17.206263,0.671795,15.160609,18.219549,7.102405,9.703079,11.742761,14.529258,0.847133,0.765977,0.858851,0.806016
7,SFS,97,27.028444,17.497753,26.088697,0.302336,22.611456,17.807711,8.692578,12.191030,13.367096,16.444317,0.816846,0.722813,0.856922,0.691863
8,SFS,98,23.734055,11.655267,15.871263,0.168236,13.195260,25.592720,6.428825,9.740507,9.916247,14.147732,0.675308,0.339077,0.911931,0.800000
9,SFS,99,32.981122,13.405916,19.575520,0.746528,21.184053,27.331356,8.313858,12.252512,13.477529,18.168112,0.879850,0.781665,0.948322,0.878133
10,SFS,100,26.478261,15.536235,17.896236,0.459416,18.429525,28.640165,6.562989,10.211841,10.235223,16.565365,0.823179,0.536828,0.920620,0.831289
11,SFS,101,22.971226,12.447610,15.704622,0.646102,17.514809,22.574940,6.413786,9.530502,9.743562,14.499530,0.863775,0.698331,0.918872,0.855098
12,SFS,102,22.026120,10.361536,14.236487,0.748002,26.605059,49.039352,7.519669,11.908437,12.197108,20.899521,0.815028,0.456919,0.876356,0.762690
13,SFS,103,10.592741,10.464139,13.367560,0.653008,9.062235,12.741279,6.257370,9.328887,8.805223,12.515718,0.849445,0.695823,0.853796,0.740130
14,SFS,104,60.098912,16.203421,28.336256,0.742141,41.152168,56.433952,9.244905,13.623737,17.986996,24.572857,0.896100,0.806086,0.915232,0.818603
15,SFS,105,23.234352,17.495219,21.171257,-0.058429,12.440747,13.091413,6.502007,9.494244,9.099220,12.458061,0.804486,0.633504,0.909328,0.837744
16,SFS,106,19.601743,12.372632,17.940290,0.773987,15.188981,25.395517,7.749968,11.425747,11.578652,16.474314,0.905856,0.809415,0.909741,0.814376
17,SFS,107,30.159321,14.309191,21.042376,0.608678,20.870857,40.871891,8.788192,13.170845,14.077144,20.517166,0.824865,0.627969,0.846462,0.738852
18,SFS,108,49.262062,20.318016,28.854397,0.760079,43.540691,50.280548,11.917035,16.569822,21.440960,28.314796,0.867525,0.768969,0.817183,0.694822
19,SFS,109,14.787611,10.576994,13.784649,0.765987,12.738619,13.854466,7.948474,11.561064,11.794986,15.907008,0.828666,0.688379,0.899349,0.776139
20,SFS,Mean,27.214140,14.084738,19.771696,0.484693,19.880688,28.196461,7.776420,11.543293,12.321551,17.362083,0.816116,0.629096,0.889097,0.787310
21,SFS,Global,54.335281,14.338941,21.086529,0.674201,45.663631,56.499844,7.964231,11.801253,13.367838,18.673998,0.869063,0.744486,0.890687,0.789451

Testing model RELDi
Evaluating for on station SFS
Test storm number 89, from 2017-09-06 00:00:00 until 2017-09-15 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 22.758 | R2: 0.570 | BFE: 50.584
Metrics for LDi_SFS-1h:
	RMSE: 16.443 | R2: 0.775 | BFE: 30.366 | Inside 90%: 0.895
Metrics for LDi_SFS-2h:
	RMSE: 22.648 | R2: 0.574 | BFE: 47.286 | Inside 90%: 0.772
Metrics for persistence -1h:
	RMSE: 17.885 | R2: 0.695 | BFE: 25.003
Metrics for persistence -2h:
	RMSE: 23.706 | R2: 0.465 | BFE: 34.913
------------------------------------------------
Test storm number 90, from 2017-09-26 00:00:00 until 2017-10-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 18.635 | R2: 0.114 | BFE: 18.339
Metrics for LDi_SFS-1h:
	RMSE: 11.153 | R2: 0.683 | BFE: 10.038 | Inside 90%: 0.853
Metrics for LDi_SFS-2h:
	RMSE: 14.922 | R2: 0.432 | BFE: 12.969 | Inside 90%: 0.767
Metrics for persistence -1h:
	RMSE: 11.376 | R2: 0.617 | BFE: 11.893
Metrics for persistence -2h:
	RMSE: 14.803 | R2: 0.352 | BFE: 14.430
------------------------------------------------
Test storm number 91, from 2018-08-24 00:00:00 until 2018-09-01 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 23.527 | R2: 0.360 | BFE: 20.574
Metrics for LDi_SFS-1h:
	RMSE: 11.551 | R2: 0.846 | BFE: 14.848 | Inside 90%: 0.924
Metrics for LDi_SFS-2h:
	RMSE: 17.014 | R2: 0.665 | BFE: 22.636 | Inside 90%: 0.825
Metrics for persistence -1h:
	RMSE: 12.051 | R2: 0.805 | BFE: 17.152
Metrics for persistence -2h:
	RMSE: 16.828 | R2: 0.620 | BFE: 22.815
------------------------------------------------
Test storm number 92, from 2021-11-02 00:00:00 until 2021-11-10 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 16.285 | R2: 0.469 | BFE: 27.901
Metrics for LDi_SFS-1h:
	RMSE: 13.471 | R2: 0.637 | BFE: 26.235 | Inside 90%: 0.800
Metrics for LDi_SFS-2h:
	RMSE: 17.731 | R2: 0.371 | BFE: 32.936 | Inside 90%: 0.690
Metrics for persistence -1h:
	RMSE: 13.416 | R2: 0.594 | BFE: 25.175
Metrics for persistence -2h:
	RMSE: 17.587 | R2: 0.303 | BFE: 28.312
------------------------------------------------
Test storm number 93, from 2022-01-12 00:00:00 until 2022-01-20 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 20.022 | R2: 0.320 | BFE: 21.623
Metrics for LDi_SFS-1h:
	RMSE: 10.177 | R2: 0.824 | BFE: 11.698 | Inside 90%: 0.928
Metrics for LDi_SFS-2h:
	RMSE: 14.724 | R2: 0.632 | BFE: 19.107 | Inside 90%: 0.838
Metrics for persistence -1h:
	RMSE: 10.825 | R2: 0.767 | BFE: 18.488
Metrics for persistence -2h:
	RMSE: 15.072 | R2: 0.549 | BFE: 26.841
------------------------------------------------
Test storm number 94, from 2022-11-05 00:00:00 until 2022-11-13 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 23.130 | R2: -0.127 | BFE: 19.614
Metrics for LDi_SFS-1h:
	RMSE: 8.173 | R2: 0.859 | BFE: 14.734 | Inside 90%: 0.938
Metrics for LDi_SFS-2h:
	RMSE: 14.188 | R2: 0.576 | BFE: 27.121 | Inside 90%: 0.807
Metrics for persistence -1h:
	RMSE: 8.427 | R2: 0.825 | BFE: 17.553
Metrics for persistence -2h:
	RMSE: 12.920 | R2: 0.588 | BFE: 26.662
------------------------------------------------
Skipping blacklisted test storm 95 for SFS from 2023-02-25 00:00:00 - 2023-03-06 00:00:00
Test storm number 96, from 2023-03-21 00:00:00 until 2023-03-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 17.206 | R2: 0.672 | BFE: 22.693
Metrics for LDi_SFS-1h:
	RMSE: 11.743 | R2: 0.847 | BFE: 15.161 | Inside 90%: 0.859
Metrics for LDi_SFS-2h:
	RMSE: 14.529 | R2: 0.766 | BFE: 18.220 | Inside 90%: 0.806
Metrics for persistence -1h:
	RMSE: 12.313 | R2: 0.812 | BFE: 18.408
Metrics for persistence -2h:
	RMSE: 15.677 | R2: 0.696 | BFE: 21.707
------------------------------------------------
Test storm number 97, from 2023-04-21 00:00:00 until 2023-04-30 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 26.089 | R2: 0.302 | BFE: 27.028
Metrics for LDi_SFS-1h:
	RMSE: 13.367 | R2: 0.817 | BFE: 22.611 | Inside 90%: 0.857
Metrics for LDi_SFS-2h:
	RMSE: 16.444 | R2: 0.723 | BFE: 17.808 | Inside 90%: 0.692
Metrics for persistence -1h:
	RMSE: 14.354 | R2: 0.774 | BFE: 26.213
Metrics for persistence -2h:
	RMSE: 17.134 | R2: 0.678 | BFE: 38.045
------------------------------------------------
Test storm number 98, from 2023-08-03 00:00:00 until 2023-08-11 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 15.871 | R2: 0.168 | BFE: 23.734
Metrics for LDi_SFS-1h:
	RMSE: 9.916 | R2: 0.675 | BFE: 13.195 | Inside 90%: 0.912
Metrics for LDi_SFS-2h:
	RMSE: 14.148 | R2: 0.339 | BFE: 25.593 | Inside 90%: 0.800
Metrics for persistence -1h:
	RMSE: 9.687 | R2: 0.741 | BFE: 13.366
Metrics for persistence -2h:
	RMSE: 13.160 | R2: 0.522 | BFE: 20.913
------------------------------------------------
Test storm number 99, from 2023-11-03 00:00:00 until 2023-11-12 00:00:00, number of batches: 3168
Shapes of the input tensors: torch.Size([3072, 96, 6]), torch.Size([3072, 96, 5]), torch.Size([3072, 1]), torch.Size([3072, 2, 4]), (3072, 2)
Metrics for SYM_H:
	RMSE: 19.576 | R2: 0.747 | BFE: 32.981
Metrics for LDi_SFS-1h:
	RMSE: 13.478 | R2: 0.880 | BFE: 21.184 | Inside 90%: 0.948
Metrics for LDi_SFS-2h:
	RMSE: 18.168 | R2: 0.782 | BFE: 27.331 | Inside 90%: 0.878
Metrics for persistence -1h:
	RMSE: 15.208 | R2: 0.828 | BFE: 28.258
Metrics for persistence -2h:
	RMSE: 22.213 | R2: 0.633 | BFE: 40.945
------------------------------------------------
Test storm number 100, from 2023-11-23 00:00:00 until 2023-12-08 00:00:00, number of batches: 4896
Shapes of the input tensors: torch.Size([4800, 96, 6]), torch.Size([4800, 96, 5]), torch.Size([4800, 1]), torch.Size([4800, 2, 4]), (4800, 2)
Metrics for SYM_H:
	RMSE: 17.896 | R2: 0.459 | BFE: 26.478
Metrics for LDi_SFS-1h:
	RMSE: 10.235 | R2: 0.823 | BFE: 18.430 | Inside 90%: 0.921
Metrics for LDi_SFS-2h:
	RMSE: 16.565 | R2: 0.537 | BFE: 28.640 | Inside 90%: 0.831
Metrics for persistence -1h:
	RMSE: 12.147 | R2: 0.750 | BFE: 26.667
Metrics for persistence -2h:
	RMSE: 16.134 | R2: 0.560 | BFE: 36.332
------------------------------------------------
Test storm number 101, from 2024-03-01 00:00:00 until 2024-03-09 00:00:00, number of batches: 2881
Shapes of the input tensors: torch.Size([2785, 96, 6]), torch.Size([2785, 96, 5]), torch.Size([2785, 1]), torch.Size([2785, 2, 4]), (2785, 2)
Metrics for SYM_H:
	RMSE: 15.705 | R2: 0.646 | BFE: 22.971
Metrics for LDi_SFS-1h:
	RMSE: 9.744 | R2: 0.864 | BFE: 17.515 | Inside 90%: 0.919
Metrics for LDi_SFS-2h:
	RMSE: 14.500 | R2: 0.698 | BFE: 22.575 | Inside 90%: 0.855
Metrics for persistence -1h:
	RMSE: 11.339 | R2: 0.785 | BFE: 24.680
Metrics for persistence -2h:
	RMSE: 16.460 | R2: 0.548 | BFE: 34.533
------------------------------------------------
Test storm number 102, from 2024-03-22 00:00:00 until 2024-03-30 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 14.236 | R2: 0.748 | BFE: 22.026
Metrics for LDi_SFS-1h:
	RMSE: 12.197 | R2: 0.815 | BFE: 26.605 | Inside 90%: 0.876
Metrics for LDi_SFS-2h:
	RMSE: 20.900 | R2: 0.457 | BFE: 49.039 | Inside 90%: 0.763
Metrics for persistence -1h:
	RMSE: 17.764 | R2: 0.629 | BFE: 29.227
Metrics for persistence -2h:
	RMSE: 23.008 | R2: 0.378 | BFE: 36.053
------------------------------------------------
Test storm number 103, from 2024-04-17 00:00:00 until 2024-04-25 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 13.368 | R2: 0.653 | BFE: 10.593
Metrics for LDi_SFS-1h:
	RMSE: 8.805 | R2: 0.849 | BFE: 9.062 | Inside 90%: 0.854
Metrics for LDi_SFS-2h:
	RMSE: 12.516 | R2: 0.696 | BFE: 12.741 | Inside 90%: 0.740
Metrics for persistence -1h:
	RMSE: 9.925 | R2: 0.819 | BFE: 18.568
Metrics for persistence -2h:
	RMSE: 12.577 | R2: 0.710 | BFE: 19.745
------------------------------------------------
Test storm number 104, from 2024-04-30 00:00:00 until 2024-05-24 00:00:00, number of batches: 7488
Shapes of the input tensors: torch.Size([7392, 96, 6]), torch.Size([7392, 96, 5]), torch.Size([7392, 1]), torch.Size([7392, 2, 4]), (7392, 2)
Metrics for SYM_H:
	RMSE: 28.336 | R2: 0.742 | BFE: 60.099
Metrics for LDi_SFS-1h:
	RMSE: 17.987 | R2: 0.896 | BFE: 41.152 | Inside 90%: 0.915
Metrics for LDi_SFS-2h:
	RMSE: 24.573 | R2: 0.806 | BFE: 56.434 | Inside 90%: 0.819
Metrics for persistence -1h:
	RMSE: 21.598 | R2: 0.842 | BFE: 52.718
Metrics for persistence -2h:
	RMSE: 29.761 | R2: 0.699 | BFE: 86.095
------------------------------------------------
Test storm number 105, from 2024-06-26 00:00:00 until 2024-07-04 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 21.171 | R2: -0.058 | BFE: 23.234
Metrics for LDi_SFS-1h:
	RMSE: 9.099 | R2: 0.804 | BFE: 12.441 | Inside 90%: 0.909
Metrics for LDi_SFS-2h:
	RMSE: 12.458 | R2: 0.634 | BFE: 13.091 | Inside 90%: 0.838
Metrics for persistence -1h:
	RMSE: 9.381 | R2: 0.772 | BFE: 22.081
Metrics for persistence -2h:
	RMSE: 11.548 | R2: 0.655 | BFE: 24.495
------------------------------------------------
Test storm number 106, from 2024-08-02 00:00:00 until 2024-08-19 00:00:00, number of batches: 5472
Shapes of the input tensors: torch.Size([5376, 96, 6]), torch.Size([5376, 96, 5]), torch.Size([5376, 1]), torch.Size([5376, 2, 4]), (5376, 2)
Metrics for SYM_H:
	RMSE: 17.940 | R2: 0.774 | BFE: 19.602
Metrics for LDi_SFS-1h:
	RMSE: 11.579 | R2: 0.906 | BFE: 15.189 | Inside 90%: 0.910
Metrics for LDi_SFS-2h:
	RMSE: 16.474 | R2: 0.809 | BFE: 25.396 | Inside 90%: 0.814
Metrics for persistence -1h:
	RMSE: 12.793 | R2: 0.874 | BFE: 16.473
Metrics for persistence -2h:
	RMSE: 16.510 | R2: 0.790 | BFE: 23.099
------------------------------------------------
Test storm number 107, from 2024-09-10 00:00:00 until 2024-09-23 00:00:00, number of batches: 4320
Shapes of the input tensors: torch.Size([4224, 96, 6]), torch.Size([4224, 96, 5]), torch.Size([4224, 1]), torch.Size([4224, 2, 4]), (4224, 2)
Metrics for SYM_H:
	RMSE: 21.042 | R2: 0.609 | BFE: 30.159
Metrics for LDi_SFS-1h:
	RMSE: 14.077 | R2: 0.825 | BFE: 20.871 | Inside 90%: 0.846
Metrics for LDi_SFS-2h:
	RMSE: 20.517 | R2: 0.628 | BFE: 40.872 | Inside 90%: 0.739
Metrics for persistence -1h:
	RMSE: 15.263 | R2: 0.788 | BFE: 32.257
Metrics for persistence -2h:
	RMSE: 19.886 | R2: 0.639 | BFE: 40.961
------------------------------------------------
Test storm number 108, from 2024-10-05 00:00:00 until 2024-10-17 00:00:00, number of batches: 4032
Shapes of the input tensors: torch.Size([3936, 96, 6]), torch.Size([3936, 96, 5]), torch.Size([3936, 1]), torch.Size([3936, 2, 4]), (3936, 2)
Metrics for SYM_H:
	RMSE: 28.854 | R2: 0.760 | BFE: 49.262
Metrics for LDi_SFS-1h:
	RMSE: 21.441 | R2: 0.868 | BFE: 43.541 | Inside 90%: 0.817
Metrics for LDi_SFS-2h:
	RMSE: 28.315 | R2: 0.769 | BFE: 50.281 | Inside 90%: 0.695
Metrics for persistence -1h:
	RMSE: 21.882 | R2: 0.851 | BFE: 41.109
Metrics for persistence -2h:
	RMSE: 28.303 | R2: 0.751 | BFE: 51.562
------------------------------------------------
Test storm number 109, from 2024-11-07 00:00:00 until 2024-11-15 00:00:00, number of batches: 2880
Shapes of the input tensors: torch.Size([2784, 96, 6]), torch.Size([2784, 96, 5]), torch.Size([2784, 1]), torch.Size([2784, 2, 4]), (2784, 2)
Metrics for SYM_H:
	RMSE: 13.785 | R2: 0.766 | BFE: 14.788
Metrics for LDi_SFS-1h:
	RMSE: 11.795 | R2: 0.829 | BFE: 12.739 | Inside 90%: 0.899
Metrics for LDi_SFS-2h:
	RMSE: 15.907 | R2: 0.688 | BFE: 13.854 | Inside 90%: 0.776
Metrics for persistence -1h:
	RMSE: 12.545 | R2: 0.780 | BFE: 15.204
Metrics for persistence -2h:
	RMSE: 17.068 | R2: 0.592 | BFE: 21.196
------------------------------------------------
Metrics for the MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,SFS,89,50.584,12.795,22.758,0.570,30.365999,47.285999,9.126,13.773,16.443,22.648,0.775,0.574,0.895,0.772
1,SFS,90,18.339,14.217,18.635,0.114,10.038000,12.969000,7.780,11.080,11.153,14.922,0.683,0.432,0.853,0.767
2,SFS,91,20.574,14.574,23.527,0.360,14.848000,22.636000,7.263,11.410,11.551,17.014,0.846,0.665,0.924,0.825
3,SFS,92,27.901,11.100,16.285,0.469,26.235001,32.936001,8.957,12.779,13.471,17.731,0.637,0.371,0.800,0.690
4,SFS,93,21.623,15.902,20.022,0.320,11.698000,19.107000,7.090,10.856,10.177,14.724,0.824,0.632,0.928,0.838
5,SFS,94,19.614,20.399,23.130,-0.127,14.734000,27.121000,5.870,10.256,8.173,14.188,0.859,0.576,0.938,0.807
6,SFS,96,22.693,10.064,17.206,0.672,15.161000,18.219999,7.102,9.703,11.743,14.529,0.847,0.766,0.859,0.806
7,SFS,97,27.028,17.498,26.089,0.302,22.611000,17.808001,8.693,12.191,13.367,16.444,0.817,0.723,0.857,0.692
8,SFS,98,23.734,11.655,15.871,0.168,13.195000,25.593000,6.429,9.741,9.916,14.148,0.675,0.339,0.912,0.800
9,SFS,99,32.981,13.406,19.576,0.747,21.184000,27.330999,8.314,12.253,13.478,18.168,0.880,0.782,0.948,0.878
10,SFS,100,26.478,15.536,17.896,0.459,18.430000,28.639999,6.563,10.212,10.235,16.565,0.823,0.537,0.921,0.831
11,SFS,101,22.971,12.448,15.705,0.646,17.514999,22.575001,6.414,9.531,9.744,14.500,0.864,0.698,0.919,0.855
12,SFS,102,22.026,10.362,14.236,0.748,26.605000,49.039001,7.520,11.908,12.197,20.900,0.815,0.457,0.876,0.763
13,SFS,103,10.593,10.464,13.368,0.653,9.062000,12.741000,6.257,9.329,8.805,12.516,0.849,0.696,0.854,0.740
14,SFS,104,60.099,16.203,28.336,0.742,41.152000,56.433998,9.245,13.624,17.987,24.573,0.896,0.806,0.915,0.819
15,SFS,105,23.234,17.495,21.171,-0.058,12.441000,13.091000,6.502,9.494,9.099,12.458,0.804,0.634,0.909,0.838
16,SFS,106,19.602,12.373,17.940,0.774,15.189000,25.396000,7.750,11.426,11.579,16.474,0.906,0.809,0.910,0.814
17,SFS,107,30.159,14.309,21.042,0.609,20.871000,40.872002,8.788,13.171,14.077,20.517,0.825,0.628,0.846,0.739
18,SFS,108,49.262,20.318,28.854,0.760,43.541000,50.280998,11.917,16.570,21.441,28.315,0.868,0.769,0.817,0.695
19,SFS,109,14.788,10.577,13.785,0.766,12.739000,13.854000,7.948,11.561,11.795,15.907,0.829,0.688,0.899,0.776
20,SFS,Mean,27.214,14.085,19.772,0.485,19.881001,28.195999,7.776,11.543,12.322,17.362,0.816,0.629,0.889,0.787
21,SFS,Global,54.335,14.339,21.087,0.674,45.664001,56.500000,7.964,11.801,13.368,18.674,0.869,0.744,0.891,0.789

Mean and global MSE output

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
20,SFS,Mean,27.214,14.085,19.772,0.485,19.881001,28.195999,7.776,11.543,12.322,17.362,0.816,0.629,0.889,0.787
21,SFS,Global,54.335,14.339,21.087,0.674,45.664001,56.500000,7.964,11.801,13.368,18.674,0.869,0.744,0.891,0.789

           Station  BFE SYM-H  DTW SYM-H  RMSE SYM-H  R2 SYM_H
StormIndex
Mean           SFS     27.214     14.085      19.772     0.485
Global         SFS     54.335     14.339      21.087     0.674
Metrics for persistence -2h:
	RMSE: 14.739 | R2: 0.823 | BFE: 52.602
Metrics for persistence -2h:
	RMSE: 19.692 | R2: 0.685 | BFE: 85.238
Diff BFE (SYM-H nowcast - LDi forecast 1h):
Total: 8.672
Diff BFE (SYM-H nowcast - LDi forecast 2h):
Total: -2.165

,Station,StormIndex,BFE SYM-H,DTW SYM-H,RMSE SYM-H,R2 SYM_H,BFE 1h,BFE 2h,DTW 1h,DTW 2h,RMSE 1h,RMSE 2h,R2 1h,R2 2h,inside 90% 1h,inside 90% 2h
0,SFS,89,50.583509,12.794882,22.757847,0.569807,30.365574,47.286335,9.126262,13.773238,16.442875,22.647701,0.775427,0.573961,0.894717,0.772464
1,SFS,90,18.338817,14.217015,18.635384,0.114263,10.037889,12.968570,7.780155,11.080265,11.153233,14.922265,0.682729,0.432066,0.853362,0.767462
2,SFS,91,20.574443,14.574017,23.526901,0.359759,14.847600,22.636118,7.262834,11.409846,11.551359,17.014166,0.845659,0.665161,0.924078,0.825163
3,SFS,92,27.901009,11.100243,16.285482,0.469231,26.235157,32.935940,8.957222,12.778894,13.470980,17.730909,0.636836,0.370833,0.800434,0.689805
4,SFS,93,21.622768,15.902404,20.022205,0.319988,11.698040,19.106506,7.089957,10.855685,10.177018,14.724424,0.824315,0.632236,0.928416,0.838178
5,SFS,94,19.613545,20.398529,23.130234,-0.127045,14.734414,27.120859,5.869899,10.255680,8.172853,14.188438,0.859289,0.575917,0.937961,0.807375
6,SFS,96,22.692748,10.063745,17.206263,0.671795,15.160609,18.219549,7.102405,9.703079,11.742761,14.529258,0.847133,0.765977,0.858851,0.806016
7,SFS,97,27.028444,17.497753,26.088697,0.302336,22.611456,17.807711,8.692578,12.191030,13.367096,16.444317,0.816846,0.722813,0.856922,0.691863
8,SFS,98,23.734055,11.655267,15.871263,0.168236,13.195260,25.592720,6.428825,9.740507,9.916247,14.147732,0.675308,0.339077,0.911931,0.800000
9,SFS,99,32.981122,13.405916,19.575520,0.746528,21.184053,27.331356,8.313858,12.252512,13.477529,18.168112,0.879850,0.781665,0.948322,0.878133
10,SFS,100,26.478261,15.536235,17.896236,0.459416,18.429525,28.640165,6.562989,10.211841,10.235223,16.565365,0.823179,0.536828,0.920620,0.831289
11,SFS,101,22.971226,12.447610,15.704622,0.646102,17.514809,22.574940,6.413786,9.530502,9.743562,14.499530,0.863775,0.698331,0.918872,0.855098
12,SFS,102,22.026120,10.361536,14.236487,0.748002,26.605059,49.039352,7.519669,11.908437,12.197108,20.899521,0.815028,0.456919,0.876356,0.762690
13,SFS,103,10.592741,10.464139,13.367560,0.653008,9.062235,12.741279,6.257370,9.328887,8.805223,12.515718,0.849445,0.695823,0.853796,0.740130
14,SFS,104,60.098912,16.203421,28.336256,0.742141,41.152168,56.433952,9.244905,13.623737,17.986996,24.572857,0.896100,0.806086,0.915232,0.818603
15,SFS,105,23.234352,17.495219,21.171257,-0.058429,12.440747,13.091413,6.502007,9.494244,9.099220,12.458061,0.804486,0.633504,0.909328,0.837744
16,SFS,106,19.601743,12.372632,17.940290,0.773987,15.188981,25.395517,7.749968,11.425747,11.578652,16.474314,0.905856,0.809415,0.909741,0.814376
17,SFS,107,30.159321,14.309191,21.042376,0.608678,20.870857,40.871891,8.788192,13.170845,14.077144,20.517166,0.824865,0.627969,0.846462,0.738852
18,SFS,108,49.262062,20.318016,28.854397,0.760079,43.540691,50.280548,11.917035,16.569822,21.440960,28.314796,0.867525,0.768969,0.817183,0.694822
19,SFS,109,14.787611,10.576994,13.784649,0.765987,12.738619,13.854466,7.948474,11.561064,11.794986,15.907008,0.828666,0.688379,0.899349,0.776139
20,SFS,Mean,27.214140,14.084738,19.771696,0.484693,19.880688,28.196461,7.776420,11.543293,12.321551,17.362083,0.816116,0.629096,0.889097,0.787310
21,SFS,Global,54.335281,14.338941,21.086529,0.674201,45.663631,56.499844,7.964231,11.801253,13.367838,18.673998,0.869063,0.744486,0.890687,0.789451

In [23]:
summary_df

,Station,Global_BFE_SYM-H,Global_RMSE_SYM-H,Global_R2_SYM-H,Global_RMSE_1h,Global_BFE_1h,Global_R2_1h,Global_inside_90%_1h,Global_RMSE_2h,Global_BFE_2h,Global_R2_2h,Global_inside_90%_2h,RMSE_persistence-1h,BFE_persistence-1h,R2_persistence-1h,RMSE_persistence-2h,BFE_persistence-2h,R2_persistence-2h,Better BFE 1h,Better BFE 2h,Better RMSE 1h,Better RMSE 2h
0,ABG,44.530046,19.620636,0.830243,11.128581,25.633680,0.945389,0.911835,17.194424,40.916145,0.869631,0.796649,13.091836,36.519421,0.915998,19.043194,52.785847,0.822267,19/20,14/20,20/20,13/20
1,MMB,48.868305,21.841389,0.648062,12.723472,51.677444,0.880569,0.926617,17.774429,77.944939,0.766924,0.841804,13.975657,63.204327,0.839810,18.071266,73.889000,0.732165,19/21,9/21,20/21,19/21
2,CLF,73.669954,28.087835,0.064327,12.652555,64.437164,0.810135,0.933223,17.307835,74.647003,0.644718,0.858612,13.114584,66.488892,0.773754,17.000250,100.730858,0.619825,23/23,14/23,23/23,23/23
3,TUC,38.910315,21.551609,0.617346,12.726727,37.391785,0.866562,0.921512,16.995157,37.349285,0.762043,0.831022,13.454135,46.375568,0.834477,17.293234,54.432415,0.726537,19/23,14/23,22/23,19/23
4,HON,29.023123,14.656344,0.871474,8.921650,26.721169,0.952376,0.958948,13.616827,32.191723,0.889059,0.882958,10.060527,36.433723,0.932309,14.495803,45.654743,0.859469,22/23,12/23,23/23,14/23
5,SFS,54.335281,21.086529,0.674201,13.367838,45.663631,0.869063,0.890687,18.673998,56.499844,0.744486,0.789451,14.738920,52.602409,0.823343,19.692383,85.238220,0.684648,21/22,10/22,22/22,19/22

In [24]:
print("SYM-H metrics")
print(f'BFE: {summary_df[[f"Global_BFE_SYM-H"]].mean().sum():.3f}')
print(f'RMSE: {summary_df[[f"Global_RMSE_SYM-H"]].mean().sum():.3f}')
print("Forecast metrics")
for forecast_step in range(FORECAST_STEPS):
    print(
        f'BFE {forecast_step + 1}h: {summary_df[[f"Global_BFE_{forecast_step + 1}h"]].mean().sum():.3f}'
    )
    print(
        f'RMSE {forecast_step + 1}h: {summary_df[[f"Global_RMSE_{forecast_step + 1}h"]].mean().sum():.3f}'
    )

SYM-H metrics
BFE: 48.223
RMSE: 21.141
Forecast metrics
BFE 1h: 41.921
RMSE 1h: 11.920
BFE 2h: 53.258
RMSE 2h: 16.927

In [25]:
str_metrics = ""

for forecast_step in range(FORECAST_STEPS):
    str_metrics += f'BFE {forecast_step + 1}h: {summary_df[[f"Global_BFE_{forecast_step + 1}h"]].mean().sum():.3f}\nRMSE {forecast_step + 1}h: {summary_df[["Global_RMSE_1h"]].mean().sum():.3f}\n'

for forecast_step in range(FORECAST_STEPS):
    summary_df[f"Diff_{forecast_step + 1}h"] = (
        summary_df[f"Global_BFE_{forecast_step + 1}h"] - summary_df["Global_BFE_SYM-H"]
    )
    summary_df[f"Diff_RMSE_{forecast_step + 1}h"] = (
        summary_df[f"Global_RMSE_{forecast_step + 1}h"]
        - summary_df["Global_RMSE_SYM-H"]
    )
    str_metrics += f"Differences BFE {forecast_step + 1}h\n"
    print(f"Differences BFE {forecast_step + 1}h")
    str_metrics += (
        summary_df.set_index("Station")[f"Diff_{forecast_step + 1}h"]
        .round(3)
        .to_string()
    )
    print(
        summary_df.set_index("Station")[f"Diff_{forecast_step + 1}h"]
        .round(3)
        .to_string()
    )
    str_metrics += f"\nSum differences: {summary_df.set_index('Station')[f'Diff_{forecast_step + 1}h'].sum():.3f}\n"
    print(
        f"Sum differences {forecast_step + 1}h: {summary_df.set_index('Station')[f'Diff_{forecast_step + 1}h'].sum():.3f}"
    )

    str_metrics += f"Differences RMSE {forecast_step + 1}h\n"
    print(f"Differences RMSE {forecast_step + 1}h")
    str_metrics += (
        summary_df.set_index("Station")[f"Diff_RMSE_{forecast_step + 1}h"]
        .round(3)
        .to_string()
    )
    print(
        summary_df.set_index("Station")[f"Diff_RMSE_{forecast_step + 1}h"]
        .round(3)
        .to_string()
    )
    str_metrics += f"\nSum differences RMSE: {summary_df.set_index('Station')[f'Diff_RMSE_{forecast_step + 1}h'].sum():.3f}\n"
    print(
        f"Sum differences RMSE {forecast_step + 1}h: {summary_df.set_index('Station')[f'Diff_RMSE_{forecast_step + 1}h'].sum():.3f}"
    )

Differences BFE 1h
Station
ABG   -18.896
MMB     2.809
CLF    -9.233
TUC    -1.519
HON    -2.302
SFS    -8.672
Sum differences 1h: -37.812
Differences RMSE 1h
Station
ABG    -8.492
MMB    -9.118
CLF   -15.435
TUC    -8.825
HON    -5.735
SFS    -7.719
Sum differences RMSE 1h: -55.324
Differences BFE 2h
Station
ABG    -3.614
MMB    29.077
CLF     0.977
TUC    -1.561
HON     3.169
SFS     2.165
Sum differences 2h: 30.212
Differences RMSE 2h
Station
ABG    -2.426
MMB    -4.067
CLF   -10.780
TUC    -4.556
HON    -1.040
SFS    -2.413
Sum differences RMSE 2h: -25.282

In [26]:
cols_print = []
for forecast_step in range(FORECAST_STEPS):
    cols_print.append(f"Diff_{forecast_step + 1}h")
    cols_print.append(f"Better BFE {forecast_step + 1}h")
    cols_print.append(f"Diff_RMSE_{forecast_step + 1}h")
    cols_print.append(f"Better RMSE {forecast_step + 1}h")
print(summary_df.set_index("Station")[cols_print])

           Diff_1h Better BFE 1h  Diff_RMSE_1h Better RMSE 1h    Diff_2h  \
Station
ABG     -18.896365         19/20     -8.492055          20/20  -3.613900
MMB       2.809139         19/21     -9.117917          20/21  29.076634
CLF      -9.232790         23/23    -15.435281          23/23   0.977049
TUC      -1.518530         19/23     -8.824883          22/23  -1.561030
HON      -2.301954         22/23     -5.734694          23/23   3.168600
SFS      -8.671649         21/22     -7.718691          22/22   2.164563

        Better BFE 2h  Diff_RMSE_2h Better RMSE 2h
Station
ABG             14/20     -2.426212          13/20
MMB              9/21     -4.066959          19/21
CLF             14/23    -10.780001          23/23
TUC             14/23     -4.556452          19/23
HON             12/23     -1.039517          14/23
SFS             10/22     -2.412531          19/22

In [27]:
print(str_metrics)

BFE 1h: 41.921
RMSE 1h: 11.920
BFE 2h: 53.258
RMSE 2h: 11.920
Differences BFE 1h
Station
ABG   -18.896
MMB     2.809
CLF    -9.233
TUC    -1.519
HON    -2.302
SFS    -8.672
Sum differences: -37.812
Differences RMSE 1h
Station
ABG    -8.492
MMB    -9.118
CLF   -15.435
TUC    -8.825
HON    -5.735
SFS    -7.719
Sum differences RMSE: -55.324
Differences BFE 2h
Station
ABG    -3.614
MMB    29.077
CLF     0.977
TUC    -1.561
HON     3.169
SFS     2.165
Sum differences: 30.212
Differences RMSE 2h
Station
ABG    -2.426
MMB    -4.067
CLF   -10.780
TUC    -4.556
HON    -1.040
SFS    -2.413
Sum differences RMSE: -25.282

In [28]:
print(str_summary)

Information for station ABG
   StormIndex  BFE SYM-H  RMSE SYM-H     BFE 1h     BFE 2h    RMSE 1h  \
18       Mean  29.870066   18.580623  15.744441  24.489235  10.462987
19     Global  44.530046   19.620636  25.633680  40.916145  11.128581

      RMSE 2h
18  16.103891
19  17.194424
Metrics for persistence LDi_ABG-1h:
	RMSE: 13.092 | BFE: 36.519
Metrics for persistence LDi_ABG-2h:
	RMSE: 19.043 | BFE: 52.786

Information for station MMB
   StormIndex  BFE SYM-H  RMSE SYM-H     BFE 1h     BFE 2h    RMSE 1h  \
19       Mean  25.250677   20.798985  19.461824  27.849573  11.534310
20     Global  48.868305   21.841389  51.677444  77.944939  12.723472

      RMSE 2h
19  16.166386
20  17.774429
Metrics for persistence LDi_MMB-1h:
	RMSE: 13.976 | BFE: 63.204
Metrics for persistence LDi_MMB-2h:
	RMSE: 18.071 | BFE: 73.889

Information for station CLF
   StormIndex  BFE SYM-H  RMSE SYM-H     BFE 1h     BFE 2h    RMSE 1h  \
21       Mean  32.105841   25.317692  20.372385  26.983358  11.382085
22     Global  73.669954   28.087835  64.437164  74.647003  12.652555

      RMSE 2h
21  15.714834
22  17.307835
Metrics for persistence LDi_CLF-1h:
	RMSE: 13.115 | BFE: 66.489
Metrics for persistence LDi_CLF-2h:
	RMSE: 17.000 | BFE: 100.731

Information for station TUC
   StormIndex  BFE SYM-H  RMSE SYM-H     BFE 1h     BFE 2h    RMSE 1h  \
21       Mean  24.771577   20.244436  18.753803  24.929941  11.671323
22     Global  38.910315   21.551609  37.391785  37.349285  12.726727

      RMSE 2h
21  16.069330
22  16.995157
Metrics for persistence LDi_TUC-1h:
	RMSE: 13.454 | BFE: 46.376
Metrics for persistence LDi_TUC-2h:
	RMSE: 17.293 | BFE: 54.432

Information for station HON
   StormIndex  BFE SYM-H  RMSE SYM-H     BFE 1h     BFE 2h   RMSE 1h  \
21       Mean  15.580000   13.947675  11.226073  16.999788  8.290536
22     Global  29.023123   14.656344  26.721169  32.191723  8.921650

      RMSE 2h
21  12.806615
22  13.616827
Metrics for persistence LDi_HON-1h:
	RMSE: 10.061 | BFE: 36.434
Metrics for persistence LDi_HON-2h:
	RMSE: 14.496 | BFE: 45.655

Information for station SFS
   StormIndex  BFE SYM-H  RMSE SYM-H     BFE 1h     BFE 2h    RMSE 1h  \
20       Mean  27.214140   19.771696  19.880688  28.196461  12.321551
21     Global  54.335281   21.086529  45.663631  56.499844  13.367838

      RMSE 2h
20  17.362083
21  18.673998
Metrics for persistence LDi_SFS-1h:
	RMSE: 14.739 | BFE: 52.602
Metrics for persistence LDi_SFS-2h:
	RMSE: 19.692 | BFE: 85.238

In [29]:
import os
import constants

for station in constants.STATIONS:
    os.makedirs(f"./figs/{station}/forecasts", exist_ok=True)
    os.makedirs(f"./figs/{station}/bfe", exist_ok=True)
    os.makedirs(f"./figs/{station}/grids", exist_ok=True)

    os.makedirs(f"./figs_colors/{station}/forecasts", exist_ok=True)
    os.makedirs(f"./figs_colors/{station}/bfe", exist_ok=True)
    os.makedirs(f"./figs_colors/{station}/grids", exist_ok=True)

In [30]:
from PIL import Image
import os


def plot_grid(images_paths, output_path, rows, columns):
    fig, axes = plt.subplots(rows, columns, figsize=(13 * columns, 7 * rows))

    for idx, image_path in enumerate(images_paths):
        row, col = divmod(idx, columns)
        if os.path.exists(image_path):
            img = Image.open(image_path)
            axes[row, col].imshow(img)
            # axes[row, col].set_title(f"{hour + 1} ahead")
        else:
            print(f"Image not found: {image_path}")
            plt.close()
            return
        axes[row, col].axis("off")

    # plt.tight_layout(rect=[0, 0, 1, 1])
    plt.tight_layout(
        pad=0.01,  # Overall padding around the figure (default is 1.08)
        w_pad=0.01,  # Padding between subplots in width (default is 0.2)
        h_pad=0.01,  # Padding between subplots in height (default is 0.2)
    )
    plt.savefig(output_path, dpi=150, transparent=True, bbox_inches="tight")
    plt.close()


def plot_all_grids(same_color=False):

    plot_grid(
        [
            f"./figs{"_colors" if same_color else ""}/{station}/bfe/bfe-comparison-sym-ldi-{station}-LDi_{station}-1h.png"
            for station in constants.STATIONS
        ],
        f"./figs{"_colors" if same_color else ""}/grids/bfe-sym-diff-ldi-stations-1h_grid.png",
        rows=3,
        columns=2,
    )

    plot_grid(
        [
            f"./figs{"_colors" if same_color else ""}/{station}/bfe/bfe-ldi-{station}-LDi_{station}-1h.png"
            for station in constants.STATIONS
        ],
        f"./figs{"_colors" if same_color else ""}/grids/bfe-ldi-stations-1h_grid.png",
        rows=3,
        columns=2,
    )

    plot_grid(
        [
            f"./figs{"_colors" if same_color else ""}/{station}/bfe/bfe-comparison-sym-ldi-{station}-LDi_{station}-2h.png"
            for station in constants.STATIONS
        ],
        f"./figs{"_colors" if same_color else ""}/grids/bfe-sym-diff-ldi-stations-2h_grid.png",
        rows=3,
        columns=2,
    )

    plot_grid(
        [
            f"./figs{"_colors" if same_color else ""}/{station}/bfe/bfe-ldi-{station}-LDi_{station}-2h.png"
            for station in constants.STATIONS
        ],
        f"./figs{"_colors" if same_color else ""}/grids/bfe-ldi-stations-2h_grid.png",
        rows=3,
        columns=2,
    )

    for station in constants.STATIONS:
        for start_date, end_date, storm_index in storm_dates.TEST_STORMS:
            plot_grid(
                [
                    f"./figs{"_colors" if same_color else ""}/{station}/forecasts/forecast-ldi-{station}-LDi_{station}-1h-test-storm-{storm_index}.png",
                    f"./figs{"_colors" if same_color else ""}/{station}/bfe/bfe-ldi-{station}-LDi_{station}-1h-test-storm-{storm_index}.png",
                    f"./figs{"_colors" if same_color else ""}/{station}/forecasts/forecast-ldi-{station}-LDi_{station}-2h-test-storm-{storm_index}.png",
                    f"./figs{"_colors" if same_color else ""}/{station}/bfe/bfe-ldi-{station}-LDi_{station}-2h-test-storm-{storm_index}.png",
                ],
                f"./figs{"_colors" if same_color else ""}/{station}/grids/grid-{station}-test-storm-{storm_index}.png",
                rows=2,
                columns=2,
            )

        plot_grid(
            [
                f"./figs{"_colors" if same_color else ""}/{station}/forecasts/forecast-ldi-{station}-LDi_{station}-1h-test-storm-104-may-storm.png",
                f"./figs{"_colors" if same_color else ""}/{station}/bfe/bfe-ldi-{station}-LDi_{station}-1h-test-storm-104-may-storm.png",
                f"./figs{"_colors" if same_color else ""}/{station}/forecasts/forecast-ldi-{station}-LDi_{station}-2h-test-storm-104-may-storm.png",
                f"./figs{"_colors" if same_color else ""}/{station}/bfe/bfe-ldi-{station}-LDi_{station}-2h-test-storm-104-may-storm.png",
            ],
            f"./figs{"_colors" if same_color else ""}/{station}/grids/grid-{station}-test-storm-104-may-peak.png",
            rows=2,
            columns=2,
        )

        plot_grid(
            [
                f"./figs{"_colors" if same_color else ""}/{station}/forecasts/forecast-ldi-{station}-LDi_{station}-1h-test-storm-108-october-storm.png",
                f"./figs{"_colors" if same_color else ""}/{station}/bfe/bfe-ldi-{station}-LDi_{station}-1h-test-storm-108-october-storm.png",
                f"./figs{"_colors" if same_color else ""}/{station}/forecasts/forecast-ldi-{station}-LDi_{station}-2h-test-storm-108-october-storm.png",
                f"./figs{"_colors" if same_color else ""}/{station}/bfe/bfe-ldi-{station}-LDi_{station}-2h-test-storm-108-october-storm.png",
            ],
            f"./figs{"_colors" if same_color else ""}/{station}/grids/grid-{station}-test-storm-108-october-peak.png",
            rows=2,
            columns=2,
        )

    for station in constants.STATIONS:
        plot_grid(
            [
                f"./figs{"_colors" if same_color else ""}/{station}/forecasts/forecast-ldi-{station}-LDi_{station}-1h-test-storm-104-may-storm.png",
                f"./figs{"_colors" if same_color else ""}/{station}/forecasts/persistence-ldi-{station}-1h-test-storm-104-may-storm.png",
                f"./figs{"_colors" if same_color else ""}/{station}/forecasts/forecast-ldi-{station}-LDi_{station}-2h-test-storm-104-may-storm.png",
                f"./figs{"_colors" if same_color else ""}/{station}/forecasts/persistence-ldi-{station}-2h-test-storm-104-may-storm.png",
            ],
            f"./figs{"_colors" if same_color else ""}/{station}/grids/persistence-grid-{station}-test-storm-104-may.png",
            rows=2,
            columns=2,
        )


plot_all_grids(same_color=False)
plot_all_grids(same_color=True)

Image not found: ./figs/ABG/forecasts/forecast-ldi-ABG-LDi_ABG-1h-test-storm-93.png
Image not found: ./figs/ABG/forecasts/forecast-ldi-ABG-LDi_ABG-1h-test-storm-103.png
Image not found: ./figs/ABG/forecasts/forecast-ldi-ABG-LDi_ABG-1h-test-storm-109.png
Image not found: ./figs/MMB/forecasts/forecast-ldi-MMB-LDi_MMB-1h-test-storm-93.png
Image not found: ./figs/MMB/forecasts/forecast-ldi-MMB-LDi_MMB-1h-test-storm-94.png
Image not found: ./figs/SFS/forecasts/forecast-ldi-SFS-LDi_SFS-1h-test-storm-95.png
Image not found: ./figs_colors/ABG/forecasts/forecast-ldi-ABG-LDi_ABG-1h-test-storm-93.png
Image not found: ./figs_colors/ABG/forecasts/forecast-ldi-ABG-LDi_ABG-1h-test-storm-103.png
Image not found: ./figs_colors/ABG/forecasts/forecast-ldi-ABG-LDi_ABG-1h-test-storm-109.png
Image not found: ./figs_colors/MMB/forecasts/forecast-ldi-MMB-LDi_MMB-1h-test-storm-93.png
Image not found: ./figs_colors/MMB/forecasts/forecast-ldi-MMB-LDi_MMB-1h-test-storm-94.png
Image not found: ./figs_colors/SFS/forecasts/forecast-ldi-SFS-LDi_SFS-1h-test-storm-95.png